### ISSUE TITLE
autoscaling down to zero nodes is bad when using Torque

### ISSUE THREAD

**Issue by delocalizer** [awslabs/cfncluster#101]
An unfortunate behaviour of torque scheduler at least as configured in the default cfncluster deployment is that when there are zero nodes in the queue (pbsnodes file), any subsequently submitted jobs are _deleted._ This is a problem when no lower bound is set on number of **ComputeFleet** instances, as a low-activity period may eventually cause all of them to be removed, at which point further submitted jobs are deleted and so the trigger to autoscale up again is never activated.

**Comment by dougalb** [comment]
We're working to try and get the behaviour to Torque similar to SoGE and Openlava, so jobs can be submitted when there are no instances in the **ComputeFleet**. It is one of the challenges as the schedulers are not typically designed to have no resources for jobs!

You can use the [`initial_queue_szie`](http://cfncluster.readthedocs.io/en/latest/configuration.html#initial-queue-size) and [`maintain_initial_size`](http://cfncluster.readthedocs.io/en/latest/configuration.html#maintain-initial-size) parameters, to lauch a Torque cluster which starts with 1 instance in the **ComputeFleet**, can scale up and will not scale below one instance.

**Comment by delocalizer** [comment]
Thanks @dougalb, I realize this is a limitation of that particular scheduler rather than cfncluster per se. Perhaps worth documenting somewhere.

**Comment by guicho271828** [comment]
How about adding the master node itself as a compute node with offline / down state?
This will make the nodes list non-empty while preventing the jobs to be submitted.
Well, I'll try this on my own first.

**Comment by guicho271828** [comment]
by the way, `sudo` does not recognize the PATH to `/opt/torque/bin` and its not convenient.

**Comment by delocalizer** [comment]
This is certainly one approach that I have used; putting a block of code in the post-install script that adds MasterServer to the queue. The two (minor) downsides as I see it:1. It's not an out-of-the-box solution.2. If you have jobs that request all or close to all the resources on a compute node then you have to spec the head node to be as large as ComputeFleet instances. This is because pbs_sched deletes jobs from the queue that don't have the resources to ever run; if the queue contains only a weedy head node then you're then in the same position as having no nodes in the queue. The requirement to have a high-end head node is then no real cost saving over having a low-spec head node with configuration initial_queue_size = 1  and maintain_initial_size = true

Date: Tue, 24 May 2016 16:25:57 -0700

**Comment by guicho271828** [comment]
I seems creating a dummy node with unrealistic np in a down state allows me to queue some jobs

**Comment by guicho271828** [comment]
not sure if it prevents autoscaling to work
```
ubuntu@ip-172-31-29-195:~$ pbsnodes
localhost
     state = down,offline,MOM-list-not-sent
     power_state = Running
     np = 10000
     ntype = cluster
     mom_service_port = 15002
     mom_manager_port = 15003

ubuntu@ip-172-31-29-195:~$ qstat
Job ID                    Name             User            Time Use S Queue
------------------------- ---------------- --------------- -------- - -----
0.ip-172-31-29-195         STDIN            ubuntu                 0 Q batch          
```

**Comment by delocalizer** [comment]
That's clever; I like it.

Date: Tue, 24 May 2016 17:17:36 -0700

**Comment by dougalb** [comment]
So this is how we do it for Openlava https://github.com/awslabs/cfncluster-cookbook/blob/master/recipes/_master_openlava_config.rb#L66 and https://github.com/awslabs/cfncluster-cookbook/blob/master/templates/default/lsb.hosts.erb#L31. Looking to do the same for Torque. We'll get this into the backlog and also see if we can find a similar solution for SLURM. Then it should all be _out of the box_.

**Comment by guicho271828** [comment]
Additional note: adding dummy nodes to a server without launching corresponding mom may cause  trouble since torque keep trying to connect to the dummy node even when other nodes exists.
