### ISSUE TITLE
The desired way of using CfnClusterInstancePolicy and CfnClusterUserPolicy

### ISSUE THREAD

**Issue by yuanzhou** [awslabs/cfncluster#102]
I've been playing with CfnCluster for couple of weeks and manged to create the cluster and mount S3 or EBS, as well as installing other packages with the post_install_script. I'm still having hard times understanding how to use the [CfnClusterInstancePolicy](http://cfncluster.readthedocs.io/en/latest/iam.html#cfnclusterinstancepolicy) and [CfnClusterUserPolicy](http://cfncluster.readthedocs.io/en/latest/iam.html#cfnclusteruserpolicy).

Originally I went to IAM and created a new user and attached the `AdministratorAccess` policy to this user. Then configured the generated Access Key ID and Secret Access Key of this user into the CfnCluster config file like below:

```
[aws]
aws_access_key_id = #your_aws_access_key_id
aws_secret_access_key = #your_secret_access_key
aws_region_name = #region
```

In order to reduce the permissions granted to this user (the `AdministratorAccess` policy is way too powerful and not secure enough), I wanted to create and IAM role that doesn't have associated Access Key ID and Secret Access Key. This also allows me not to put the Access Key ID and Secret Access Key in the config file since I installed the CfnCluster on one of our EC2 instances.

How can I achieve this goal? 

I tested with the [ec2_iam_role](http://cfncluster.readthedocs.io/en/latest/configuration.html#ec2-iam-role) option, created a new policy based on the `CfnClusterInstancePolicy` and attached to the `cfncluster-iam-role`, then specified that option and value in the config file:

```
[aws]
aws_access_key_id = #your_aws_access_key_id
aws_secret_access_key = #your_secret_access_key

[cluster test]
ec2_iam_role = cfncluster-iam-role
```

This created the cluster no problem, but I still had to specify the Access Key ID and Secret Access Key from that existing user. And to my understanding, this `ec2_iam_role` with `CfnClusterInstancePolicy` is assigned to each cluster instance instead of the "user" who creates the cluster with CfnCluster.

What is the purpose of `CfnClusterUserPolicy` and how should I use it with an IAM role?

**Comment by yuanzhou** [comment]
Just wanted to add more info regarding this topic. Once the cluster gets created, I could see the corresponding RootRole was created with an inline policy. And the content of the inline policy is almost the same as the sample [CfnClusterInstancePolicy] (http://cfncluster.readthedocs.io/en/latest/iam.html#cfnclusterinstancepolicy) except it has the detailed resource ARN specified.

**Comment by mohanasudhan** [comment]
This question is similar to #151 . Following wiki http://cfncluster.readthedocs.io/en/latest/iam.html explains the need for CfnClusterInstancePolicy & CfnClusterUserPolicy

ec2_iam_role --> EC2 IAM Role that will be attached to all instances in the cluster. In here we expect CfnClusterInstancePolicy
AWS credential section in cfncluster configuration is required for successful execution cfncluster command (in here we expect user or role to have CfnClusterUserPolicy). If not defined, boto will attempt to use a) environment (which is your case) or b) EC2 IAM role.
