### ISSUE TITLE
Tasks not executed by the Compute Nodes in Ubuntu Cfncluster image

### ISSUE THREAD

**Issue by diegomartin** [awslabs/cfncluster#104]
Hi,

I'm trying to use CfnCluster 1.2.1 for GPU computing and I'm using a custom AMI based on the Ubuntu 14.04 CfnCluster AMI.

Everything is created correctly in the CloudFormation console, although when I submit a new test task to Oracle Grid Engine using qsub from the Master Server, it never gets executed from the queue according to qstat. It stays always in status "qw" and never enters state "r".

It seems to work fine with the Amazon Linux AMI (using user ec2-user instead of ubuntu) and the exact same configuration. Also, the master instance announces the number of remaining tasks to the cluster as a metric, and new compute instances are auto-scaled as a result.

What mechanisms does CfnCluster or Oracle Grid Engine provide to further debug this? I took a look at the log files, but didn't find anything relevant. What could be the cause for this behavior?

Thank you,

Diego

**Comment by diegomartin** [comment]
I think I found the solution. It seems to be the same issue as the one described in #86.

I fixed it by adding the following line to the CfnCluster configuration file:

`    base_os = ubuntu1404`

If a custom_ami is specified but no base_os is specified, it defaults to use the Amazon Linux, which uses a different method to configure SGE. There may be problems in the SGE configuration performed by CfnCluster if base_os and custom_ami os are different.

I would suggest to clarify this in the configuration documentation (either as part of the base_os or the custom_ami parameter). Maybe one of this parameters need to be compulsory for the cluster to boot?

**Comment by dougalb** [comment]
Thanks for raising the issue. We'll make updates to the documentation.

**Comment by andygotz** [comment]
Hi,

does cfncluster support ubuntu1404 clusters now? From this issue I understood yes but when we tried to create a cluster with the following configuration parameters:
base_os = ubuntu1404
custom_ami = ami-38e80e57

on the region eu-central-1 it failed to create the cluster. 

The failure was a ROLLBACK after the SQS-CREATE_IN_PROGRESS event and during the create user or so it seemed from the logs.

Should we assume ubuntu1404 is not supported yet? Or should we persist and try to make it work.

We are using cfncluster version  1.2.1 installed with pip.

Thank you for any light you can shed on this to save us time.

Andy

**Comment by dougalb** [comment]
Hi Andy,

Ubuntu 1404 is absolutely supported. Can you provide some more details regarding your issue. The AMI id you have provided is the base AMI from CfnCluster, so you do not need to put it in the config.

What is your AWS Account Number and I can see if I can determine from problem.

-Dougal

**Comment by andygotz** [comment]
Hi Doug,

thanks a lot for this +ve answer. Our account number is 971096242052. I have attached the cfncluster config file.

[config.txt](https://github.com/awslabs/cfncluster/files/322476/config.txt)

Any help you can offer us to get an ubuntu cluster up and running would be highly appreciated.

Andy

**Comment by dougalb** [comment]
If you run `cfncluster status fdmtest2`, you should see the errors reported by CloudFormation before it did the rollback. 

At a high level, you are attempting to launch into a VPC which does not have the required networking configured. I see that you are attempting to use a HTTP proxy however the VPC does not have any way to access anything because either a) it has not IGW or b) it has no VGW. Also you do not need to specify `custom_ami`.

I would recommend configuring your VPC with an IGW to get comfortable with CfnCluster and it's config options.

**Comment by andygotz** [comment]
Thanks for the quick answer. I will have to learn more about IWG and VGW to solve the problem. We will get back to you once we have understood the networking aspects better and if we have still not solved the problem.

Kind regards

Andy

**Comment by dougalb** [comment]
You can email me at dougalb at amazon dot com, and I can probably connect you will our local team.
