### ISSUE TITLE
Document `tenancy` option

### ISSUE THREAD

**Issue by guicho271828** [awslabs/cfncluster#105]
Amazon clusters generally have varying range of performance instability, due to hyperthreading cores, effect of hypervisors, and the other users running a program on the same machine. While this is ok with batch jobs i.e. the jobs that solely aim to get the jobs done, this is problematic for running massive computational experiments [1]. Unless using dedicated instances, time measurements are unreliable and the reproducibility is not guaranteed.

currently `cluster_type` supports `ondemand` and `spot` only.

[1] Kotthoff, Lars. "Reliability of computational experiments on virtualised hardware." Journal of Experimental & Theoretical Artificial Intelligence 26.1 (2014): 33-49.

**Comment by dougalb** [comment]
Hi, I think you will find the following AWS re:Invent session very helpful in understanding performance on EC2 - https://www.youtube.com/watch?v=SZAvtbrIBAk. 

To address your specific question, the `cluster_type` parameter refers to the purchasing model. Customer who have a need for dedicated tenancy, would use the `tenancy` parameter. More details of Dedicated Tenancy can be found here - http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/dedicated-instance.html. Please note, EC2 performance is not related to tenancy.

**Comment by guicho271828** [comment]
is `tenancy` parameter some sort of undocumented option? I couldnt find it here.
http://cfncluster.readthedocs.io/en/latest/configuration.html#cluster-type

**Comment by dougalb** [comment]
Oops, looks like it's missing in the docs. It is a separate parameter in the `cluster` section. It supports the values __default__ and __dedicated__. We'll get the docs updated.

Again please note, tenancy is not related performance or resource allocations of an instance.

**Comment by guicho271828** [comment]
thanks for the quick response. ok, it was just not in the doc.

Performance is surely affected when there are other users on the same physical machine. For example, if one user is running a very memory-intensive application with a frequent read/write to the main memory, it results in a memory bus contention which affects the performance [2]. So, as other users read/write more memory, my program gets slower.

Again, note that the problem is not the absolute performance i.e. that my program gets slower, but that the performance is unstable/unpredictable. It is perfectly OK if the instance is consistently slow. However, I cannot predict if it gets slower or not, since I cannot control the behavior of the other users on the same phisical machine.

This is a problem if I need to compare the performance of program X and program Y. Example: During the experiments running program X there may be no other users on the same machine, while after a few hours later some user may launch an instance somewhere in the world, Amazon assigned it to the same physical machine as mine, and program Y gets slower. If program X is my proposed method and Y is an old method, it is unfairly favoring my program X. One common method to tackle this problem is to run the experiments multiple times and take the average, but having a dedicated instance also eliminates this problem.

[2] Burns, Ethan, et al. "Best-first heuristic search for multicore machines." Journal of Artificial Intelligence Research (2010): 689-743.

**Comment by dougalb** [comment]
Typically, you would not share a physical machine if you are using the
largest instance sizes. If you have an application that uses all if the
system resources, you would not select a small instance.

While smaller instances likely share physical hosts, the resources are
allocated per instance.

**Comment by guicho271828** [comment]
hmm, but for example, a C4 instance has 36 VCPUs, (36 HT cores), while Xeon E2666 v3 has 10 cores, which means with 2 CPU slots it is 40 HT cores, so there are 4 CPUs that looks like Amazon is free to assign to the other users.

**Comment by delocalizer** [comment]
more likely reserved for the hypervisor

**Comment by guicho271828** [comment]
@delocalizer Well, yes, I also believe so. but the problem is that for academic papers this is just another bit that is not verifiable for people outside Amazon. The reviewers start complaining about it, possible cause of rejection of a paper.

**Comment by mndoci** [comment]
@guicho271828 

I used to run product management for EC2 instances. As stated earlier, you shouldn't use dedicated instances for performance reasons. For the largest instance size in a family the performance should be the same for all dimensions.  Many of our customers routinely publish papers using EC2 instances. As long as referees are comfortable with virtual machines you should be OK.

**Comment by mohanasudhan** [comment]
Closing this issue as dogul and deepak already answered customer query here. Don't hesitate to reopen the issue if you need any more infromation
