### ISSUE TITLE
How to modify `cfn_scheduler_slots` from my local .cfncluster/config ?

### ISSUE THREAD

**Issue by guicho271828** [awslabs/cfncluster#107]
`cfn_scheduler_slots` affects the number of processors that the scheduler assigns to each node.
This is important for me to disable the hyperthreading, which is not a true core. The problem is I have no idea where does this value comes from in ruby. Id like to use "cores" instead of "vcpu".

1. https://github.com/awslabs/cfncluster-cookbook/blob/master/attributes/default.rb#L134
1. https://github.com/awslabs/cfncluster-cookbook/blob/master/recipes/_prep_env.rb#L20
2. https://github.com/awslabs/cfncluster-cookbook/blob/master/templates/default/cfnconfig.erb#L8
3. https://github.com/awslabs/cfncluster-cookbook/blob/master/files/default/compute_ready#L8
4. https://github.com/awslabs/cfncluster-node/blob/develop/sqswatcher/sqswatcher.py#L147
5. https://github.com/awslabs/cfncluster-node/blob/develop/sqswatcher/plugins/torque.py#L34
New nodes are created in the last step.

Although there are many easy workaround, I like a better solution.

Easy workaround 1:
directly modifying /etc/cfncluster/config in step 3 from `pre_install` scripts (I will try this tomorrow)

Easy workaround 2:
setting `default_np` value of Torque server to a fixed value.

Both workarounds are not flexible enough because it does not reflect the real cluster types, and instead relies on hand/hard coding.

Edit: found where the value is set.

**Comment by dougalb** [comment]
This feature is experimental and only recently added. See https://github.com/awslabs/cfncluster/issues/36 for more details. I would suggest that you use SGE, if you need this feature. The Torque scheduler is not as effective in CfnCluster as SGE or Openlava. This is something we're trying to improve but it's driven by scheduler features, something we don't modify.

**Comment by guicho271828** [comment]
> #36 
> extra_json = { "cfncluster" : { "cfn_scheduler_slots" : "cores" } }

That's wonderful. Thanks! I should have checked the past issues.

**Comment by lukeseawalker** [comment]
Hi yanpanlau,
please take a look at the scaling_adjustment and scaling_adjustment2 parameters into the scaling section of the configuration file [here](https://cfncluster.readthedocs.io/en/latest/configuration.html#scaling-adjustment)
