### ISSUE TITLE
Each time I create a cluster an extra 20 Gb Volume is created

### ISSUE THREAD

**Issue by geekson** [awslabs/cfncluster#109]
Hello,

I don't put any info regarding a shared folder in my configuration although I get a 20gb volume in my cluste once its complete. What's that for? Below is my config.

[aws]
aws_region_name = eu-west-1
aws_access_key_id = XXXXXXXXXXXXXX
aws_secret_access_key = XXXXXXXXXXXXXXXXXX-X

[cluster HPC]
vpc_settings = HPC
key_name = Key Pair
scheduler = slurm
base_os = ubuntu1404

[vpc SPEOS HPC]
master_subnet_id = subnet-bd1402ca
vpc_id = vpc-5b6fcc3e

[global]
update_check = true
sanity_check = true
cluster_template = HPC

**Comment by guicho271828** [comment]
it is most likely the root drive for booting the OS.

**Comment by geekson** [comment]
Hi,

I don't think so, the master already has a drive:

![image](https://cloud.githubusercontent.com/assets/15198277/15701569/48e90966-27db-11e6-9623-309a3e43677f.png)

**Comment by jamiekin** [comment]
It is the shared volume for the cluster.

http://cfncluster.readthedocs.io/en/latest/configuration.html#ebs-section

-Jamie

On Jun 1, 2016, at 12:29 AM, geekson <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I don't think so, the master already has a drive:

[image]<https://cloud.githubusercontent.com/assets/15198277/15701569/48e90966-27db-11e6-9623-309a3e43677f.png>

-

**Comment by guicho271828** [comment]
sorry you are right.
if you don't put any data for shared drive, it defaults to 20GB. check here
https://github.com/awslabs/cfncluster/blob/master/cli/cfncluster/examples/config

and also the doc

**Comment by geekson** [comment]
Thanks guys. I notice this looks like a shared drive. 

Now, I wonder how come it would still be there even though I changed my config (cf above).

**Comment by geekson** [comment]
Even though I force ebs_volume_id value to:

ebs_volume_id = NONE

It still create it. I'm creating it from windows cmd any relation?

**Comment by dougalb** [comment]
Within CfnCluster, almost all values have a default. You cannot disable the creation of the _shared_ EBS volume, however you can change the size to be 1GB. 

CfnCluster is designed around the concept of [Beowulf](https://en.wikipedia.org/wiki/Beowulf_cluster) cluster and as such has a common shared filesystem for /home and a shared volume. Why do you want to remove the shared volume?

**Comment by geekson** [comment]
@dougalb Hello,
I thought it could be better to share a folder from the headnode. I guess I'll use this shared drive to put my application. Thanks for your answer.
