### ISSUE TITLE
Configuration for specifing not only the region, but also the availability zone

### ISSUE THREAD

**Issue by guicho271828** [awslabs/cfncluster#110]
Spot price may depend significantly on the availability zone.

![screenshot from 2016-06-03 09 11 28](https://cloud.githubusercontent.com/assets/1321968/15765070/769dfeac-296b-11e6-9594-dfd3ce947712.png)

**Comment by dougalb** [comment]
The `master_subnet_id` and `compute_subnet_id` values map to availability zone.

**Comment by guicho271828** [comment]
are they the same things?
For example, http://cfncluster.readthedocs.io/en/latest/configuration.html#master-subnet-id lists `subnet-xxxxxx` as an example, but it's not clear from the text if we can specify `us-west-2a` here. maybe an update to the doc may be helpful.

**Comment by guicho271828** [comment]
and I don't think there is a way to know which subnet belongs to which availability zone.

**Comment by dougalb** [comment]
Within Amazon VPC, a subnet is created within an Availability Zone. When you specify a subnet, your are explicitly specifying an Availability Zone.

http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Subnets.html#VPCSubnet

You can look up the AZ of a subnet using the CLI or using the console.

**Comment by guicho271828** [comment]
ok, thank you for the clarification.
I managed to see the mapping from subnets to AZ.
```
$ aws ec2 describe-subnets
{
    "Subnets": [
        {
            "VpcId": "vpc-31404b53", 
            "CidrBlock": "172.31.16.0/20", 
            "MapPublicIpOnLaunch": true, 
            "DefaultForAz": true, 
            "State": "available", 
            "AvailabilityZone": "us-west-2b", 
            "SubnetId": "subnet-01765c75", 
            "AvailableIpAddressCount": 4090
        }, 
        {
            "VpcId": "vpc-31404b53", 
            "CidrBlock": "172.31.32.0/20", 
            "MapPublicIpOnLaunch": true, 
            "DefaultForAz": true, 
            "State": "available", 
            "AvailabilityZone": "us-west-2a", 
            "SubnetId": "subnet-52808830", 
            "AvailableIpAddressCount": 4091
        }, 
        {
            "VpcId": "vpc-31404b53", 
            "CidrBlock": "172.31.0.0/20", 
            "MapPublicIpOnLaunch": true, 
            "DefaultForAz": true, 
            "State": "available", 
            "AvailabilityZone": "us-west-2c", 
            "SubnetId": "subnet-31e5b077", 
            "AvailableIpAddressCount": 4091
        }
    ]
}
```
