### ISSUE TITLE
Slurm Accounting Configurations

### ISSUE THREAD

**Issue by yuanzhou** [awslabs/cfncluster#111]
I've made positive progress with CfnCluster and we are using Slurm as the job scheduler. Our application to be deployed on this CfnCluster also uses the Slurm `acct` to check the job status.

By default the `sacct` will output "SLURM accounting storage is disabled", so I'll have to install `slurmdbd` in order to use their MySQL-based accounting storage. I tried several means to configure the slurmdbd with no luck.

Can anyone give me some pointers? I noticed that CfnCluster cookbook installs slurm at `/opt/slurm`, but when I installed the rpm version of slurmdbd, I have no idea how to configure it.

**Comment by yuanzhou** [comment]
I tried several times by just using `accounting_storage/mysql` without SlurmDBD,

````
# ACCOUNTING
JobAcctGatherType=jobacct_gather/linux
#JobAcctGatherFrequency=30
#
AccountingStorageType=accounting_storage/mysql
AccountingStorageHost=ip-172-31-30-239
AccountingStorageLoc=slurm_acct_db
AccountingStoragePass=123
AccountingStorageUser=slurm
````

But still getting the following error:

````
[root@ip-172-31-30-239 shared]# sacct
sacct: error: Couldn't find the specified plugin name for accounting_storage/mysql looking at all files
sacct: error: cannot find accounting_storage plugin for accounting_storage/mysql
sacct: error: cannot create accounting_storage context for accounting_storage/mysql
sacct: error: Couldn't find the specified plugin name for accounting_storage/mysql looking at all files
sacct: error: cannot find accounting_storage plugin for accounting_storage/mysql
sacct: error: cannot create accounting_storage context for accounting_storage/mysql
sacct: error: Problem talking to the database: Operation not permitted
````

I searched all but couldn't find any useful solution. I checked the CfnCluster cookbook at https://github.com/awslabs/cfncluster-cookbook/blob/master/recipes/slurm_install.rb#L37 and it seems we'll need to specify the `mysql_config` during the configuration. Otherwise there's no `accounting_storage_mysql.so` will be created in `/opt/slurm/lib`.

Is there any thing I can do to have the CfnCluster installed Slurm wot work with MySQL as accounting storage?

**Comment by yuanzhou** [comment]
@dougalb any suggestions that we can enable the Slurm Accounting with CfnCluster?

**Comment by dougalb** [comment]
In cfncluster-1.3, the slurm build should include the mysql libraries. Please can you test configuring accounting using the latest release?

**Comment by yuanzhou** [comment]
@dougalb awesome! I'll give it a try! Perfect timing!

**Comment by yuanzhou** [comment]
So I tried CfnCluster 1.3 and created the AWS cluster that users slurm as the job scheduler. I wanted to use  MySQL as the direct accounting storage without slurmdbd. I have MySQL server installed and created `slurm_acct_db` database. In this testing case, I'm using MySQL `root` user with password `123`,  and `ip-172-31-26-149` the the master node hostname. Below is the corresponding section of `/opt/slurm/etc/slurm.conf`:

````
# ACCOUNTING
JobAcctGatherType=jobacct_gather/linux
#JobAcctGatherFrequency=30
#
AccountingStorageType=accounting_storage/mysql
AccountingStorageHost=ip-172-31-26-149
AccountingStorageLoc=slurm_acct_db
AccountingStoragePass=123
AccountingStorageUser=root
````

I also did `scontrol reconfigure`, but got this message when I ran `sacct` command:

````
sacct: error: mysql_real_connect failed: 1130 Host 'ip-172-31-26-149.ec2.internal' is not allowed to connect to this MySQL server
sacct: error: The database must be up when starting the MYSQL plugin.  Trying again in 5 seconds.
````

And I also tried "localhost" as the `AccountingStorageHost` but got a different message instead:

````
sacct: error: issue converting tables
sacct: error: Couldn't load specified plugin name for accounting_storage/mysql: Plugin init() callback failed
sacct: error: cannot create accounting_storage context for accounting_storage/mysql
sacct: error: issue converting tables
sacct: error: Couldn't load specified plugin name for accounting_storage/mysql: Plugin init() callback failed
sacct: error: cannot create accounting_storage context for accounting_storage/mysql
sacct: error: Problem talking to the database: Interrupted system call
````

The message is different from what I saw when using CfnCluster 1.2. It seems slurm could find mysql plugin this time, but can't load it or having trouble talking to the MySQL database.

**Comment by jsmedmar** [comment]
@sean-smith @yuanzhou, did you guys figured this out?

**Comment by eugenov** [comment]
also looking for the cure!

**Comment by demartinofra** [comment]
Sorry @jsmedmar if we missed your comment but the issue was marked as resolved and we were not monitoring it (in such cases I'd recommend you open a new issue if needed)

@jsmedmar @eugenov there is an official blog post outlining the accounting setup for Slurm in ParallelCluster: https://aws.amazon.com/blogs/compute/enabling-job-accounting-for-hpc-with-aws-parallelcluster-and-amazon-rds/. Can you check that out and get back to us if you still require some guidance?
