### ISSUE TITLE
sns:GetTopicAttributes required for IAM role

### ISSUE THREAD

**Issue by dkoppstein** [awslabs/cfncluster#113]
For the CfnClusterUserPolicy on the [CFNcluster IAM](http://cfncluster.readthedocs.io/en/latest/iam.html) webpage, I was getting some error saying that the sns:GetTopicAttributes was not allowed. 

Changing to this:

```
        {
            "Sid": "SNSDescribe",
            "Action": [
                "sns:ListTopics",
                "sns:GetTopicAttributes"
            ],
            "Effect": "Allow",
            "Resource": "*"
        },
```

seemed to fix the issue.

**Comment by dougalb** [comment]
Thank you for catching this. We'll get the docs updated.

**Comment by mohanasudhan** [comment]
policy is updated http://cfncluster.readthedocs.io/en/latest/iam.html. closing
