### ISSUE TITLE
Docker support or other container technology?

### ISSUE THREAD

**Issue by robnagler** [awslabs/cfncluster#114]
Are there plans to allow users to manage a cluster of MPI-enabled Docker containers? 

We have built a prototype of this on bare metal, but would like to compare this to a fleet of user-specified Docker containers.

**Comment by dougalb** [comment]
We are working towards ensuring that Docker is part of the base AMI and available to the default cluster user here https://github.com/awslabs/cfncluster-cookbook/issues/1. 

MPI-enabled will depend on the containers and schedulers. You may well be able to use the Openlava docker support https://github.com/openlava/openlava/blob/master/examples/docker/docker_integration.txt.

**Comment by robnagler** [comment]
Unfortunately the schedulers do not support running the containers on compute nodes. What OpenLava supports is running the master inside a container. With MPI, you have to be able to ssh into an already running container.

I realize that CfnCluster's job is not to handle this case, but it would be nice if there were a scheduler that assumes the entire cluster belongs to a user. This scheduler could then setup the job for a single MPI job.

**Comment by mohanasudhan** [comment]
As dougal point we can prioritize adding docker to nodes but it doesn't add much value with schedulers we have today in cfncluster. If there are more request we can look at adding singularity container bits into node which can be used with current schedulers we have today. 

Closing this issue as we are tracking docker separately. If you need singularity support pls create another issue
