### ISSUE TITLE
How to expand the shared EBS volume based on snapshot

### ISSUE THREAD

**Issue by guorongxu** [awslabs/cfncluster#115]
I have taken a snapshot from an EBS volume with 100GB, but I would like to create a 1TB EBS volume based on the snapshot. However, I found the attached new EBS volume is still only 100GB after I created the cluster. Is there any way to see the other 900GB space and also the whole 1TB volume share with compute nodes?

Thanks,

**Comment by schmutze** [comment]
Hi Guorong,

In order to utilize the new space, you'll need to expand the filesystem. If your original volume also contains a partition, you'll need to extend the partition first before you expand the file system. The following document will guide you through the process, including checking if you need to resize the partition first with a link to instructions:

http://amzn.to/294ymO6

Please let me know if you have any questions.

thanks,
chad

**Comment by guorongxu** [comment]
Hi Chad,

Thanks a lot for your response!

Currently, I installed my software packages on one small EBS volume and then take a snapshot. Then I set the snapshot id in the cfncluster config file to create a new cluster with an EBS volume based on the snapshot. Since cfncluster can support only one EBS volume which can be shared with other compute nodes, I have to resize the new attached EBS volume created by my snapshot. When I create a new EBS volume based on snapshot with the large size from AWS Console, I can resize the larger EBS volume by simply running the command "sudo resize2fs /dev/xvd*". So I am wondering if you can provide this kind of feature to easily resize the attached EBS volume in the cluster. I know there is one option "volume_size" in the cfncluster config file, but that is only used for new blank volume instead of the snapshot.

Best,
Guorong

**Comment by chambm** [comment]
I second the suggestion to have a turnkey solution to expand the EBS drive's space. But if it switches to EFS then it's a moot point!

**Comment by johnbot1** [comment]
Except for the cost with EFS being $0.30/GB compared to standard general purpose SSD at $0.10/GB. Having built-in EFS support would be useful especially for those wanting to share file systems between cfn and other compute/workstation instances.

John

**Comment by guorongxu** [comment]
Thanks a lot for your valuable suggestions!

Actually I installed a lot of software packages on a 100GB EBS volume and then I took a snapshot for publish. However, the users have to create a large EBS volume based on my published 100GB EBS volume if they have a lot of dataset to process. I am not sure if you can provide a easy and quick way for users to create a cluster with a large EBS volume and everything is preinstalled. 

Your response would be really appreciated!

Guorong
