### ISSUE TITLE
Specifying multiple keys in the config file

### ISSUE THREAD

**Issue by andygotz** [awslabs/cfncluster#117]
Hi,

first of all cfncluster is working well with Ubuntu - thanks! The problem we had previously was due to specifying http_proxy in the config file. Tip for beginners: do not specify http_proxy in the config file unless you know what you are doing. Now my question:

Is it possible to specify multiple keys in the config file to give access to more than one user to the master node? How?

Thanks
Andy

**Comment by f403** [comment]
You can update your _authorized_keys_ with the _post_install_ script.
