### ISSUE TITLE
Wrong type for the argument --extra-parameters for update

### ISSUE THREAD

**Issue by recheliu** [awslabs/cfncluster#118]
In line [104](https://github.com/awslabs/cfncluster/blob/master/cli/cfncluster/cli.py#L104) of cli.py, it sets the type as "str" for "--extra-parameters":

```
pupdate.add_argument("--extra-parameters", "-p", type=str, dest="extra_parameters", default=None,
```

help='add extra parameters to stack update')

Nevertheless, I believe that the type should be not "str". Instead, it should be "json.loads", as the same argument for "create" in line [89](https://github.com/awslabs/cfncluster/blob/master/cli/cfncluster/cli.py#L89) of the same file.

Otherwise, there is no way to pass extra parameters as a dict to update.

**Comment by lukeseawalker** [comment]
Fixed in https://github.com/awslabs/cfncluster/commit/88f42fb52ad6abbad22ba5221195d8d9ec5c56f9
