### ISSUE TITLE
Add tags to the config file

### ISSUE THREAD

**Issue by craigbruce** [awslabs/cfncluster#119]
I can see an example on #79 on how to set the tags for your cluster as part of the ``create`` command, this is rather verbose and error prone. It would be great if I could set my desired tags in my config file. Is this something that is on the roadmap?

**Comment by dougalb** [comment]
Great enhancement! Will look to getting this added.

**Comment by pansapiens** [comment]
It would be great if this was supported. As a non-commandline alternative I was going to make a custom cfncluster CloudFormation template tagging every resource as per our organisational requirements, but having support from the config file would be preferred.

**Comment by dougalb** [comment]
This has been added to cfncluster-1.3.0. Doc link - http://cfncluster.readthedocs.io/en/latest/configuration.html#tags
