### ISSUE TITLE
Compute instances won't stop spawning

### ISSUE THREAD

**Issue by mikerossgithub** [awslabs/cfncluster#122]
After deleting a cluster and terminating all instances (master and compute), compute instances keep spawning.

To create the cluster, I followed the instructions here: http://cfncluster.readthedocs.io/en/latest/hello_world.html

To delete the cluster, I called "cfncluster delete mycluster" from my host machine (a separate EC2 instance), which appeared to execute fine. I have now terminated the host machine in addition to the master instance and all compute instances. But the compute instances keep respawning.

Is there any way to stop this?

**Comment by digout** [comment]
Terminate the cloudformation item.

-- bruno

On 20 lug 2016, at 18:38, mikerossgithub <notifications@github.com<mailto:notifications@github.com>> wrote:


After deleting a cluster and terminating all instances (master and compute), compute instances keep spawning.

To create the cluster, I followed the instructions here: http://cfncluster.readthedocs.io/en/latest/hello_world.html

To delete the cluster, I called "cfncluster delete mycluster" from my host machine (a separate EC2 instance), which appeared to execute fine. I have now terminated the host machine in addition to the master instance and all compute instances. But the compute instances keep respawning.

Is there any way to stop this?

**Comment by jamiekin** [comment]
You should see the running stack in the AWS console by visiting https://console.aws.amazon.com/cloudformation.  Simply select the active stack and delete it.  This will remove any running instances and also delete the auto-scaling group and any other resources associated with this cluster.

 

-Jamie

**Comment by mikerossgithub** [comment]
Thank you. That did the trick
