### ISSUE TITLE
create cfncluster fails at computefleet

### ISSUE THREAD

**Issue by rollinroy** [awslabs/cfncluster#127]
Hi.  I've created a modified ubuntu AMI for cfncluster based on ami-f2bf5492.  The custom AMI specifies a 12GB root device and I've included the following cluster parameters in my cfncluster:
base_os = ubuntu1404
master_root_volume_size = 12
compute_root_volume_size = 12
Everything else is defaulted (include 2 compute nodes)

When I first created the cluster it was successful based on some trivial tests.  I then deleted the cluster and a day later creating the same custom cluster failed at create ComputeFleet (which I assume is creating the compute nodes.  I noticed from the ec2 console that the two compute nodes were being initialized; then one completed; and just when the second one completed I received failure and rollback.  My wag is that it was a timeout associated with starting one of the compute nodes.  Anyway, while writing this post, I attempted to create the custom cluster and all worked well.  I'll try using the --norollback and check out the running instances.  Any other ideas or suggestions?  I'll attach the call stack of the failed issue.
[aws_cfncluster_fail.txt](https://github.com/awslabs/cfncluster/files/419630/aws_cfncluster_fail.txt)

tia.

cheers, roy

**Comment by dougalb** [comment]
Launch the cluster with the --norollback option and then look at the
/var/log/cfn-init.log file on a ComputeFleet instance for errors during the
bootstrapping.

**Comment by yuanzhou** [comment]
I encountered this same issue today. Creating the cluster with the same template.

**Comment by yuanzhou** [comment]
Just to update. It failed several times the other day, but when I tried again it worked. And I tried CfnCluster 1.3.1 and didn't reproduce this issue. So I thought it might be a glitch on AWS.

**Comment by dougalb** [comment]
Can you please post your account number, region and cluster name. This is
not expected behavior and I would like to see if there is something we
explain.

**Comment by yuanzhou** [comment]
@dougalb I deleted the failed cluster and recreated it. So I can't post the account number and cluster name. Sorry about that. But I did encounter this unexpected behavior several times with 1.2 the other day. I was using the same JOSN template via CloudFormation, which worked without any problem before. Then it failed several times and rolled back the cluster creation. I tried again before I went home that day, and the last try worked, surprisingly. 

So far I don't see this creation issue with 1.3

**Comment by dougalb** [comment]
Please just post your region and account number. I can find the rest.

When you say using the same template, are you using a custom CloudFormation
template?

**Comment by yuanzhou** [comment]
@dougalb 

````
region: us-east-1
account: 495666495561
````

The template I used was the one generated by CfnCluster, and I saved it into a JSON template file. The I uploaded the form via CloudFormation and specified parameters.

**Comment by dougalb** [comment]
Okay, so that is not something we test today and not something we typically support. The issue you are having is likely related to the fact that you are trying to launch two stacks that both have the same value for EBSVolumeId. The second MasterServer is trying to attach the volume and it will fail.

You would see this in your logs, if you launch with --norollback and look at the /var/log/cfn-init.log.

I would avoid creating your own templates and rather use the one already hosted in S3, which is here: https://s3.amazonaws.com/us-east-1-cfncluster/templates/cfncluster-1.3.1.cfn.json

In addition, you must be very specific about what parameters you are copying between stacks.
