### ISSUE TITLE
default template fails to curl cookbook tar

### ISSUE THREAD

**Issue by mmanfred** [awslabs/cfncluster#133]
I was trying to test cfncluster and was unable to start an sge master.  Upon looking at the logs i saw that curl was failing and outputting binary to the log file.

I changed
"curl -s -L -o /etc/chef/cfncluster-cookbook.tgz -v /etc/chef/cfncluster-cookbook.tgz $cookbook_url\n",
To
"curl -s -L -o /etc/chef/cfncluster-cookbook.tgz -v $cookbook_url\n",
in the two locations in the 1.3.1 json file. That seemed to resolve that issue.

**Comment by dougalb** [comment]
Thanks for catching that. It should be "curl -s -L -o /etc/chef/cfncluster-cookbook.tgz -z /etc/chef/cfncluster-cookbook.tgz $cookbook_url\n",
