### ISSUE TITLE
restart cluster erratic behavior

### ISSUE THREAD

**Issue by rollinroy** [awslabs/cfncluster#136]
I created a cluster based on a custom ami (based on ubuntu 16.0.4) and submitted a trivial job (qsub -b y hostname) and all worked well.  I think stopped the cluster (via cfncluster stop roycc) and then I restarted (via cfncluster start roycc).  

After the cluster restarted there was no compute nodes as expected.  I submitted the same trivial job (qsub -b y hostname) and the job went into 'qw' state (waiting for auto-scaling to create a compute node).  Eventually a compute node was created; but my job never ran; it stayed in 'qw' state.  Eventually 10 compute nodes were created and launched but my job never ran.  

I deleted the job and submitted it again with -now y flag added.  It failed with the message "Your qsub request could not be scheduled; try again later.".  If I submitted the job without the -now y flag, the job just goes into the qw state.

Any suggestion of how to trouble shoot this?  I could also try this with the standard cfncluster AMI.

tia.

cheers, roy

**Comment by adavanisanti** [comment]
+1

**Comment by rollinroy** [comment]
This issue can be closed.
cheers, roy
