### ISSUE TITLE
Custom libraries (paths /usr/local/bin and /usr/bin) are lost inside cluster master and slaves

### ISSUE THREAD

**Issue by apalazzin** [awslabs/cfncluster#138]
Hi,

I've created my custom AMI, starting from the **cfncluster-1.3.1-ubuntu-1404-lts-hvm-201609030709 (ami-3ff0824c)**, with installed the libraries and the dependencies of my company.

If I create manually the ec2 server from my custom AMI, everything is properly installed.
If I create the cfncluster from the same custom AMI, something is incorrectly installed (some libraries inside `/usr/local/bin` and `/usr/bin` are lost and don't exist anymore).

I don't understand this problem. Can you help me?

Info `pip freeze`:

```
cfncluster==1.3.1
boto==2.42.0
awscli==1.10.67
```

Info `aws --version`:

`aws-cli/1.10.67 Python/2.7.6 Linux/3.19.0-32-generic botocore/1.4.57`

File `config`:

```
[global]
cluster_template = default
update_check = true
sanity_check = true

[aws]
aws_region_name = eu-west-1

[cluster default]
key_name = xxxxxx
compute_instance_type = t2.micro
master_instance_type = t2.micro
initial_queue_size = 1
max_queue_size = 10
maintain_initial_size = false
scheduler = sge
custom_ami = xxxxxx
s3_read_write_resource = *
base_os = ubuntu1404
vpc_settings = public
scaling_settings = custom

[vpc public]
vpc_id = xxxxxx
master_subnet_id = xxxxxx
ssh_from = xxxxxx
use_public_ips = true

[scaling custom]
scaling_threshold = 1
scaling_adjustment = 1
scaling_threshold2 = 200
scaling_adjustment2 = 1
scaling_period = 60
scaling_evaluation_periods = 2
scaling_cooldown = 300
```

**Comment by dougalb** [comment]
Could you be more specific about what is missing? CfnCluster uses Chef recipes to install and configure the necessary software such as the schedulers or Ganglia. 

In general we don't advise customers to create a custom AMI but rather install all needed software into the /shared directory and then create an EBS snapshot. You can then easily use this EBS snapshot to launch more clusters with the software already installed. In addition, you can easily take advantage of the CfnCluster updates without having to build a custom AMI each time.

**Comment by apalazzin** [comment]
I've found the problem. 

My company libraries depend by `libhdf5-openmpi-dev` and it's mutually exclusive with `libhdf5-openmpi-dev` ( installed from `liblas-dev` via [cookbook](https://github.com/awslabs/cfncluster-cookbook/blob/master/attributes/default.rb) ).

:dancing_men: 

Thanks for the support.
