### ISSUE TITLE
post_install_args positions have changed

### ISSUE THREAD

**Issue by apalazzin** [awslabs/cfncluster#139]
Hi,

I have followed instructions for mounting EFS public with post_install script (reference #116 ), but I've some problems with executions failed.

I've investigated and I found that post_install_args positions have **changed**.

The debug messages inside post_install_script helped me, the **new** post_install_args positions:

```
$1 --> url of post_install script
$2 --> first argument passed with post_install_args
$3 --> second argument passed with post_install_args
```

Are these changes intentional? @dougalb 

Info `pip freeze`:

```
cfncluster==1.3.1
boto==2.42.0
awscli==1.10.67
```

Info `aws --version`:

`aws-cli/1.10.67 Python/2.7.6 Linux/3.19.0-32-generic botocore/1.4.57`

File `config`:

```
[global]
cluster_template = default
update_check = true
sanity_check = true

[aws]
aws_region_name = eu-west-1

[cluster default]
key_name = xxxxxx
compute_instance_type = t2.micro
master_instance_type = t2.micro
initial_queue_size = 1
max_queue_size = 10
maintain_initial_size = false
scheduler = sge
custom_ami = ami-3ff0824c
s3_read_write_resource = *
base_os = ubuntu1404
vpc_settings = public
scaling_settings = custom
post_install = xxxxxx/post_install.sh
post_install_args = fistArg secondArg

[vpc public]
vpc_id = xxxxxx
master_subnet_id = xxxxxx
ssh_from = xxxxxx
use_public_ips = true

[scaling custom]
scaling_threshold = 1
scaling_adjustment = 1
scaling_threshold2 = 200
scaling_adjustment2 = 1
scaling_period = 60
scaling_evaluation_periods = 2
scaling_cooldown = 300
```

**Comment by dougalb** [comment]
The _post_install_ script has not been changed since it was published.

```
$ aws s3api head-object --bucket cfncluster-global --key scripts/mount-efs.sh
{
    "AcceptRanges": "bytes",
    "ContentType": "application/x-sh",
    "LastModified": "Fri, 01 Jul 2016 09:51:58 GMT",
    "ContentLength": 381,
    "ETag": "\"de2e35f5cf2b2869de1d4213f5f17972\"",
    "Metadata": {}
}
```

What errors did you receive when you used it? The _secondArg_ is only necessary if you wish to specify the mount point, otherwise it defaults to /efs.

**Comment by apalazzin** [comment]
**cfn-init.log**
```
2016-09-29 13:50:00,191 [DEBUG] Running command runpostinstall
2016-09-29 13:50:00,191 [DEBUG] No test for command runpostinstall
2016-09-29 13:50:00,505 [ERROR] Command runpostinstall (/opt/cfncluster/scripts/fetch_and_run -postinstall) failed
2016-09-29 13:50:00,506 [DEBUG] Command runpostinstall output: cfncluster: fetch_and_run - Failed to run boot_as_master postinstall

2016-09-29 13:50:00,506 [ERROR] Error encountered during build of shellRunPostInstall: Command runpostinstall failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 517, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 248, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 113, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command runpostinstall failed
2016-09-29 13:50:00,740 [ERROR] -----------------------BUILD FAILED!------------------------
2016-09-29 13:50:00,742 [ERROR] Unhandled exception during build: Command runpostinstall failed
Traceback (most recent call last):
  File "/usr/local/bin/cfn-init", line 123, in <module>
    worklog.build(detail.metadata, configSets)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 118, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 505, in build
    self.run_config(config, worklog)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 517, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 248, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 113, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command runpostinstall failed
```
The problem isn't the `scripts/mount-efs.sh` but how is passing `post_install_args`:
```
$1 --> https://s3.amazonaws.com/cfncluster-global/scripts/mount-efs.sh
$2 --> first argument passed with post_install_args
$3 --> second argument passed with post_install_args
```
If you try to create a cfnCluster with `scripts/mount-efs.sh`, you can watch CloudFormation error (reference https://github.com/awslabs/cfncluster/issues/116#issuecomment-250050912).

**Comment by dougalb** [comment]
Ah, it looks like it's related to this PR https://github.com/awslabs/cfncluster-cookbook/pull/10. We'll dig into it. The behaviour should not have changed.

**Comment by apalazzin** [comment]
Indeed it has changed (https://github.com/awslabs/cfncluster-cookbook/pull/10/files).

Before was 
`/bin/sh $tmpfile $args`
now is 
`download_run ${cfn_postinstall} ${cfn_postinstall_args}` and `$tmpfile $@`

So the script args are switched at right in the last method calling .

**Comment by xuguorong2016** [comment]
Hi Dougal, 

I got the same error when I created a cfncluster with EFS using the post-install shell script provided by the above.
This is my template of cfncluster,
[aws]
aws_region_name = us-west-2
aws_access_key_id = xxxxxxxxxxxxxx
aws_secret_access_key = xxxxxxxxxxxxxxxxxxxxxxxxxx

[cluster test]
vpc_settings = public
key_name = test_oregon
master_instance_type = m3.large
compute_instance_type = r3.xlarge
initial_queue_size = 0
cluster_type = spot
spot_price = 1.0
ebs_settings = custom
s3_read_resource = arn:aws:s3:::test-bucket
s3_read_write_resource = arn:aws:s3:::test-bucket/*
post_install = s3://cfncluster-global/scripts/mount-efs.sh
post_install_args = fs-xxxxxxxx

[vpc public]
master_subnet_id = subnet-xxxxxxxx
vpc_id = vpc-xxxxxxxx

[global]
update_check = true
sanity_check = true
cluster_template = test

[ebs custom]
volume_size = 20

Do you have any suggestions on this issue? Your response would be really appreciated!
Best,
Michael

![screenshot from 2017-02-04 14-04-36](https://cloud.githubusercontent.com/assets/19210374/22621912/9f29d514-eae3-11e6-8ec4-4b7cfc068553.png)

**Comment by lukeseawalker** [comment]
pre/post-install args position have been clarified in the doc https://github.com/awslabs/cfncluster/commit/666588615d67950216e5944f463d8d0daf921a54
