### ISSUE TITLE
GPU AMI

### ISSUE THREAD

**Issue by cancan101** [awslabs/cfncluster#140]
Pre build AMIs with GPU (Nvidia drivers) support.
I see there are cookbooks for [nvidia](https://github.com/awslabs/cfncluster-cookbook/blob/dccc6c783b44143adda9198976e400c4c27b6771/recipes/_nvidia_install.rb) but I [don't see any of the AMIs indicating they have GPU drivers](https://github.com/awslabs/cfncluster/blob/master/amis.txt).

**Comment by dougalb** [comment]
All AMIs since [cfncluster-1.3.1](https://github.com/awslabs/cfncluster/blob/master/CHANGELOG.rst) have shipped with NVIDIA GPU drivers and CUDA 7.5 installed.
