### ISSUE TITLE
Accessing the cloud formation templates

### ISSUE THREAD

**Issue by kegunder** [awslabs/cfncluster#144]
I'm having issues accessing the latest cloudformation templates (i.e. templateUrl).  I have only days worth of s3 experience, so I'm having a hard time finding the source of the issue.

When I use boto3, I'm able to download and review the template for cfnCluster v1.2.1:

`s3.meta.client.download_file('cfncluster-us-west-2', 'templates/cfncluster-1.2.1.cfn.json' , 'cfncluster2.json')`

However, finding a 1.3.1 (or 1.3.0) version isn't possible do to:
ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

Please explain if this is intended behavior (or point to relevant section in the docs.)  I'm not seeing, or not understanding the details that I see here: http://cfncluster.readthedocs.io/en/latest/configuration.html

Thanks!

**Comment by rvinaybharadwaj** [comment]
Similarly confused regarding the 1.3.2 template within the east-1 region. The default template selection appears to fail: 

`TemplateURL must reference a valid S3 object to which you have access.`

Specifying the [template url ](https://s3.amazonaws.com/cfncluster-us-east-1/templates/cfncluster-1.3.2.cfn.json)directly also fails:

`Config sanity error: https://s3.amazonaws.com/cfncluster-us-east-1/templates/cfncluster-1.3.2.cfn.json 403 Forbidden`

**Comment by bwbarrett** [comment]
@rvinaybharadwaj, i'm afraid it's a bit hard to determine what's going on without more information (like, at least a snippet of your config file).  Were you trying to use the CfnCluster default template in the second test, or a personal version?  I ask because the CfnCluster version is at https://s3.amazonaws.com/cfncluster-resources-us-east-1/templates/cfncluster-1.3.2.cfn.json, not https://s3.amazonaws.com/cfncluster-us-east-1/templates/cfncluster-1.3.2.cfn.json.

**Comment by rvinaybharadwaj** [comment]
We have tried multiple solutions, including specifying the template URL ourselves. For sanity purposes we just generated a configuration with cfncluster config

[aws]
aws_region_name = us-east-1
aws_access_key_id = xxx
aws_secret_access_key = xxxx

[cluster xxxx]
vpc_settings = xxxx
key_name = xxxxx

[vpc xxxx]
master_subnet_id = xxx
vpc_id = xxx

[global]
update_check = true
sanity_check = true
cluster_template = xxxx

And we still receive the same error

We are using the following version of cfncluster:
$ cfncluster version
1.3.2

and we get this error while trying to create cfncluster with the above config
$cfncluster create hello-world
Starting: hello-world
TemplateURL must reference a valid S3 object to which you have access.

Is there a setting that is not being properly set so as to use the correct json file

**Comment by bwbarrett** [comment]
@rvinaybharadwaj, if that's the entire config file (modulo the `xxxx` substitutions, of course), than there's a couple of different policy issues you could be seeing.  The first step is to confirm that the error is coming from the CloudFormation create call, as I suspect.  `~/.cfncluster/cfncluster-cli.log` has a full accounting of the calls made on your behalf to AWS services, along with errors.  It would be useful to see the lines around the error message in that file, but some clean-up will be required, given all the user-identifiable data in the log file.

Just guessing, but the error is likely coming from the call to CloudFormation to create the cluster stack.  CfnCluster doesn't try to download the template directly, but instead passes the template URL to CloudFormation.  It's odd that you're getting errors on our default template, but likely means that your account has an IAM policy limiting access to S3 (which CloudFormation is then enforcing).  If you have CloudTrail enabled, that would likely have the reason for the permissions failure.  But the log file should have more details to get you pointed in the right direction.

**Comment by JeffNing** [comment]
I got the exact same error, too with all the default configuration like aforementioned and here the bottom of the log:

```
08-14 19:46 boto         DEBUG    wrapping ssl socket; CA certificate file=/usr/local/lib/python2.7/dist-packages/boto/cacerts/cacerts.txt
08-14 19:46 boto         DEBUG    validating server certificate: hostname=cloudformation.us-west-1.amazonaws.com, certificate hosts=['cloudformation.us-west-1.amazonaws.com']
08-14 19:46 boto         DEBUG    Response headers: [('x-amzn-requestid', '373b39e1-8129-11e7-9861-bf478eac7685'), ('date', 'Mon, 14 Aug 2017 19:46:07 GMT'), ('content-length', '186'), ('content-type', 'application/json'), ('connection', 'close')]
08-14 19:46 boto         ERROR    400 Bad Request
08-14 19:46 boto         ERROR    {"Error":{"Code":"ValidationError","Message":"TemplateURL must reference a valid S3 object to which you have access.","Type":"Sender"},"RequestId":"373b39e1-8129-11e7-9861-bf478eac7685"}
```

Any help and/or suggestion would be appreciated.

**Comment by jesusmend** [comment]
As @bwbarrett stated, the problem is with IAM permissions on your account. It seems there is something missing in the recommended IAM policies [here](http://cfncluster.readthedocs.io/en/latest/iam.html) When using those policies and role, I get the same error. If I temporarily give the IAM account creating the cluster `AdmistratorAccess`, all works and the error goes away. I'm currently working on finding out what's missing from the listed policies

**Comment by mohanasudhan** [comment]
I am using latest template https://github.com/mohanasudhan/cfncluster/blob/0a4d150a86875ea8565623329dd0e78382f9facf/docs/source/iam.rst for testing. I can create and delete cfncluster 

We also got an fix in this area which is up for next release https://github.com/awslabs/cfncluster/pull/244

Can anyone confirm the problem still exist with latest policy @jesusmend @JeffNing @rvinaybharadwaj @kegunder ?

If no comment for next one week i am planning to close this issue

**Comment by mohanasudhan** [comment]
@jesusmend has updated here https://github.com/mohanasudhan/cfncluster/commit/0a4d150a86875ea8565623329dd0e78382f9facf#comments . Seems we are good with current changes of PR #242 

Closing the issue. @others pls reopen the issue if you still blocked.
