### ISSUE TITLE
ec2_iam_role doesn't seem to work

### ISSUE THREAD

**Issue by sk8bro** [awslabs/cfncluster#151]
I created a role using IAM called "cfnc-user"

part of the policy attached to cfnc-user is this bit: 

        {
            "Sid": "IAMModify",
            "Action": [
                "iam:PassRole"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:iam::176086582871:role/cfnc-user"
        }

then in my ~/cfncluster/config file I do not list credentials except specifying ec2_iam_role = cfnc-user

However, running cfncluster create xyz seems to pull my credentials from ~/.aws/credentials whether I specify an ec2_iam_role or not. For example, changing the credentials in ~/.aws/credentials changes the behavior of cfncluster create. 

I've also tried editing the policy Resource to "*"

Am I doing something wrong here? Thx!

**Comment by mohanasudhan** [comment]
In here you confuse between cluster instance role and cfncluster aws credential for orchestration. 
1. ec2_iam_role --> Existing EC2 IAM Role that will be attached to all instances in the cluster.
2. AWS credential section in cfncluster configuration is required. If not defined, boto will attempt to use a) environment (which is your case) or b) EC2 IAM role.
