### ISSUE TITLE
multiple ssh_from ip addresses?

### ISSUE THREAD

**Issue by sk8bro** [awslabs/cfncluster#152]
Hi, I have 2 ip addresses i would like to allow using the ssh_from option... should that be possible? 

specifying ssh_from = .... twice (2 separate lines) doesn't work

Thanks!

**Comment by f403** [comment]
ssh_from (AccessFrom) must be a valid [CIDR](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing) range. Pattern for it is:
> "AllowedPattern" : "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"

Easiest workaround can be manually updating MasterSecurityGroup in AWS Console after CFN Cluster starts.

If you want an automated solution, take a look into [CFN Template](https://s3.amazonaws.com/eu-central-1-cfncluster/templates/cfncluster-1.3.1.cfn.json), search for "AccessFrom" and "MasterSecurityGroup". And use custom CFN template. 

Be aware of need to merge your custom CFN template when updating CFN Cluster to newer  version.

**Comment by sk8bro** [comment]
Thanks for the suggestion -- 

making a security group specifying the other IP and then using additional_sg option worked!
