### ISSUE TITLE
Canadian central location support

### ISSUE THREAD

**Issue by elainhelen** [awslabs/cfncluster#154]
AWS Canadian region is finally up and running. We would really love to take advantage of cfncluster. 
Thanks

**Comment by kdyb** [comment]
I second that.

**Comment by bwbarrett** [comment]
This will be fixed in CfnCluster 1.3.2.  You can track the patch set at pull request https://github.com/awslabs/cfncluster/pull/188.

**Comment by bwbarrett** [comment]
With today's CfnCluster 1.3.2 release, ca-central-1 is now supported with CfnCluster.  Enjoy!
