### ISSUE TITLE
"Unable to get mapping for AWSInstanceType2Capabilites" error while creating cluster with p2.xlarge instance

### ISSUE THREAD

**Issue by shivakumar121** [awslabs/cfncluster#156]
My attempts at creating a cluster with p2.xlarge instance gives this error "Template error: Unable to get mapping for AWSInstanceType2Capabilites::p2.xlarge::EBSOpt". I tried some other instance types and they work just fine. 
A quick look at the "cfncluster.cfn.json" file shows that the mappings for "AWSInstanceType2Capabilites" is given as "p2.large" in line 1579. Shouldn't this be "p2.xlarge"? I would appreciate suggestions to fix this since I need the p2.xlarge instance to work for my needs. 
I am using cfncluster 1.3.1.

**Comment by shivakumar121** [comment]
So I changed p2.large to p2.xlarge in cfncluster.cfn.json, and used this edited file by specifying template_url = url_of_my_edited_cfncluster.cfn.json in the config file. This seems to have fixed the problem as I can now create clusters with p2.xlarge instances.
The default json might still need to be updated for it to work out of the box.

**Comment by mikerossgithub** [comment]
I am having the same problem. On top of that, I cannot seem to link to a json I have in an s3 bucket, even though it is in the same region (us-west-2) as everything else, can can be accessed easily with a web browser. How did you set up your s3 link?

**Comment by shivakumar121** [comment]
I had to make my json in the S3 bucket downloadable by everyone for it to work. It may not be the best solution, but it worked for me. This can be done in the 'permissions' section of S3 console via a web browser. Hope it helps.

**Comment by bwbarrett** [comment]
Thanks for the bug report.  This will be fixed in CfnCluster 1.3.2.  You can track the patch set at pull request https://github.com/awslabs/cfncluster/pull/188.
