### ISSUE TITLE
p2.xlarge compute instances cannot be started

### ISSUE THREAD

**Issue by mikerossgithub** [awslabs/cfncluster#160]
This is a repeat of a previous issue. It seems there is still the same problem with being unable to start a "p2.xlarge" instance because it is called "p2.large" in cfncluster.cfn.json. I see that a change was made at some point, but it is not in the main branch, and consequently calling cfncluster create does not work. Can the change be propagated to the URL that is looked at by cfncluster create?

**Comment by barrettabel** [comment]
Has anyone found a work around for this? trying to use p2.xlarge instances..

**Comment by mistycheney** [comment]
Commit 68a8b3e0db4f549f813df0eb6a2a4979162d7cf5 only fixes two places. Line 1581 is still not corrected. Fixing that line and follow the method proposed by Issue #516 allows p2.xlarge instance to work.

**Comment by mikerossgithub** [comment]
@barrettabel the workaround is to make your own copy of cfncluster/cloudformation/cfncluster.cfn.json, with the p2 typos fixed, then copy it to a bucket in s3, then refer to that address with the "template_url" variable in cfncluster config.

**Comment by barrettabel** [comment]
Thanks both of you gents, this is what I ended up doing, as well as modifying autoscaling  to look at GPU load ( nvidia-smi etc..) Would be nice to push this all to the master, I have a few scientists using this and just grabbing from pip would be nice..

Cheers


________________________________

**Comment by mikerossgithub** [comment]
@barrettabel -- Neat. Would you mind sharing what you did to modify autoscaling to look at GPU load?

**Comment by bwbarrett** [comment]
This should be fixed in CfnCluster 1.3.2.
