### ISSUE TITLE
cfncluster configuration script crashed on EC2 instance.

### ISSUE THREAD

**Issue by zeeev** [awslabs/cfncluster#165]
Followed the 

Platform: Ubuntu
Image Size: 8GB
Visibility: Public

   17  $ sudo easy_install -U cfncluster
   18  sudo easy_install -U cfncluster
   19  cfncluster configure

```
AWS Region ID []: us-west-1
VPC Name [public]:
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/cfncluster", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python2.7/site-packages/cfncluster/cli.py", line 154, in main
    args.func(args)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/cfncluster/cli.py", line 25, in configure
    easyconfig.configure(args)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/cfncluster/easyconfig.py", line 141, in configure
    key_name = prompt('Key Name', config.get('cluster ' + cluster_template, 'key_name') if config.has_option('cluster ' + cluster_template, 'key_name') else None, options=list_keys(aws_access_key_id, aws_secret_access_key, aws_region_name))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/cfncluster/easyconfig.py", line 76, in list_keys
    keypairs = conn.get_all_key_pairs()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/boto/ec2/connection.py", line 2836, in get_all_key_pairs
    [('item', KeyPair)], verb='POST')
  File "/home/ubuntu/.local/lib/python2.7/site-packages/boto/connection.py", line 1186, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 401 Unauthorized
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to validate the provided access credentials</Message></Error></Errors><RequestID>f43a9c24-c4e9-487f-9b1d-90063d05fb3c</RequestID></Response>

```

**Comment by PaulMcElligott** [comment]
Hello Zeev,

How did you resolve this issue? I am getting the same error.

**Comment by PaulMcElligott** [comment]
I am getting this error also. What did you do to resolve this? Please post.

**Comment by zeeev** [comment]
@PaulMcElligott I never resolved this issue.

**Comment by mahmadza** [comment]
I also have this issue...tried to user starcluster but doesn't work either...

**Comment by bwbarrett** [comment]
The error message is that CfnCluster couldn't authenticate with the credentials provided.  The first prompts from CfnCluster should have been for an AWS Access Key and AWS Secret Key; are you sure you provided the correct ones?  It might be easier (and more secure) to skip hard coding those in the CfnCluster config script and instead follow the [AWS CLI configuration instructions](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html), so that you can ensure you have the correct credentials by first testing with the AWS CLI.  If you take the CLI credentials route, just hit enter when prompted for the Access and Secret Keys by CfnCluster.

**Comment by mahmadza** [comment]
My mistake was to try to develop my own AMI from StarCluster AMI that was on Ubuntu 13.04, which support has been withdrawn. That was my mistake. They have 3 or 4 StarCluster AMI that's still on that version.

I later used another StarCluster AMI that's on Ubuntu 14.04.4 (the only one that's later than 13.04), keyed-in all the correct AWS Access Key and AWS Secret Key and it's all OK!

**Comment by mahmadza** [comment]
Anyways, sorry to talk about starcluster. I also tried CfnCluster on that old AMI Ubuntu 13.04 and it also didn't work (before I realized the version issue).
