### ISSUE TITLE
Cannot create a cluster from a custom based ami

### ISSUE THREAD

**Issue by porsini** [awslabs/cfncluster#168]
Hi 

We are having issues in creating a cluster from a customised ami, based on ubuntu1404.
We attempted two procedures in creating the customised ami.

[cfncluster-cli.log.zip](https://github.com/awslabs/cfncluster/files/779914/cfncluster-cli.log.zip)
[cfncluster-cli.log.zip](https://github.com/awslabs/cfncluster/files/779916/cfncluster-cli.log.zip)
1) Following the official procedure at the link below
http://cfncluster.readthedocs.io/en/latest/ami_customization.html#
starting from ami-3ff0824c (ubuntu1404 on eu-west-1)
Initially we could actually create a cluster from the customised AMI produced as above, but occasionally the cluster creation was failing when creating the master server:
Status: MasterServer - CREATE_IN_PROGRESS
After a certain amount of time the creation was reversed, getting the following message:
"Status: cfncluster-mycluster - ROLLBACK_IN_PROGRESS"

Now this happens all the times, and we can't manage to create a cluster any longer.
See cfncluster log attached.
Config files is as following

[cluster default]
vpc_settings = public
key_name = mykeyname
#below the two private custom amis used the: first created with 1) the second with 2)
#custom_ami = ami-588ed63e 
custom_ami = ami-b683a2d0
master_instance_type = c3.large
compute_instance_type = c3.large
#master_instance_type = c3.8xlarge
#compute_instance_type = c4.8xlarge
initial_queue_size = 0
max_queue_size = 10
scheduler = sge
base_os = ubuntu1404

2) We have created a second customised ami, from an instance started with "cfncluster create", and specifying "base_os = ubuntu1404" only, no custom_ami. The customised image was still generated from the AWS console. But again, when attempting the creation of a new cfncluster based on it, we got the same issue than before.
 
In both cases we can't connect to the instance lunched by cfn_cluster (we have no problem when using "base_os = ubuntu1404" only). Adopting the "--norollback" option, the master instance remain alive, but still we cannot connect to the instance.

Any idea of what we are doing wrong?
out account is: 637405051405

Thanks in advanced for any help

Paolo

**Comment by porsini** [comment]
Hi,
Me again ... in the end I have given up in creating a customised_ami with ubuntu1404.
However I succeeded when using centos7.
Paolo

**Comment by dhrjklt** [comment]
Hi

In my case I want to use a custom AMI based on Redhat. I have created the AMI but every time I assign the AMI ID in config file the "Status: cfncluster-Belle - ROLLBACK_IN_PROGRESS"  occurs. 

How can I use my own private AMI in the cfn cluster as my worker nodes ?

**Comment by bwbarrett** [comment]
@dhrjklt, You'll likely find a useful error message (or at least a hint for the next step of debugging) in the event log for the CloudFormation template for your cluster.  The failure which led to the rollback (ie, cluster build failure) will be recorded there.

**Comment by dhrjklt** [comment]
@bwbarrett 

The below error I found in the log: 

20:56:14 UTC+0550	ROLLBACK_IN_PROGRESS	AWS::CloudFormation::Stack	cfncluster-belle	The following resource(s) failed to create: [MasterServer]. . Rollback requested by user.
Physical ID:arn:aws:cloudformation:ap-south-1:188794524589:stack/cfncluster-belle/d8a2b570-2cee-11e7-bcec-503a56826a82

20:56:13 UTC+0550	CREATE_FAILED	AWS::EC2::Instance	MasterServer	Received FAILURE signal with UniqueId i-02869f9fa9217b7d4
Physical ID:i-02869f9fa9217b7d4

But when I use a default AMI (centos6), the build is successful.

**Comment by bwbarrett** [comment]
@dhrjklt, I can't see your CloudFormation logs, so I can't dig into what happened.  But you now have an instance id (i-02869f9fa9217b7d4) of the master, which failed to perform steps expected in the CloudFormation template.  The next step would be to dig into the history of that instance (why did it shut down, for example).
