### ISSUE TITLE
ami-5af48629 - centos7 - possible bug in file /etc/ssh/sshd_config

### ISSUE THREAD

**Issue by porsini** [awslabs/cfncluster#169]
Hi,

I have used ami-5af48629 (centos7 ami, provided by cfncluster), as base to build a customised ami.
When lunching an instance based on ami-5af48629, either from the AWS console or from CfnCluster, I can connect to it via ssh, I can copy files using scp, but I cannot log in via ftp (e.g. filezilla).
Searching the problem, it seem that there is a issue in /etc/ssh/sshd_config.
In fact, while "sftp-server" is located in /usr/libexec/openssh/, in the /etc/ssh/sshd_config file, I found the following line:
Subsystem sftp /usr/libexec/sftp-server
Replacing this with:
Subsystem sftp /usr/libexec/openssh/sftp-server
The connection via sftp works. However, the header of the /etc/ssh/sshd_config file states:

# This file was generated by Chef for ip-172-31-1-83.eu-west-1.compute.internal
# Do NOT modify this file by hand!

And now I understand why. If I change this by hand, and then I create a custom ami, when I lunch CfnCluster specifying the customised ami that fixes the issue, the fix is reversed. IT seems that that the system files (included /etc/ssh/sshd_config) are overwritten because I include base_os = centos7 in the config file. On the other hand, if I don't include "base_os = centos7", the base system would default to alinux, and I would have problems anyway.

Would it be possible to bring this small fix to the /etc/ssh/sshd_config in ami-5af48629 ? Or upgrade to a version of centos7 that fixes this?
Please don't hesitate to correct/advice something else, if I am missing something.

Thanks a lot for your help

Paolo

**Comment by huffmabc** [comment]
Same issue on amazon linux

**Comment by AStupidBear** [comment]
hope this can be fixed soon
