### ISSUE TITLE
Sanity check on EBS volume attachment

### ISSUE THREAD

**Issue by snorfalorpagus** [awslabs/cfncluster#171]
The application checks to see if an ESB volume exists, but doesn't check if it's available. If the volume is attached to another instance already then the provisioning will fail.

We already have a reference to the `boto.ec2.volume.Volume` object. It should be easy enough to check `AttachmentSet.status`.

**Comment by mohanasudhan** [comment]
PR https://github.com/awslabs/cfncluster/pull/243
