### ISSUE TITLE
Instance type i3 not supported

### ISSUE THREAD

**Issue by andreas-wilm** [awslabs/cfncluster#173]
Hi, the new i3 instance type is not supported as per cloudformation/cfncluster.cfn.json. Andreas

**Comment by btklein** [comment]
Yes, this would be quite nice; any ETA?

**Comment by andreas-wilm** [comment]
Hi,

I added all i3 instance types to cloudformation/cfncluster.cfn.json and uploaded it to a [publicly accessible location](https://s3-ap-southeast-1.amazonaws.com/rpd-public/cfncluster.1.3.1.i3.cfn.json). This was done similar to b81a164c932fef3d5a9ea312ed8d391cfefe414b

When I then select any i3 instance as master and specify the above url with  --template-url I still get: 
> Parameter MasterInstanceType failed to satisfy constraint: Must be a valid EC2 instance type, with support for HVM.

This should work though, right?

Andreas

**Comment by apalazzin** [comment]
Hi @andreas-wilm ,
I've similar problem with others new instances.

I've resolved the problem with add the `template_url` inside `config` file ( documentation http://cfncluster.readthedocs.io/en/latest/configuration.html#template-url ).

**Comment by freecurve** [comment]
Just to pile on - x1.16xlarge also not supported though x1.32xlarge is; I will try your solution apalazzin thank you!

**Comment by kdyb** [comment]
Please support r4 instances

**Comment by bwbarrett** [comment]
This will be fixed in CfnCluster 1.3.2.  You can track the patch set at pull request https://github.com/awslabs/cfncluster/pull/188.

**Comment by bwbarrett** [comment]
I3 instances are now supported with the release of CfnCluster 1.3.2.  Please note that auto-creation of /scratch doesn't work on I3 (see https://github.com/awslabs/cfncluster/issues/195).  This will be fixed in a follow-on release.
