### ISSUE TITLE
Multiple documentation issues & missing IAM permissions

### ISSUE THREAD

**Issue by chrisdag** [awslabs/cfncluster#176]
Creating an issue here but I will also try to improve my git-fu so that I can submit a proper pull request.

The following documentation issues were encountered when I created a fresh IAM user, configured IAM policies for the user and Ec2-IntanceRole and then tried to make an HPC stack using a standalone config file that contained no default entries.

This is what I ran into:

1.  "configuration" page aka configuration.rst has a syntax error in the Tag section. The example provided showing how to add tags has broken syntax. Instead of `tags = {"key": "value", "key2", "value2"}` the proper format is `tags = {"key" : "value", "key2" : "value2"}`

2. "configuration" page has outdated values for the size of volumes used by the master and compute nodes. The doc page says "10" is the default but if you try to launch a cluster with these values you get an error back saying the minimum value for both master and compute root disk is now 15

3. The suggested IAM policy for the CfnCluster user is wildly incorrect and will fail instantly out of the box. There are missing IAM permissions required to launch the stack and MANY missing permissions that enable a clean rollback and delete. This is what I had to add to my user IAM policy in order to get past the create and delete/rollback phases:

`
Add To EC2 Describe:
"ec2:DescribeAvailabilityZones"

Add To EC2Modify:
 “ec2:DeleteNetworkInterface”
 “ec2:DeleteVolume”
 "ec2:TerminateInstances"

Add To SNS Describe:
  “sns:GetTopicAttributes"

Add To SNS Modify:
 “sns:DeleteTopic”

Add To DynamoDBModify:
  “dynamodb:DeleteTable"

Add To SQS Modify:
 “sqs:DeleteQueue”

`

**Comment by chrisdag** [comment]
Update:

Found a new missing IAM permission

You can't "cfncluster delete" a cluster with a live computeFleet unless you also have:

   autoscaling:DeleteLaunchConfiguration

... permission

**Comment by chrisdag** [comment]
More missing IAM permissions required for cfncluster IAM user to delete a cluster:

autoscaling:DescribeScalingActivities
autoscaling:DeleteAutoScalingGroup

**Comment by mohanasudhan** [comment]
Issue 1 & 2 are already fixed. https://github.com/awslabs/cfncluster/pull/242 for iam policy update.
