### ISSUE TITLE
using st1 volume type

### ISSUE THREAD

**Issue by shenkers** [awslabs/cfncluster#179]
I am trying to use the st1 volume type, but I am having trouble launching a cluster.

So far I have tried modyifying the .cfncluster/config, as well as using a custom cfncluster.cfn.json file.  In both cases I got a rollback before cfncluster finishes launching the cluster. Is it possible to change the volume type to st1 with cfncluster? Are there additional properties that need to be set for this to work?

I tried using the properties to set volume type in .cfncluster/config file looks like this:

````
[cluster testcluster]
ebs_settings = testebs
...

[ebs testebs]
volume_type = st1
````

I also tried using a custom JSON file by modifying the VolumeType associated with the ComputeRootVolumeSize.

ie, from:

```
3195             "Ebs" : {
3196               "VolumeSize" : {
3197                 "Ref" : "ComputeRootVolumeSize"
3198               },
3199               "VolumeType" : "gp2"
3200             }
```

to:
```
3195             "Ebs" : {
3196               "VolumeSize" : {
3197                 "Ref" : "ComputeRootVolumeSize"
3198               },
3199               "VolumeType" : "st1"
3200             }
```

**Comment by bwbarrett** [comment]
If you look at the CloudFormation history for the stack, it should tell you what failed (and why).  I was able to create a cluster with a st1 volume, so there shouldn't be any inherent problems.  You don't have a `volume_size` in your example configuration; one potential gotcha with st1 volumes is that the minimum size is quite large (500 GiB, I believe), so you will also need to provide a `volume_size` option to bump up the volume size from the 20 GiB default to something larger.
