### ISSUE TITLE
different post-install script for master/compute

### ISSUE THREAD

**Issue by shenkers** [awslabs/cfncluster#180]
I want to run distinct commands on master/compute node setup. Is there an environmental variable or way to detect whether the startup script is being run on the master or compute node? Is there another pattern you would recommend to run different post_install commands on master/compute?

**Comment by bwbarrett** [comment]
There is not a way to have different post_install scripts.  However, it's pretty easy to tell master and compute nodes apart in a single script:

```
. /etc/cfncluster/cfnconfig 

case ${cfn_node_type} in
MasterServer)
    echo "I am the master"
    ;;
ComputeFleet)
    echo "I am a compute node"
    ;;
esac
```
