### ISSUE TITLE
ganglia doesn't seem to work properly with ubuntu1604 os_type

### ISSUE THREAD

**Issue by timp0** [awslabs/cfncluster#182]
As title says - running a cluster with ubuntu1604 works fine, but the ganglia interface just gives a page of (apparently) php script.  Is there a fix?

**Comment by bwbarrett** [comment]
I think this was the result of some packages not being updated properly in CfnCluster 1.3.1  Can you try updating to 1.3.2 and see if the problem still occurs?  It works for me with 16.04 and CfnCluster 1.3.2.  Thanks!

**Comment by timp0** [comment]
It works better now, but still doesn't seem to actually plot anything in the boxes: 
![image](https://user-images.githubusercontent.com/1441855/27504846-389ed584-5860-11e7-8d32-d18480fbb1a6.png)

**Comment by adavanisanti** [comment]
I see the same problem. Ganglia on ubuntu1604 doesn't plot anything. I am using cfncluster 1.3.2. Is there a fix for this?

Thanks!
