### ISSUE TITLE
Openlava: cannot configure a shared numeric resource

### ISSUE THREAD

**Issue by zalex5** [awslabs/cfncluster#183]
Hi,
I'm trying to configure a shared numeric resource on an openlava cluster (created with cfncluster).

On the master I inserted the resource in /opt/openlava/etc/lsf.cluster.openlava:

> Begin ResourceMap
> RESOURCENAME  LOCATION
> cloudio (5@[all])
> End ResourceMap

... and in /opt/openlava/etc/lsf.shared

> Begin Resource
> RESOURCENAME  TYPE    INTERVAL INCREASING  DESCRIPTION        # Keywords
>    cloudio      Numeric ()        N           (SAN I/O Resource)
>    fs         Boolean ()       ()          (File server)
>    cs         Boolean ()       ()          (Compute server)
>    ms         Boolean ()       ()          (Master server)
> End Resource

After that I stopped openlava on the master (sudo service openlava stop), removed the /opt/openlava/work/lim.events file (in order to clear the cluster) and restarted openlava (sudo service openlava start).

With "bhosts -l" I verified that the master is able to see the new resource. An extract of the output:

>  cloudio
>  Total             5
>  Reserved        0.0
> 

Now the critical part...
I re-added the compute nodes with "lsaddhost -R cloudio hostname".
The nodes are correctly re-added to the cluster but the slots for the new resource are not defined.
This is an extract of the "bhosts -l" output for one of the re-added nodes:

>  cloudio
>  Total             -
>  Reserved          -
> 

I've also tried to restart lim on the compute nodes and to launch a "badmin reconfig" but the result doesn't change.

Can you give me an hint about how to configure this ?
Thank you very much !

**Comment by digout** [comment]
Have you also defined the cloudio resource in the lsf.shared file local to each compute node?
This shall be done in the pre/post install scripts.

-- dop

**Comment by zalex5** [comment]
Yes we tried that with a post install script but it didn't work (the result was the same).
Do you think that we could solve this problem using a pre-install script ?

**Comment by bwbarrett** [comment]
Openlava is removed in CfnCluster 1.3.2 and we have no plans to fix existing issues in Openlava support.  Closing this ticket.
