### ISSUE TITLE
Command to SSH into master node

### ISSUE THREAD

**Issue by snorfalorpagus** [awslabs/cfncluster#184]
Starcluster provides a command to login to the master node, without having to find it's address / path to PEM / username.

http://star.mit.edu/cluster/docs/latest/manual/getting_started.html#logging-into-the-master-node

Can we do the same? Syntax would be something like this:

```
$ cfncluster sshmaster mycluster
```

**Comment by enrico-usai** [comment]
This can be done since [CfnCluster 1.5.2](https://github.com/awslabs/cfncluster/releases/tag/v1.5.2) with `cfncluster ssh <clustername>` command: https://cfncluster.readthedocs.io/en/latest/commands.html#ssh.
