### ISSUE TITLE
Issue #77 to reopen

### ISSUE THREAD

**Issue by freecurve** [awslabs/cfncluster#185]
in publish pending change the line to 
pending=$(qstat -g d -s p -u '*' | tail -n+3 | awk '$5 == "qw" || $5 == "Rq" {total = total+ $8} END {print total}')

so that Rq jobs are counted as pending. 

Thank you!

**Comment by bwbarrett** [comment]
Closing this in favor of just repoening #77, since this issue loses all the history.
