### ISSUE TITLE
Failed to start preprocess NSF configuration

### ISSUE THREAD

**Issue by jreyesucf** [awslabs/cfncluster#189]
Hello, I was running cfncluster just fine, when suddenly I go to create a cluster and the Master Server fails to create. I ran the cfncluster create command with --norollback option to look into the log files of the master node, and found this after running command

systemctl status nfs-config.service

nfs-config.service - Preprocess NFS configuration
   Loaded: loaded (/lib/systemd/system/nfs-config.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2017-06-15 11:10:27 UTC; 11min ago
  Process: 10792 ExecStart=/usr/lib/systemd/scripts/nfs-utils_env.sh (code=exited, status=2)
 Main PID: 10792 (code=exited, status=2)

Jun 15 11:10:27 ip-172-31-20-119 systemd[1]: Starting Preprocess NFS configuration...
Jun 15 11:10:27 ip-172-31-20-119 nfs-utils_env.sh[10792]: /usr/lib/systemd/scripts/nfs-utils_env.sh: 5: /etc/default/nfs-kernel-server: Syntax e
Jun 15 11:10:27 ip-172-31-20-119 systemd[1]: nfs-config.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 15 11:10:27 ip-172-31-20-119 systemd[1]: Failed to start Preprocess NFS configuration.
Jun 15 11:10:27 ip-172-31-20-119 systemd[1]: nfs-config.service: Unit entered failed state.
Jun 15 11:10:27 ip-172-31-20-119 systemd[1]: nfs-config.service: Failed with result 'exit-code'.

My cfncluster/config script is very basic and still has this issue. Here is the configuration:

[aws]
aws_region_name = us-east-1
aws_access_key_id = <my id>
aws_secret_access_key =<my key>

[cluster default]
vpc_settings = public
key_name = test_key

[global]
update_check = true
sanity_check = true
cluster_template = peps

[cluster peps]
vpc_settings = public
key_name = peps_key
base_os = ubuntu1604
master_instance_type = c3.8xlarge
compute_instance_type = c3.8xlarge

[vpc public]
master_subnet_id = subnet-63c14038
vpc_id = vpc-9d8548fb

I have literally no idea what to do about this.

**Comment by jreyesucf** [comment]
After further investigation, it seems that this is partly tied to the use of the base_os ubuntu1604.

Creation of a cluster works just fine with ubuntu1404. Unfortunately I definitely need ubuntu1604

**Comment by mohanasudhan** [comment]
We are looking at the issue. Will update asap.

**Comment by mohanasudhan** [comment]
Let us know if you still have the problem

**Comment by jreyesucf** [comment]
The problem still seems to be persisting as far as using the base os ubuntu1604


Justin Reyes


________________________________

**Comment by mistycheney** [comment]
Using the latest develop version solves the problem for me.

**Comment by jreyesucf** [comment]
So then I just have to upgrade my version of cfncluster?



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by marcofurbo** [comment]
I'm having the exact same problem. How do I update to the develop branch?

**Comment by mistycheney** [comment]
Simply `git checkout develop``

**Comment by jreyesucf** [comment]
I run this inside the cfncluster directory?


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by marcofurbo** [comment]
I would want to update my existing installation from python-pip with version 1.3.2. Is there an easy way to accomplish this?

**Comment by mistycheney** [comment]
If you used pip, you can try `pip install git+https://github.com/awslabs/cfncluster.git@develop`

**Comment by marcofurbo** [comment]
I get this response:

IOError: [Errno 2] No such file or directory: '/tmp/pip-N79d3g-build/setup.py'

I don't think that the develop branch includes the setup.py file.

**Comment by mistycheney** [comment]
I believe I cloned the repo and did `sudo pip install .` in `cli/`

**Comment by marcofurbo** [comment]
That did work for me. Thanks so much for your help!

**Comment by bwbarrett** [comment]
We apologize; this was likely due to a bad configuration push last week while we were preparing for the upcoming 1.3.2 release.  We've rolled back that push and 1.3.1 should work normally again.  If you're still having problems, please re-open this ticket with details about when you launched your cluster.  Thanks!
