### ISSUE TITLE
Two Separate S3 Role Policies for Read/Write

### ISSUE THREAD

**Issue by marcofurbo** [awslabs/cfncluster#192]
Can I have two different s3_read_write_resource lines under one [cluster] section?

I'm hoping to have 

arn:aws:s3:::<BUCKET>/*

and

arn:aws:s3:::<BUCKET>/

**Comment by bwbarrett** [comment]
It's not possible to specify two resources using the `s3_read_write_resource` option.  The `s3_{read,read_write}_resource` options are really pretty simplistic shortcuts.  The more general way to manage S3 access would be to use an IAM role, which will provide all the various policy options you might want.  I recommend following the instructions to create the CfnClusterInstancePolicy in IAM and then specify that in your config: http://cfncluster.readthedocs.org/en/latest/iam.html.
