### ISSUE TITLE
I3/F1 instance store not automatically mounted at /scratch

### ISSUE THREAD

**Issue by bwbarrett** [awslabs/cfncluster#195]
setup-ephemeral-drives.sh in cfncluster-cookbook will create a raid volume across all ephemeral storage and mount it at /scratch.  Due to incorrect device mappings on instance types which use NVMe devices to expose ephemeral store (I3/F1), that script doesn't find any ephemeral devices and therefore doesn't build the mount point.  We need to update the script to work with the NVMe drives, likely by looking for `/dev/disk/by-id/*Instance* ` as the device list.

**Comment by AStupidBear** [comment]
Is there a workaround for this? My work is bottlenecked by I/O therefore I need instance volume urgently.

**Comment by bwbarrett** [comment]
This will be fixed in CfnCluster 1.3.3, but we don't have a public timeline for release.

The instance store drives are all available in the instance, we're just not building the raid drive properly.  https://github.com/bwbarrett/cfncluster-cookbook/blob/master/files/default/setup-ephemeral-drives.sh is the setup script that we use today, which assumes instance metadata is correct (sadly, not the case for I3/F1).  A solution would be to use a script similar to that as a post-install script, which used `/dev/nvme*` instead of IMDS for finding available drives.  Not ideal, obviously, but a short term fix.
