### ISSUE TITLE
make cfncluster/sqswatcher add the number of CPUs in the slurm.conf file

### ISSUE THREAD

**Issue by furybubu** [awslabs/cfncluster#197]
Hi there, 
thanks for maintaining such an essential tool. 
I am using cfncluster in concert with SLURM, and want to configure the scheduler with the selectType=select/cons_res parameter in slurm.conf. This would basically enable the submission of jobs to multiple cores on the same node. One requirement to make it work this way is to define the number of cpus/cores of each node listed in slurm.conf on this line Nodename=...... 
The main problem is that this line is being constantly updated by sqswatcher as the number of nodes requested by cfncluster changes, a behavior mentioned in this comment found in the slurm.conf generated by cfncluster:

#WARNING!!! The Nodename and PartionName entries below
# get updated by the sqswatcher process, be careful
# when manually editing! Default node is there to allow
# submission of jobs to an empty cluster.

How can I make cfncluster update this line with the additional cpu/core info? I tried to edit the file in post, but it seems to somehow break things.

**Comment by marcofurbo** [comment]
Hello,

I am also trying to accomplish something similar. We are using SLURM and we'd like for the jobs to use up all of the vCPUs of each node before scaling or placing jobs on a new node.

How should we go about this?

**Comment by bwbarrett** [comment]
There's not a great way to do this today; CfnCluster's design point was originally more prototype and single user than act as the owner of a production cluster.  Obviously, it's grown from there, but this is one of the places that some of our original design shows through.

I've tagged this as an enhancement requests and it's one that I think is quite reasonable.  We should be able to pass the number of cores / memory / whatever through the SQS message.  It won't make parsing the slurm.conf any easier (sigh), but it seems like something we can support in a future release.

**Comment by kgkeys** [comment]
I just ran into this, as well.  As an ugly hack, I modified: __writeNodeList() in: sqswatcher/plugins/slurm.py.
`if len(node_list[partition]) > 0:
    new_file.write('NodeName=' + ','.join(node_list[partition]) + " " + ' '.join(items[1:]))
else:
    new_file.write("#NodeName= Procs=18 CoresPerSocket=9 Sockets=2 State=UNKNOWN\n")`

Now, SQS watcher writes the correct info to the slurm.conf.  

Obviously, this only applies to the instance type we're using.  Assuming the master and compute are always the same type, you could analyze the configuration of the master and write this to an sqswatcher config file.  Then cause the slurm plugin to read from that file at runtime.

HTH,
Kyle

**Comment by mohanasudhan** [comment]
@furybubu @marcofurbo we load default slurm config from [cookbooks/cfncluster/templates/default/slurm.conf.erb](https://github.com/awslabs/cfncluster-cookbook/blob/develop/templates/default/slurm.conf.erb) and we override NodeName and PartitionName using sqswatcher for adding/removing nodes. In here you want different allocation algorithm (SelectType) than what's provided by default (which is SelectType=select/linear). I would recommend using pre_install script to modify slurm.conf.erb so master_slurm_config receipe use your default values.

**Comment by mohanasudhan** [comment]
Reopen the issue if you feel provided recommendation doesn’t help you. Note as referred in the linked PR cpu/socket/core are updated correctly by slurm daemon today and sinfo reflect the same.
