### ISSUE TITLE
DOC: Getting Started "Repeat Command at the Start"

### ISSUE THREAD

**Issue by j-grana6** [awslabs/cfncluster#199]
At the end of getting_started.rst, the docs say: "Once all of those settings contain valid values, you can launch the cluster by repeating the command that was used at the start." and then give the command:

`$ cfncluster create mycluster`

However, that command is nowhere to be found in the beginning of the doc.  I assume that if you run 'create' without a configuration, it will prompt the user to config.  However, this is not mentioned in the docs.

**Comment by bwbarrett** [comment]
Thanks for the note.  I updated the documentation to be more clear.  I think this was a left over from before `cfncluster configure` was its own command.
