### ISSUE TITLE
post_install timeout

### ISSUE THREAD

**Issue by shenkers** [awslabs/cfncluster#202]
I have a very long running post_install script, and it seems that cfncluster kills the cluster before the script completes. When I run the long running commands as a separate nohup'd process the cluster boots up successfully. Is there a configuration to allow for long-running startup scripts?

Thanks,
Sol

**Comment by bwbarrett** [comment]
The timeout is hard coded (in two places, one for the master server and one for the compute servers) in the CloudFormation template.  You will need to use a custom CloudFormation template to increase the timeout.  The default template is [here](https://github.com/awslabs/cfncluster/blob/develop/cloudformation/cfncluster.cfn.json), and then you'll need to use the `template_url` option, documented [here](http://cfncluster.readthedocs.io/en/latest/configuration.html#template-url).

If you have any other questions, reopen this issue or open a new issue.

Good luck,

Brian

**Comment by shenkers** [comment]
Thanks Brian, that clarifies it! Just to put more of the details in this thread, the section of the default template that needs to be edited will look something like this:

```
"CreationPolicy" : {
        "ResourceSignal" : {
          "Timeout" : "PT30M",
          "Count" : {
            "Ref" : "ComputeWaitConditionCount"
          }
        }
      }
```

Where the "PT30M" above means it will wait 30M before timing-out

http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-autoscalingupdatepolicyrollingupdate``
