### ISSUE TITLE
optional arguments --config and --region shows unrecofnized

### ISSUE THREAD

**Issue by elainhelen** [awslabs/cfncluster#203]
I used cfncluster to bootstrap a cluster in each AWS region.
In order to manage them, I created a config file for each region. 
Then I tried to use optional arguments --config and --region to manage those clusters.
But it showed the following error.
`$ cfncluster create cfnclusteruswest2 --config config-cfnclusteruswest2 --region us-west-2
usage: cfncluster [-h] [--config CONFIG_FILE] [--region REGION] [--nowait]
                  {create,update,delete,start,stop,status,list,instances,configure,version}
                  ...
cfncluster: error: unrecognized arguments: --config config-cfnclusteruswest2 --region us-west-2`

**Comment by mohanasudhan** [comment]
use config parameter before create command
 
cfncluster --config config-cfnclusteruswest2 --region us-west-2 create cfnclusteruswest2
