### ISSUE TITLE
How do I use the --tags option with CFNCluster?

### ISSUE THREAD

**Issue by mohanasudhan** [awslabs/cfncluster#204]
Copied from customer issue 

Use-case: I had a customer case where the customer tried to add tags to their CfnCluster. The customer and myself attempted to use the --tags parameter like so ($ cfncluster create mycluster --tags Key=string,Value=string). Unfortunately this and many of the other examples on how to add tags in our public documentation result in returning an error. 

Solution: To correctly use the --tags parameter you will need to input a specially formatted JSON list encapsulated by single quotes: '{"Keystr":"Valuestr"}' 

Issue: There are no mentions of the usage of --tags parameter in the CfnCluster documentation. In the CfnCluster CLI there is only proof that --tags/-g is a parameter. To my knowledge there is no public information on the usage of --tags. I had to examine the source code of the CfnCluster tool and bruteforce different JSON formats for the tool to accept my list. Overall I can see how this would be a negative experience for a customer, as I experienced this myself. 

Proposed Action(s): In the public documentation note the usage of --tags and give an example. Possibly expand this to the other parameters like --extra-parameters and --norollback. 

Please let me know if you have any additional questions. Thanks!

**Comment by bwbarrett** [comment]
@mohanasudhan, we can push doc updates without doing a release, so this doesn't have to wait for 1.3.3....

**Comment by mohanasudhan** [comment]
fix https://github.com/awslabs/cfncluster/pull/205

**Comment by mohanasudhan** [comment]
Merged the fix. closing
