### ISSUE TITLE
Feature Request - Output/dry run option

### ISSUE THREAD

**Issue by shadycuz** [awslabs/cfncluster#219]
I have a need to use the cloudformation stack from cfncluster with other tools. It would be nice if we could have cfncluster output the cloudformation yaml with out actually deploying it.

**Comment by mohanasudhan** [comment]
Thanks for your request. 

We like to think a bit about this feature request. As we see dry run is important feature for development, we don't want to mislead the term dry run here as the underlying infrastructure like cloudformation does only validate template (which doesn't guarantees provided yaml/json will work perfect without error). We can add the feature of "generate-template" here but this exposes our internal implementation and its hard to move forward. I will keep this open for couple of days to see interest on this feature.

**Comment by mohanasudhan** [comment]
I got misleaded here. cfn template is static refer <http://cfncluster.readthedocs.io/en/latest/configuration.html#template-url> you can use aws cli or sdk to download it from s3.

**Comment by shadycuz** [comment]
@mohanasudhan This wont work. I don't want to create the cluster first, I want to view the template before launching so it can be modified. Can you reopen this?

**Comment by shadycuz** [comment]
And trying to get the template https://s3.amazonaws.com/cfncluster-us-east-1/templates/cfncluster-1.3.2.cfn.json does not work for me. Also I want the Cloudformation template cfncluster is sending to AWS using my config file, not the stock one you guys base stuff on...

**Comment by bwbarrett** [comment]
@shadycuz, I think you're misunderstanding how CfnCluster uses the template.  We don't actually build a new CloudFormation template for each configuration.  Instead, it calls CloudFormation using the template associated with the version of CfnCluster in use and a set of parameters.  The CloudFormation template is always the same (unless the user provides a different one), only the templates (and stack name, obviously) are different from cluster to cluster.

The template for CfnCluster 1.3.2 is here: https://github.com/awslabs/cfncluster/blob/v1.3.2/cloudformation/cfncluster.cfn.json.  The call to CloudFormation to create the stack is here: https://github.com/awslabs/cfncluster/blob/88c940f38c1ae7be1c45d374802be430bb13d3e7/cli/cfncluster/cfncluster.py#L67-L69.

**Comment by shadycuz** [comment]
Now things make sense =), I can now build a proper devops pipeline for testing new releases, thanks @bwbarrett
