### ISSUE TITLE
Can cfncluster mount the existing ebs volumes?

### ISSUE THREAD

**Issue by michaelxu2014** [awslabs/cfncluster#22]
Can I automatically mount the existing ebs volumes to a cluster if I have already created some ebs volumes? For example, can I specify the volume IDs in the configuration file before create/start a cluster?

Thanks,
Michael

**Comment by michaelxu2014** [comment]
I tried to use a snapshot but looks like it did not work. The below is my EBS settings,

## EBS Settings
#[ebs custom]
# Id of EBS snapshot if using snapshot as source for volume
# (defaults to NONE for default template)
ebs_snapshot_id = snap-507e03de
# Type of volume to create either new or from snapshot
# (defaults to gp2 for default template)
volume_type = gp2
# Size of volume to be created if not using a snapshot
# (defaults to 20GB for default template)
volume_size = 50
# Number of IOPS for io1 type volumes
#volume_iops = 200
# Use encrypted volume (should not be used with snapshots)
# (defaults to false for default template)
#encrypted = false

Please let me know if it is not correct. Thanks!

Michael

**Comment by dougalb** [comment]
Within the cluster section, you need to make sure you are explicitly calling out an ebs settings section. So for example, you should have something like this:

[cluster default]
key_name = my key
ebs_settings = mysnapshot
vpc_settings = public

[vpc public]
vpc_id = vpc-a1b2c3d4
master_subnet_id = subnet-a1b2c3d4

[ebs mysnapshot]
ebs_snapshot_id = snap-a1b1c1d4
volume_type = gp2

You do not need any volume_size as that will come from the EBS snapshot.

**Comment by michaelxu2014** [comment]
It works now, thanks a lot!
