### ISSUE TITLE
/etc/apt/aot.conf typo?

### ISSUE THREAD

**Issue by chambm** [awslabs/cfncluster#221]
I was diffing the 1.2.1 template with 1.3.1 and discovered what I suppose is a typo in the proxy support. I don't use proxies, but the redirection to `/etc/apt/aot.conf` in 
cfncluster.cfn.yaml
cfncluster.cfn.json
is suspect. I almost submitted a PR but figured it's better to check whether it's intentional first.

**Comment by mohanasudhan** [comment]
Change is introduced in this PR https://github.com/awslabs/cfncluster/commit/dedb449fbfcdbe18661a2e7d18650c3ab199da49#diff-3a692397159661f29792dbe4f41f12e9 

Seems it's typo to me '/etc/apt/aot.conf' -> '/etc/apt/apt.conf'

**Comment by mohanasudhan** [comment]
Fix: https://github.com/awslabs/cfncluster/pull/241
