### ISSUE TITLE
SFTP connection error

### ISSUE THREAD

**Issue by ppau1** [awslabs/cfncluster#222]
## Brief summary

I would like to connect to my recently created cluster with an SFTP manager (like Cyberduck) but I cannot establish a connection.

## Details

I recently created a cluster with cfncluster and I am able to connect to it with ssh with my Public Key and as user "centos".  But when I try to connect through SFTP with a program such as Transmit I get a connection error `Could not connect to server “ec2-34-209-169-253.us-west-2.compute.amazonaws.com”. Command Failed.`

Similarly, with Cyberduck I get `Interoperability failure. EOF while reading packet. Please contact your web hosting service provider for assistance.`

I can SFTP using these programs to other servers that have not been created with cfncluster.

**Comment by mohanasudhan** [comment]
similar issue is report before #169 .

**Comment by mohanasudhan** [comment]
Refer #169
