### ISSUE TITLE
Creating cloudformation template with some fixed parameters

### ISSUE THREAD

**Issue by adavanisanti** [awslabs/cfncluster#223]
I would like to build a cloud formation template that can create a cluster similar to cfncluster but with some fixed parameters. I have tried modifying the [template](https://github.com/awslabs/cfncluster/blob/develop/cloudformation/cfncluster.cfn.json) with some parameters (centos6 OS, slurm, and a custom-ami). I would like to use this template for AWS marketplace. I am using centos6 due to the issue discussed [here](https://github.com/awslabs/cfncluster/issues/209). 

Cluster creation fails at Master Server creation. Apparently, one of the errors is at 
+ cfn-init -s cluster-fixed-params-1 -v -c default -r MasterServer --region us-west-2

/usr/lib/python2.6/site-packages/cfnbootstrap/packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail.

Updating to Python 2.7 may help resolve the above problem. But, centos6 yum depends on Python 2.6.6 and may break other things.

Could you help me with building a cloudformation template that can create a cluster similar to cfncluster but with some fixed parameters?

Let me know if you need more information.

Thanks
Santi

**Comment by mohanasudhan** [comment]
Refer: https://stackoverflow.com/questions/29134512/insecureplatformwarning-a-true-sslcontext-object-is-not-available-this-prevent

**Comment by mohanasudhan** [comment]
Re-open if you still have any issue. closing

**Comment by adavanisanti** [comment]
@mohanasudhan I have tried installing all the libraries and cloud formation failed at master server creation.

I have tried using the template (https://github.com/awslabs/cfncluster/blob/develop/cloudformation/cfncluster.cfn.json) 
directly on cloud formation with ubuntu1604 and ran into same problem. Everything works fine with cfncluster cli. Could you help with creating a cloudformation template that I can directly use with AWS cloudformation?
