### ISSUE TITLE
Can post_install script be a local script?

### ISSUE THREAD

**Issue by adavanisanti** [awslabs/cfncluster#226]
I have a script that I need to run after boot. This script is part of the AMI. According to the documentation, this has to be a URL post_install script. Can this be a local script, say /usr/local/scripts/example.sh?

Thanks
Santi

**Comment by bwbarrett** [comment]
The post_install script needs to be a URL that works with wget.  In theory, `file:///usr/local/scripts/example.sh` syntax should work, although there's a couple of gotchas.  First, the script needs to exist both in the AMI and in the same location on the host from which you run cfncluster, as the command line validates the URL.  Second, there's very little debugging output when something goes wrong, so it's definitely a trial and error debugging.  I'm not sure I'd recommend such a strategy, but it should work.

I have to ask; if you're baking your own AMI, why not just add the /etc/init.d/ hook and avoid the post-install hook?

**Comment by adavanisanti** [comment]
@bwbarrett Yes, realized that I can add to /etc/init.d/ after some StackOverflow digging. Will try that. 

Thanks!

**Comment by jackyenbioinfo** [comment]
hello, would you explain a little bit more how you did it to put the script under /etc/init.d/ ? I'm attempting to do the same thing you did...thanks

**Comment by adavanisanti** [comment]
@jackyenbioinfo I don't remember the exact case as I am not using a post install script anymore. But the idea was to create 1) custom AMI using one of the cfncluster template AMIs, 2) Within that AMI create a script under `/etc/init.d/<custom_script>`, 3) Use that script in`post_install` option using `file:///etc/init.d/<custom_script`.

**Comment by jackyenbioinfo** [comment]
thanks! so under the post_install in the config file do "file:///etc/init.d/my_script" correct? Could I put it under the home directory like "/home/ubuntu/myscript" and just specify in my config file? thanks

**Comment by adavanisanti** [comment]
@jackyenbioinfo I think @bwbarrett suggestion was to use `/etc/init.d` script to run something at boot **instead of** using `post_install` script. My suggestion above is incorrect! You can use another script in `$HOME` in `post_install` and technically it should work.
