### ISSUE TITLE
Using nfs4 to mount /shared

### ISSUE THREAD

**Issue by adavanisanti** [awslabs/cfncluster#230]
I would like to test network speed using nfs4 instead of nfs3. I guess this will need some changes to chef recipes. Could you help make this change?

```
ubuntu@ip-172-31-22-8:~$ mount -v | grep shared
ip-172-31-21-135.us-west-2.compute.internal:/shared on /shared type nfs (rw,noatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=172.31.21.135,mountvers=3,mountport=32767,mountproto=udp,local_lock=none,addr=172.31.21.135,_netdev)
```

**Comment by mohanasudhan** [comment]
installed nfs chef support nfs4 as well but we using vers3 https://github.com/awslabs/cfncluster-cookbook/blob/develop/recipes/_compute_base_config.rb#L41

you can mount using nfs4

mount -t nfs4 -o nfsvers=4.1 <device> <dir>
