### ISSUE TITLE
Possible quote issue? 

### ISSUE THREAD

**Issue by shadycuz** [awslabs/cfncluster#231]
https://github.com/awslabs/cfncluster/blob/88c940f38c1ae7be1c45d374802be430bb13d3e7/cloudformation/cfncluster.cfn.json#L2652-L2663

I'm trying to add addittional commands to the `runcmd:` list. I'm trying to automount EFS, but even simple commands like mkdir are not working. Looked in my user data and it looks like this. 

```
 - [ sh, "which apt-get && echo Acquire::http::Proxy "NONE"; >> /etc/apt/aot.conf" ]
```

it looks to me like the quotes around "NONE" would cause an issue. I'm not sure what the fix is, you first have to escape the yaml template, and then the bash. I run alpine linux sooo?

**Comment by shadycuz** [comment]
When I took out the second runcmd (the apt one) I got this in the log 
```
sh: which yum && echo NONE >> /etc/yum.conf: No such file or directory
```

but my EFS mounted =)

**Comment by jocherry** [comment]
I am afraid I don't understand this, are you saying the JSON is malformed?
Or the edits your performing are having unexpected results?

It will likely be easier to run a post install script (http://cfncluster.readthedocs.io/en/latest/pre_post_install.html)
as opposed to editing the cloudformation template directly.
(I have personally found it takes a lot of trial and error to cloudformation templates correct)

**Comment by mohanasudhan** [comment]
I am not clear about your EFS automount here. Dougal created a script for mount EFS refer https://github.com/awslabs/cfncluster/issues/116 

Can't help here as we are not clear on the problem. Please reopen this issue if it still blocking you also say what are you planning to achieve here
