### ISSUE TITLE
Questions: SharedDir on Master but not on compute fleet?

### ISSUE THREAD

**Issue by shadycuz** [awslabs/cfncluster#232]
What can I edit in the cfn-init of the compute fleet to have it skip mounting the shared directory from master via NFS?

**Comment by jocherry** [comment]
You do not wish to have the shared file system mounted on the compute fleet?
Or you are using a different shared file system?

NFS is mounted during the AMI build, so you cannot change a script in cfn-init to not mount it.

If you really don't want NFS, you can build a custom ami without it: 
http://cfncluster.readthedocs.io/en/latest/ami_customization.html?highlight=custom_ami
