### ISSUE TITLE
Question: Post install script only on master node

### ISSUE THREAD

**Issue by adavanisanti** [awslabs/cfncluster#235]
Is there a way to run a post install script only on the master node? 

Thanks
Santi

**Comment by dougalb** [comment]
https://www.google.com/search?q=cfncluster+master+post-install&oq=cfncluster+master+post-install&aqs=chrome..69i57j69i64l2.7065j0j7&sourceid=chrome&ie=UTF-8

https://github.com/awslabs/cfncluster/issues/180

**Comment by adavanisanti** [comment]
Thanks, @dougalb. Came across #180 just after submitting the question :).
