### ISSUE TITLE
Question: Change node AMI while master is up

### ISSUE THREAD

**Issue by ctaperts** [awslabs/cfncluster#246]
Is it possible to change the node AMI for the cluster while the master is up?

Thanks

**Comment by mohanasudhan** [comment]
Before answering your question. Can we understand what are you trying to achieve here?

**Comment by ctaperts** [comment]
I am trying to preserve the master while changing the nodes AMI for the sge cluster

**Comment by mohanasudhan** [comment]
It's possible to create cluster with [custom_ami](http://cfncluster.readthedocs.io/en/latest/configuration.html#custom-ami). As per current design we use same ami for mater and compute node. You can't change compute node AMI while master instance is running.

I am not  sure what you want to change in compute node of sge cluster. Have you looked at [post_install](http://cfncluster.readthedocs.io/en/latest/configuration.html#post-install) and [pre_install](http://cfncluster.readthedocs.io/en/latest/configuration.html#pre-install) script. you can have customized script to run only on compute node based on instance tags.

**Comment by ctaperts** [comment]
We have a service that needs to be updated and each update takes a considerable amount of time, if it were possible to swap out the AMI used instead would be a bit less work. I appreciate your time

**Comment by ctaperts** [comment]
We have a service that needs to be updated and each update takes a considerable amount of time, if it were possible to swap out the AMI used instead would be a bit less work. I appreciate your time

Also we would like the master IP address not to change between updates

**Comment by mohanasudhan** [comment]
Have you looked at [Code Deploy](https://aws.amazon.com/codedeploy/) In-place deployment? Again I don't know what your service does, so please validate before take my word on it. 

Master instance has elastic ip address and we are not changing it in cluster life cycle.

**Comment by ctaperts** [comment]
Sorry I should've been more accurate, the private IP address. I'll take a look at Code Deploy thanks!

**Comment by mohanasudhan** [comment]
when you stop and start cfncluster, we do stop of master instance today (will might change this behavior), which will change public ip address associated to the master but not the private ip (also note eip is not affected here).

**Comment by ctaperts** [comment]
awesome, thanks a lot
