### ISSUE TITLE
cannot stop cluster

### ISSUE THREAD

**Issue by michaelxu2014** [awslabs/cfncluster#25]
When I tried to run the command "cfncluster stop mycluster", I could not stop cluster and no response at all. Any thoughts?

Thanks,
Michael

**Comment by michaelxu2014** [comment]
Hi Dougal,

I created another 10 nodes SGE cluster with cfncluster and I still have trouble with stoping it. Do you have any log to check what's going on? Any suggestions on this issue please let me know?

Thanks,
Michael

**Comment by delagoya** [comment]
As a last resort, you should be able to go into CloudFormation web console
and delete the stack. You can also get better error reporting from the
console on which specific step failed and why.

**Comment by dougalb** [comment]
The "cfncluster stop" was added as a placeholder but not fully implemented. There has been very little demand as the compute instances automatically terminate when idle and can scale up again when required. If you wish to stop a cluster, you can simply stop the MasterServer using the console and then start again when required.

What is the scenario that you, where you want to stop a cluster?

**Comment by michaelxu2014** [comment]
OK, cool! For my case, I want to turn off the cluster but not terminate them if I finish my jobs. That could save my time to configure the cluster. But I will try to stop the MasterServer on the console, thanks a lot!

Michael

**Comment by delagoya** [comment]
I'ld actually vote for a +1 on this feature request. I regularly stopped clusters while I was acquiring data, sometimes for a week or two.

**Comment by michaelxu2014** [comment]
Hi Angel,

Thanks you for your response! CloudFormation can provide some information to track the status of my cluster, but it is not that clear to understand the real cause. It just tell me it is failed to create master server, but I don't understand why.

Thanks,
Michael
