### ISSUE TITLE
Currently failing Kitchen tests

### ISSUE THREAD

**Issue by jocherry** [awslabs/cfncluster#250]
Currently around 40% of kitchen tests are failing in the pipeline.
All of these need to be green before releasing new version.

Will update with specific platforms and versions  failure to track progress.

**Comment by rajachan** [comment]
I'm seeing two themes of failures. The `*centos-70` kitchen instances are failing to find R packages in the yum repositories. We seem to include the `yum-epel` receipe only for OS versions < 7, so it might be related to how the R packages are maintained between the different upstream repos. 

The `*centos-66` failures seem to be related to the NFS recipe when it tries to start the nfsd server. Will try it manually and see what's happening.

**Comment by mohanasudhan** [comment]
Kitchen: default-gpu-amazon-linux-latest
Failure: " Can't load libEGL from libEGL.so.1: libEGL.so.1"
Logs:
nvidia-installer command line:
    ./nvidia-installer
    --silent
    --no-network
    --dkms

Using built-in stream user interface
-> Detected 8 CPUs online; setting concurrency level to 8.
-> License accepted by command line option.
-> Installing NVIDIA driver version 375.66.
-> Would you like to register the kernel module sources with DKMS? This will allow DKMS to automatically build a new module, if you install a different kernel later. (Answer: Yes)
WARNING: nvidia-installer was forced to guess the X library path '/usr/lib64' and X module path '/usr/lib64/xorg/modules'; these paths were not queryable from the system.  If X fails to find the NVIDIA X driver module, please install the `pkg-config` utility and the X.Org SDK/development package for your distribution and reinstall the driver.
-> Installing both new and classic TLS OpenGL libraries.
-> Installing classic TLS 32bit OpenGL libraries.
-> Install NVIDIA's 32-bit compatibility libraries? (Answer: Yes)
-> Will install GLVND GLX client libraries.
-> Will install GLVND EGL client libraries.
-> Skipping GLX non-GLVND file: "libGL.so.375.66"
-> Skipping GLX non-GLVND file: "libGL.so.1"
-> Skipping GLX non-GLVND file: "libGL.so"
-> Skipping EGL non-GLVND file: "libEGL.so.375.66"
-> Skipping EGL non-GLVND file: "libEGL.so"
-> Skipping EGL non-GLVND file: "libEGL.so.1"
-> Skipping GLX non-GLVND file: "./32/libGL.so.375.66"
-> Skipping GLX non-GLVND file: "libGL.so.1"
-> Skipping GLX non-GLVND file: "libGL.so"
-> Skipping EGL non-GLVND file: "./32/libEGL.so.375.66"
-> Skipping EGL non-GLVND file: "libEGL.so"
-> Skipping EGL non-GLVND file: "libEGL.so.1"
Looking for install checker script at ./libglvnd_install_checker/check-libglvnd-install.sh
   executing: '/bin/sh ./libglvnd_install_checker/check-libglvnd-install.sh'...
   Checking for libglvnd installation.
   Checking libGLdispatch...
   Checking libGLdispatch dispatch table
   Checking call through libGLdispatch
   All OK
   libGLdispatch is OK
   Checking for libGLX
   libGLX is OK
   Checking for libEGL
   Can't load libEGL from libEGL.so.1: libEGL.so.1: cannot open shared object file: No such file or directory
-> An incomplete installation of libglvnd was found. Do you want to install a full copy of libglvnd? This will overwrite any existing libglvnd libraries. (Answer: Abort installation.)

**Comment by mohanasudhan** [comment]
w00t !! kitchens are all green :) closing this issue
