### ISSUE TITLE
Merge kitchen.cloud.yml and kitchen.yml file

### ISSUE THREAD

**Issue by mohanasudhan** [awslabs/cfncluster#254]
We currently have two file for kitchen build in cfncluster-cookbook, which is bit confusing when we are trying to modify things in kitchen. See if we can merge those two files to one. 

https://github.com/awslabs/cfncluster-cookbook/blob/develop/.kitchen.cloud.yml
https://github.com/awslabs/cfncluster-cookbook/blob/develop/.kitchen.yml

**Comment by dougalb** [comment]
This is considered a "good" practice, so that you do not default to using
cloud resources when using Kitchen.

**Comment by mohanasudhan** [comment]
Thanks @dougalb for the rationale behind having two file. Now it make sense.

**Comment by rajachan** [comment]
For the sake of our CI testing, it might be worthwhile to drop all the vagrant stuff and just use Docker with the `kitchen-docker` driver for the local yaml. I tested this a while back and things seem to go fine for the most part, except some hiccups around certain recipes. I'll poke at that some more after the release.

**Comment by mohanasudhan** [comment]
Sounds good, can you add separate issue for it, so we don't lose track of it. Thx
