### ISSUE TITLE
Use docker driver instead of vagrant for local kitchen tests

### ISSUE THREAD

**Issue by rajachan** [awslabs/cfncluster#255]
The cfncluster-cookbook's PR CI testing runs into issues with incompatible vagrant versions when using the local kitchen config. We should look at using the `kitchen-docker` driver instead which is minimal and works much better, and is easier to test locally on our laptops.

It should be straight forward to make this change:

```
--- a/.kitchen.yml
+++ b/.kitchen.yml
@@ -1,6 +1,6 @@
 ---
 driver:
-  name: vagrant
+  name: docker
```

```
--- a/Gemfile
+++ b/Gemfile
@@ -10,6 +10,7 @@ end

 group :test do
   gem 'chefspec', '~> 4.0'
+  gem 'kitchen-docker'
```

That said, it needs some effort to make sure our entire cookbook is happy with it.

**Comment by bwbarrett** [comment]
Why?  I'd much rather we just always use the cloud test setup...

**Comment by rajachan** [comment]
Closing this out based on our offline discussion from a while ago. Neither vagrant nor docker would mimic actual customer usage with our AMIs, so this enhancement is moot.
