### ISSUE TITLE
SGE cluster crash issue

### ISSUE THREAD

**Issue by michaelxu2014** [awslabs/cfncluster#26]
Hi Dougal,

Recently, I created an SGE cluster with 20 nodes (cc2.8xlarge) to process our jobs with 30+ dataset. For each dataset, I need to submit 5,000+ jobs to the SGE cluster. When SGE finishes one dataset, then I submit another dataset (5,000+ jobs) to the queue. However, the cluster was crashed when cluster processed every 5 dataset. The below is the error message,

Unable to run job: failed receiving gdi request response for mid=1 (got syncron message receive timeout error).

When I log in the master node, I cannot get any response when I type the command "qhsot" and "qstat". And I can not also submit any jobs to the queue. Do you have any suggestions?

Thanks,
Michael

**Comment by dougalb** [comment]
What is the value of the master_instance_type in the cfncluster config? It sounds like the SGE master died, possibly under load.

**Comment by michaelxu2014** [comment]
No, the master node is still alive. The instance type of master is c3.large.

**Comment by dougalb** [comment]
How much IO is being done against the /shared EBS volume during the runs? What does Ganglia show during the runs? It sounds like an SGE load issue.

**Comment by michaelxu2014** [comment]
where can I find the information you mentioned?

**Comment by dougalb** [comment]
IO can be measured using iostat on the MasterServer or looking at CloudWatch metrics for EBS. Ganglia is available over the web via the http://<master ip>/gangalia URL.

Is all the data being read/written from /shared during the 5000 runs? How long are jobs typically running?

**Comment by michaelxu2014** [comment]
All data is being read from /shared, but is being written out to S3 during the 5000 runs. Each small job takes about 30 mins. Each dataset takes 5 hours on a cluster with 20 cc2.8xlarge nodes. 
When the case happened, I checked that all nodes looks like healthy. OK, I will check the CloudWatch and Ganlia if that happens again.

**Comment by dougalb** [comment]
How big is the /shared partition? How much data is being read in by each job? The c3.large is a 2 vCPU instance with no EBS optimization. Have you tried using a larger MasterServer? Something like an m3.2xlarge?

**Comment by michaelxu2014** [comment]
100GB for the /shared partition. The data is up to 40MB for each job. No, I did not try a larger Master server. I will try a large instance type in future.

**Comment by dougalb** [comment]
Okay, I think that might be the issue. 5000 * 40MB == ~200GB. Are some jobs reading the same inout data?

**Comment by michaelxu2014** [comment]
Actually, 5000 jobs read 100 files (40MB) during the runs.

**Comment by dougalb** [comment]
Each one of the 5000 jobs reads 100 x 40MB, so each job reads in 4GB?

**Comment by michaelxu2014** [comment]
Sorry, actually I only have 100 files (each file is 40MB) for 5000 jobs read in. Each job takes 2 files out of the 100 files.

**Comment by michaelxu2014** [comment]
Hi Dougal,

Unfortunately, the issue happened again this morning and I did not turn on the port 80. So I cannot access the ganglia. I can login the master server and cannot get any response by typing "qhost" and "qstat" commands. Howerver, I can get the response by "qhost" and "qstat" when I manually terminated some nodes. For this cluster, I still used c3.large instance as the master server because the cluster was running when I talked to you. I will use larger master server next time.

Thanks,
Michael

**Comment by dougalb** [comment]
Closing, based on email discussions.

**Comment by cchng** [comment]
Hi @dougalb, what was the resolution for this issue? I have a similar set up with read/writes to an io1 volume. I've increased the IOPS and master node size, but still seeing "failed receiving gdi request response for mid=65535" on a python drmaa pipeline run on the master node.

qmaster/messages
```
01/06/2020 21:50:22|event_|ip-xx-xx|W|acknowledge timeout after 600 seconds for event client (drmaa:574) on host "ip-xx-xx.us-west-2.compute.internal"
01/06/2020 21:50:22|event_|ip-xx-xx|E|removing event client (drmaa:574) on host "ip-xx-xx.us-west-2.compute.internal" after acknowledge timeout from event client list
```
Can I manually increase SCHEDULER_TIMEOUT on SGE?

**Comment by enrico-usai** [comment]
Hi @cchng 

thank you for reporting your question.
As a general suggestion, it is better to open a new issue (eventually referencing similar ones) rather than answer to a closed one (especially in case like this, on which the original issue is almost 5 years old) ;)

Did you try [EFS](https://docs.aws.amazon.com/parallelcluster/latest/ug/efs-section.html) or the [Storage Optimized](https://aws.amazon.com/ec2/instance-types/#Storage_Optimized) instance types?

Please feel free to open a new ticket if you have questions or information to share.
Thank you
