### ISSUE TITLE
Only one compute node takes waiting jobs from the queue and other nodes are idle

### ISSUE THREAD

**Issue by guorongxu** [awslabs/cfncluster#275]
Hello,

I have repeatedly experienced this issue on cfncluster. I created a cluster with 15 r3.8x instances. I saw only one node is running my job and other 9 nodes are idle. But this cluster worked well at the beginning and then the issue happened during the middle of the processing. When I created a new cluster I found the cfncluster released a new version. So I am wondering if every time the new release would affect the old clusters because they updated all AMIs to the latest patch levels. When the cluster was trying to add new nodes into the cluster but could not attached them to the head node because the AMIs are changed. Please take a look at my account 318643255700 and the case id is: 4166805131. 

For saving the spend, I changed the number of compute node from 10 to 1 and kept the cluster running for your trouble shooting.

Thanks a lot for your help!

**Comment by rajachan** [comment]
@guorongxu, a given auto scaling group's launch configuration should not be impacted by updates to the CfnCluster version. A running cluster will always use the AMIs that are appropriate for the version it was originally launched with. Can you send us the logs from the sqswatcher agent running on the nodes so we can better understand what's happening? Also, feel free to shutdown your cluster. We will try to reproduce what you are seeing from our end.

**Comment by guorongxu** [comment]
Hello Raghu,

Thank you so much for your help!
I downloaded the logs from the master node and one compute node which was processing one job. I did not shutdown the cluster because this case is not that easy to reproduce. So you feel free to look into the cluster if you want. I set the compute node to 0 and only keep the master node running, so you can check the cluster for trouble shooting.

[log_node.zip](https://github.com/awslabs/cfncluster/files/1545213/log_node.zip)
[log_master.zip](https://github.com/awslabs/cfncluster/files/1545214/log_master.zip)

Thanks,
Guorong

**Comment by rajachan** [comment]
From your sqswatcher logs:

```
2017-12-04 00:32:05,860 ERROR [sge:__runSgeCommand] Failed to run ['/opt/sge/bin/lx-amd64/qconf', '-dattr', 'hostgroup', 'hostlist', 'ip-172-31-25-219', '@allhosts']
2017-12-04 00:32:05,869 ERROR [sge:__runSgeCommand] Failed to run ['/opt/sge/bin/lx-amd64/qconf', '-de', 'ip-172-31-25-219']
error writing to file "/opt/sge/default/spool/qmaster/admin_hosts/.ip-172-31-27-8.us-west-2.compute.internal": No space left on device
error writing to file "/opt/sge/default/spool/qmaster/submit_hosts/.ip-172-31-27-8.us-west-2.compute.internal": No space left on device
error writing to file "/opt/sge/default/spool/qmaster/exec_hosts/.ip-172-31-27-8.us-west-2.compute.internal": No space left on device
error writing object "ip-172-31-27-8.us-west-2.compute.internal" to spooling database
2017-12-04 00:47:38,809 ERROR [sge:__runSgeCommand] Failed to run ['/opt/sge/bin/lx-amd64/qconf', '-Ae', '/tmp/tmpMg4sAB']
```

You are possibly saturating the storage capacity on the `/opt/sge` NFS mount which is causing the `qconf` commands to fail.  That NFS export is for internal use only.  Using the `/shared` NFS mount that is also exported by default from the Master node might better serve your needs for shared storage across all the nodes to install third-party software or to store external application data. Refer to the [this documentation entry](http://cfncluster.readthedocs.io/en/latest/configuration.html#shared-dir) for more information on customizing the `/shared` mount point.

**Comment by guorongxu** [comment]
Hi Raghu,

Thank you for your help!
I created root volume with 2TB and attached to each compute node because the I/O will be very slow if all 10 nodes and 32 threads read/write to /shared disk at the same time. So I let each node run the process and read/write to the local volume. Besides, I used the exactly same cfncluster to create another new cluster and is working well. 

The below is my cfncluster configuration file. 

Thanks,
Guorong 

[aws]
aws_region_name = us-west-2
aws_access_key_id = 
aws_secret_access_key = 

[cluster ccbb]
vpc_settings = public
key_name = 
master_instance_type = t2.medium
compute_instance_type = r3.8xlarge
initial_queue_size = 1
cluster_type = spot
spot_price = 1.5
compute_root_volume_size = 2000
ebs_settings = custom
s3_read_resource = arn:aws:s3:::my-bucket
s3_read_write_resource = arn:aws:s3:::my-bucket/*

[vpc public]
master_subnet_id = subnet-611e3e06
vpc_id = vpc-b79682d0

[global]
update_check = true
sanity_check = true
cluster_template = ccbb

[ebs custom]
ebs_snapshot_id =

**Comment by rajachan** [comment]
To clarify my earlier observation, the `/opt/sge` mount is exported from the root volume on the Master server, just like how `/home` is.   Based on your configuration, you are using the default root volume size (15GB), and are possibly saturating that. 

You can have CfnCluster configure the Master with a larger root volume using the [master_root_volume_size](http://cfncluster.readthedocs.io/en/latest/configuration.html#master-root-volume-size) configuration parameter.

**Comment by guorongxu** [comment]
Hi Raghu,

I just double checked the root volume of the master node and it is full. I will delete the log files and try it again.

Thanks a lot,
Guorong

**Comment by rajachan** [comment]
If you have a long-running cluster, it is possible that the SGE logs are causing this. You might want to check out http://gridscheduler.sourceforge.net/howto/rotatelogs.html for some guidance on manually rotating its logs.

**Comment by guorongxu** [comment]
Hi Raghu,

Thank you for your clarification!
The problem is that cfncluster cannot keep adding compute nodes into the cluster if the error is happen, otherwise, the users have to pay the usage for all idle nodes. I have only 5 jobs in the queue but the cfncluster had added 9 idle nodes into the console instead of cluster. I think cfncluster can catch the error and then let the compute nodes offline after a while if the nodes cannot added into the cluster, so the users don't have to manually change the settings to delete the nodes from the cluster. What do you think?

Best,
Guorong

**Comment by bwbarrett** [comment]
@guorongxu, any node added should die within the hour, because it will have been idle for the next hour.  You're right that the behavior of the system when the disk is full is not awesome, but in general most systems don't behave properly when the disk is full.  There's not a great way to fix this bug from the CfnCluster point of view; the easiest thing for you the customer to do is to add a CloudWatch metric for disk space (you'll need to add the cloudwatch agent to the master node) and clean up the disk when it approaches full.

**Comment by guorongxu** [comment]
Hi Brian,

Thank you so much for reply!
Unfortunately, the idle nodes never die within the hour and they were showing in the console all days until I changed the autoscaling settings to shut down. So that's why I did not terminate the cluster and hope you guys can check what's going on, I don't want this issue happens again and again. Is it possible for you to take a look? Please let me know if you need my help to provide any log, or access key to trouble shooting.

Thanks,
Guorong

**Comment by bwbarrett** [comment]
Looking at the code some more, you're right, it won't scale down.  It's a trade-off between not scaling down when SGE is down for a transient failure and when it's down for misconfiguration.  We're probably not going to change that in the near future (but are open to patches that take the balance into account).

In this case, however, the root cause is a full `/` volume on the master node.  The solution is to clean up the disk, not let it fill again, and terminate the instances that aren't currently part of the SGE cluster.  There's nothing for us to look at, so please don't leave the cluster running for us.  As I said previously, the way to avoid this issue in the future is to add an alarm about disk space and make more space available when it goes off.
