### ISSUE TITLE
Question: list of changes/enhancements  from 1.3.x to 1.4.x? 

### ISSUE THREAD

**Issue by adavanisanti** [awslabs/cfncluster#278]
Could you point me to list of changes/enhancements/bug fixes that happened in 1.4.x compared to 1.3.x? This will help me remove any workarounds that I was using for some problems in 1.3.x and take advantage of enhancements.

Thanks
Santi

**Comment by rajachan** [comment]
[Here](https://github.com/awslabs/cfncluster/compare/v1.3.2...v1.4.1) are all the commits between v1.3.2 and v1.4.1 releases.

**Comment by jocherry** [comment]
Additionally, [here](https://forums.aws.amazon.com/ann.jspa?annID=5254) is the release announcement from the AWS forum.

**Comment by adavanisanti** [comment]
Thanks @rajachan @jocherry
