### ISSUE TITLE
Post install script failing

### ISSUE THREAD

**Issue by adavanisanti** [awslabs/cfncluster#279]
I have a post install script to mount s3 using s3-fuse with below changes

```
post_install = <s3_mount_script.sh>
post_install_args = "arg1" "arg2" "arg3" "arg4"
```

The post-install script fails with following error message on cfn-init.log. I am printing the args to verify. Looks like the script is arg 1 and not arg 0.

```
2017-12-18 20:34:53,854 [DEBUG] Command runpostinstall 
output: Script name /tmp/tmp.Y0sXIK01a4
<s3_mount_script.sh>
<arg1>
<arg2>
<arg3>

cfncluster: fetch_and_run - Failed to run boot_as_master postinstall

2017-12-18 20:34:53,854 [ERROR] Error encountered during build of shellRunPostInstall: Command runpostinstall failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 517, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 248, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command runpostinstall failed
```

 Should I append my argument ids to make this work? Could you please help?

**Comment by adavanisanti** [comment]
Looks like there is a problem in file ```/opt/cfncluster/scripts/fetch_and_run```
 with ```$tmpfile $@``` line where ```$@``` includes the post_install_script itself.

```
function download_run (){
    url=$1
    scheme=$(echo "${url}"| cut -d: -f1)
    tmpfile=$(mktemp)
    trap "/bin/rm $tmpfile" RETURN
    if [ "${scheme}" == "s3" ]; then
      aws --region ${cfn_region} s3 cp ${url} - > $tmpfile || return 1
    else
      wget -qO- ${url} > $tmpfile || return 1
    fi
    chmod +x $tmpfile || return 1
    $tmpfile $@ || return 1
}
```

```
function run_postinstall () {
  RC=0
  if [ "${cfn_postinstall}" != "NONE" ]; then
    if [ "${cfn_postinstall_args}" != "NONE" ]; then
        download_run ${cfn_postinstall} ${cfn_postinstall_args}
    else
        download_run ${cfn_postinstall}
    fi
  fi || error_exit "Failed to run boot_as_master postinstall"
}
```

**Comment by jocherry** [comment]
What makes you think this is an issue with post-install script runner vs an issue with your script? Are you suspecting this is an issue with argument passing to the post install script?

Does your script do any logging?  Can you include that output?

**Comment by adavanisanti** [comment]
@jocherry Yes, I included the output in my first message. I am printing all arguments to my post-install script. The first argument seems to be the argument itself. Please see above.

**Comment by jocherry** [comment]
@adavanisanti Got it, let me have a look to try to reproduce.

**Comment by jocherry** [comment]
Hey @adavanisanti,
I ran some tests locally and am seeing the correct behavior.  
This means I see $1 in the script as being the script location, followed by $2 ...$n as the args passed in.
Are you seeing a different result? Are there first and second argument being switched?

**Comment by lukeseawalker** [comment]
pre/post-install args position have been clarified in the doc https://github.com/awslabs/cfncluster/commit/666588615d67950216e5944f463d8d0daf921a54
