### ISSUE TITLE
SLURM Dependency Issue

### ISSUE THREAD

**Issue by Preco01** [awslabs/cfncluster#288]
Hello,

I have jobs dependencies problem on cfncluster using SLURM. When I launched a dependency job tested with SLURM from cfncluster I have an error.

-Please find bellow the dependency test code:
`#!/bin/sh

id=`sbatch --job-name=factor9-1 --ntasks=1 --ntasks-per-core=1 
--output=/shared/ix26501.slurmout  /shared/jobscript`
echo "ntasks 1 jobid $id"

for n in 2 4 8 16 32; do
    id=`sbatch --depend=afterany:$id --job-name=factor9-$n --ntasks=$n --ntasks-per-core=1 --output=/shared/x2650-$n.slurmout /shared/jobscript`;
    echo "ntasks $n jobid $id"
    done`

-Please find bellow errors I got:
`batch: error: Batch job submission failed: Job dependency problem
ntasks 2 jobid
sbatch: error: Batch job submission failed: Job dependency problem
ntasks 4 jobid
sbatch: error: Batch job submission failed: Job dependency problem
ntasks 8 jobid`

Is anyone already got this kind of issue or do you have any idea how to fix it?

Thx in advance :)
P1

**Comment by rajachan** [comment]
The output of sbatch is not the job ID itself, but a string confirming the successful submission of the job along with a job ID. In your script, you might want to awk out the job ID from the sbatch command's output. For instance, the following would work:

```id=$(sbatch --job-name=factor9-1 --ntasks=1 --ntasks-per-core=1 --output=/shared/ix26501.slurmout /shared/jobscript | awk '{print $4}')```

Feel free to reopen this issue if your problem persists.

**Comment by Preco01** [comment]
Hello,

Thank you for your answer.
I tested with awk but I still have errors after the first job is sent.

-->So here is the batch to test dependencies on cfncluster using SLURM with your code modification:
`#!/bin/sh

id=$(sbatch --job-name=factor9-1 --ntasks=1 --ntasks-per-core=1 -output=/shared/ix26501.slurmout /shared/jobscript | awk '{print $4}')
echo "ntasks 1 jobid $id"

for n in 2 4 8 16 32; do
    id=`sbatch --depend=afterany:$id --job-name=factor9-$n --ntasks=$n --ntasks-per-core=1 --output=/shared/x2650-$n.slurmout jobscript`;
    echo "ntasks $n jobid $id"
    done`

-->Here is jobscript:
`#! /bin/bash

echo "Dependencies on $HOSTNAME "`

-->And here errors I got:
`ntasks 1 jobid 26
ntasks 2 jobid Submitted batch job 27
sbatch: error: Batch job submission failed: Job dependency problem
ntasks 4 jobid
sbatch: error: Batch job submission failed: Job dependency problem
ntasks 8 jobid
sbatch: error: Batch job submission failed: Job dependency problem
ntasks 16 jobid
sbatch: error: Batch job submission failed: Job dependency problem
ntasks 32 jobid`

Do you see what goes wrong?
Do you think I should modify something on SLURM or cfnconfig config.

P1

**Comment by rajachan** [comment]
You should extract the job ID from the child job's sbatch command inside your loop as well.
