### ISSUE TITLE
user providers removing `supports { manage_home: true }` from v13

### ISSUE THREAD

**Issue by rajachan** [awslabs/cfncluster#289]
When looking through cookbook logs, I noticed a deprecation warning for the supports flag of the user provider that we use in several places. Some additional information is [available here](https://github.com/chef/chef/issues/5371).

This issue is to remind us to make the change when we move away from Chef `12.19.36` that we are currently using so we don't fail with an upgrade.

**Comment by lukeseawalker** [comment]
done in https://github.com/awslabs/cfncluster-cookbook/commit/7228ae631156be917319af526cb829dbfacf2844
