### ISSUE TITLE
build cluster from linux AMIs?

### ISSUE THREAD

**Issue by dkoppstein** [awslabs/cfncluster#29]
It'd be nice to be able to build cfncluster from standard AMIs. Currently, the StarCluster AMIs are very out of date (stuck on Ubuntu 12 series) which causes problems with software installation. An AWS customer representative suggested cfncluster as an alternative, but I'm worried that the cfncluster AMIs will go out of date too in the future.

**Comment by dougalb** [comment]
You can take the code from GitHub and install onto an AMI, then probably update the CloudFormation, however there is work ongoing to support more OS choices and make it easier for customers to use their own AMI and customize existing.

**Comment by dkoppstein** [comment]
I see, thanks for the clarification. What would need to be done in addition to `cd bootstrap; make install` to get this installed on an AMI? I'd be happy to help with documentation or be a guinea pig. I'm interested in getting this working on Ubuntu 14.04 and autodeploying an ansible configuration upon node instantiation.

**Comment by cancan101** [comment]
@dkoppstein Looking over the coder, it is not clear to me that `cd bootstrap; make install` is enough to build an AMI. For example where is SGE installed?

**Comment by dougalb** [comment]
With the move to Chef for AMI building and bootstrapping, it should now be simpler to build a custom AMI. You can use the build_ami.sh script as part of the https://github.com/awslabs/cfncluster-cookbook project.

**Comment by kdaily** [comment]
Nice! Can I use the Packer config file as a basis for my install directly?

**Comment by dougalb** [comment]
Yes, although the build_ami.sh script sets some required variables used by the packer json files. 

Also the goal of CfnCluster is to provide an environment that you can quickly launch and tear down. As such, customers typically don't customize an AMI but rather add simple customizations using post_install and then additionally add an application environment using an EBS snapshot.

**Comment by kdaily** [comment]
Thanks. We're using it as a longer running cluster with many users giving input to what should be installed, then tearing down and re-launching when new software is required. But I might be able to 'retrain' my collabs to use it more in the fashion as designed.
