### ISSUE TITLE
post install script has to exit 0

### ISSUE THREAD

**Issue by veloduff** [awslabs/cfncluster#291]
This may be the same problem being seen in issue 279 (https://github.com/awslabs/cfncluster/issues/279)

If the post install script does not exit with 0, then the boot process fails.  The issue is in the download_run function.  The command is run using an or ( || ), which means if any part command fails, the return code is 1 and results in a boot fail.   I've noted the location below.

```
function download_run (){
    url=$1
    scheme=$(echo "${url}"| cut -d: -f1)
    tmpfile=$(mktemp)
    trap "/bin/rm $tmpfile" RETURN
    if [ "${scheme}" == "s3" ]; then
      aws --region ${cfn_region} s3 cp ${url} - > $tmpfile || return 1
    else
      wget -qO- ${url} > $tmpfile || return 1
    fi
    chmod +x $tmpfile || return 1
    $tmpfile $@ || return 1     ##### <----- right here  ######
}
```

I would allow the boot process to continue, regardless of the return code, but then catch and log the return code.

You can recreate this by creating a post install script with "exit 1":
```
#!/bin/bash
exit 1
```

**Comment by bwbarrett** [comment]
By design, we fail to build the cluster / compute nodes if the install scripts don't complete successfully; they returned an error, so something is broken.  Disabling rollback of the CloudFormation template will allow customers to debug, if necessary.

We don't think changing the default behavior is the right choice.  A better option would be to add a parameter in the config file (and cloud formation template) to allow the user to choose behavior.  I'm not sure when we'll be able to work on this item, but we'll keep this issue open for our backlog.

**Comment by veloduff** [comment]
What about just adding more info: 

```
--- fetch_and_run	2018-01-15 00:38:54.068588708 +0000
+++ fetch_and_run.duff	2018-01-15 00:41:20.047024547 +0000
@@ -21,11 +21,12 @@
       wget -qO- ${url} > $tmpfile || return 1
     fi
     chmod +x $tmpfile || return 1
-    $tmpfile $@ || return 1
+    $tmpfile $@ || error_exit "Failed to run boot_as_master $ACTION, $file failed with non 0 return code: $?"
 }

 function run_preinstall () {
   if [ "${cfn_preinstall}" != "NONE" ]; then
+    file="${cfn_preinstall}"
     if [ "${cfn_preinstall_args}" != "NONE" ]; then
         download_run ${cfn_preinstall} ${cfn_preinstall_args}
     else
@@ -37,6 +38,7 @@
 function run_postinstall () {
   RC=0
   if [ "${cfn_postinstall}" != "NONE" ]; then
+    file="${cfn_postinstall}"
     if [ "${cfn_postinstall_args}" != "NONE" ]; then
         download_run ${cfn_postinstall} ${cfn_postinstall_args}
     else
```

**Comment by mohanasudhan** [comment]
Looks ok to me, please file a PR. we are happy to review and take it in. Thanks

**Comment by lukeseawalker** [comment]
Commit https://github.com/awslabs/cfncluster-cookbook/commit/9f53f9f1e1eebf55dfa95f0cdeb6ee4651fc56eb
