### ISSUE TITLE
How to run a bootstrap script on compute node? 

### ISSUE THREAD

**Issue by chandrakantlotke** [awslabs/cfncluster#300]
I would like to run the bootstrap script on compute node. where can I insert the script in cloud formation template? Probably in ComputeServerLaunchConfig->User data.
But here I can not paste simple bash script, it needs some formatting. Please suggest any suitable option.

**Comment by jocherry** [comment]
I think you should use a post install script:
http://cfncluster.readthedocs.io/en/latest/configuration.html#post-install

Which will execute on the master and compute nodes.

**Comment by jmenbo** [comment]
If you only want to run the post script on compute nodes, you can add the following `if` statement to check if there are NFS exports or not. By default, only the Master node provides NFS exports.
```bash
if [ ! -s /etc/exports ]  # If the exports file is "empty" it is a compute node and NOT the master node. 
   then
   # execute commands on compute nodes
fi
```
