### ISSUE TITLE
ORTE lost communication

### ISSUE THREAD

**Issue by karlvirgil** [awslabs/cfncluster#301]
In the last 24 hrs I have started receiving these job termination messages when running on an sge-enabled cfncluster.  The same job has been running fine for many days prior.  I am running on 10 compute nodes of c5.18xlarge
 
```
error: commlib error: got read error (closing "ip-10-15-20-17.ec2.internal/shepherd_ijs/1")
 --------------------------------------------------------------------------
 ORTE has lost communication with its daemon located on node:

   hostname:  ip-10-15-20-17.ec2.internal

 This is usually due to either a failure of the TCP network
 connection to the node, or possibly an internal failure of
 the daemon itself. We cannot recover from this failure, and
 therefore will terminate the job.

```
Any thoughts?

**Comment by bwbarrett** [comment]
The commlib and ORTE errors are coming from two different packages, so it looks like something caused all connections to 10.15.20.17 to die.  The first thing I would check is the health of that instance; is it still up, can you ssh into it, etc.  My first, mostly uneducated, guess would be that your instance rebooted for some reason, which logs should be able to highlight.
