### ISSUE TITLE
Unresolved resource depancies when using ec2_iam_role?

### ISSUE THREAD

**Issue by klitgord** [awslabs/cfncluster#303]
Hello,
   I want to add the ec2:create_volume function my compute nodes and figure that creating a custom role would be the way to go.  So I created a new policy as per the 'CfnClusterInstancePolicy' updating the account id an region blocks, plus the additional ec2 functionality.   I then created a new role and attached this policy to it.  The in my confgure file, I pass the arn for the role to the 'ec2_iam_role' param.

unfortunately though when I try to run, I get the following error: 

Template format error: Unresolved resource dependencies [RootRole] in the Resources block of the template

I don't have any mention of RootRole, so I presume that cfncluster is looking for something I am failing to define?  

Any suggestions at to what I would need to add and where?

kind regards,
   Niels

**Comment by rajachan** [comment]
@klitgord, this seems like an issue with the template formatting. Take a look at [this FAQ](https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-template-validation/) entry and see if that helps. You might also want to [validate your template](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-validate-template.html) to make sure your syntax is correct.

**Comment by rajachan** [comment]
@klitgord, RootRole is a resource in CfnCluster's cloudformation template that gets created by default when a custom Instance profile is not provided. It seems like the input you provide to ec2_iam_role is either malformed or not of the right syntax, causing the template validation to fail. Take a look at [this FAQ entry](https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-template-validation/) and see if that helps. If you want to validate the syntax of your input to ec2_iam_role, you could try making the change directly in the CfnCluster template and [validating it](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-validate-template.html) for correctness.

**Comment by rajachan** [comment]
@klitgord, also note that ec2_iam_role takes the name of the IAM role (which should be the same name as that of your Instance Profile) and not its arn. For instance, if you have the following role:

```
Role ARN               : arn:aws:iam::0123456789:role/TestAdmin
Role description:      : Test EC2 admin role.
Instance Profile ARNs  : arn:aws:iam::0123456789:instance-profile/TestAdmin
```

You should set `ec2_iam_role = TestAdmin` in your CfnCluster configuration.

**Comment by klitgord** [comment]
Ah, thank you @rajachan , 
seems like you identified multiple likely issues.  I was indeed using the full arn to identify the role, thank you for pointing that, but that alone did not fix things. I will take a look at the other suggestions you had. kind regards 
-niels
