### ISSUE TITLE
Is it safe to duplicate the "master" instance for a single cluster?

### ISSUE THREAD

**Issue by jprobichaud** [awslabs/cfncluster#304]
For our use-cases, it is not rare that generating the set of jobs one wants to submit in the grid takes some non-trivial amount of processing power or RAM.  We are using cfncluster to create an SGE grid.

For that reason, I'm wondering if it is possible/safe once the cluster is created that a colleague could use the EC2 console to clone the Master compute node using the "launch another instance like this" feature.  

Would that mess how the SGE queue/scheduler behave?

**Comment by bwbarrett** [comment]
I believe it is safe to "launch another instance like this", meaning that I think it won't mess up the existing cluster.  However, the new instance won't result in a working cluster; there are a number of pieces to CfnCluster necessary for a working cluster (an SQS queue, a DynamoDB table, an AutoScaling Group, some CloudWatch metrics, etc.) which will not be duplicated.  There are also some launch parameters from CloudFormation that are likely not to be setup properly.  So you'd end up with an instance of dubious use that will confuse everyone.  But it shouldn't harm anything.

Your best bet is to create another cluster using the CfnCluster cli and same configuration file, but with a different cluster name.  That will give you a mirror set of resources that works end to end.
