### ISSUE TITLE
no signal that MasterServer is provisioned for certain types of custom VPCs

### ISSUE THREAD

**Issue by legel** [awslabs/cfncluster#31]
During "cfncluster create examplename", when using a custom VPC setting defined in the AWS Console, the system gets stuck at "Status: MasterServer - CREATE_IN_PROGRESS", even though the MasterServer does get successfully created (upon manually inspecting it in EC2 Dashboard).

It's possible my inexperience with subnets caused some sort of communication feedback problem. I used a VPC CIDR with 10.0.0.0/16 (DNS resolution: Yes, DNS hostname: Yes) and set up a subnet 10.0.0.0/26 (Default Subnet: No, Auto-assign Public IP: No) with an attached Internet gateway and a default DHCP option (ec2.internal). The VPC was launched in us-east-1.

This led me to try digging around all of the underlying code... Finally I considered that maybe my VPC attempt was naive somehow, and so went with one of the Default VPCs. At first, still a delay in the response of MasterServer... 

But, then, the magical words: cfncluster-examplename CREATE_COMPLETE ... with all the outputs that you want to see, including the elegant neuroscience-inspired name "Ganglia".  :) 

Anyways, I wanted to post this experience - a bug, or at least a failure of the system to help me address a potentially problematic VPC configuration - so that others might be able to tear this, and so that this case can be considered in developing this out.

**Comment by dougalb** [comment]
Closing in favor of discussion in AWS forums - https://forums.aws.amazon.com/thread.jspa?threadID=180213&tstart=0
