### ISSUE TITLE
Not able to create cfncluster - Received FAILURE signal with UniqueId i-0e29a2bf890609db8

### ISSUE THREAD

**Issue by badaldavda** [awslabs/cfncluster#313]
cli version 1.4.2 -

=====config=====
[global]
cluster_template = default
update_check = true
sanity_check = true

[aws]
aws_region_name = us-east-1
aws_access_key_id = xxx
aws_secret_access_key = xxx

[cluster default]
key_name = northVirginia
compute_instance_type = c4.xlarge
master_instance_type = c4.xlarge
initial_queue_size = 1
max_queue_size = 10
maintain_initial_size = false
scheduler = sge
cluster_type = ondemand
master_root_volume_size = 50
compute_root_volume_size = 50
vpc_settings = public
cwl_region = us-east-1
base_os = centos7

[vpc public]
vpc_id = vpc-43258725
master_subnet_id = subnet-5e177773
vpc_security_group_id = sg-4fd7d733

Uploading the files.
Changed chef-stacktrace.out to chef-stacktrace.log for uploading. 
[chef-stacktrace.log](https://github.com/awslabs/cfncluster/files/1698339/chef-stacktrace.log)

[cfn-wire.log](https://github.com/awslabs/cfncluster/files/1698332/cfn-wire.log)
[cfn-init.log](https://github.com/awslabs/cfncluster/files/1698333/cfn-init.log)
[cfn-init-cmd.log](https://github.com/awslabs/cfncluster/files/1698334/cfn-init-cmd.log)

**Comment by badaldavda** [comment]
Hi were you able to replicate this? I tried this with ubuntu and it worked.

**Comment by jocherry** [comment]
Hello,
I tried to replicate this, but was unsuccessful.  I copied your config, but creating the stack is succeeding.

I am curious about your security group, does it allow access to nfs ports as required?
https://docs.aws.amazon.com/efs/latest/ug/accessing-fs-create-security-groups.html
(look at 3.b)

**Comment by badaldavda** [comment]
Hi. I did add NFS ports but still was not able to create it. Again it rolledback with failure signal

**Comment by bwbarrett** [comment]
@badaldavda, since we can't replicate this problem internally, I don't have any great advice on debugging.  Your best bet is probably to add the `--norollback` option to `cfncluster create` and log into both the master and compute nodes and try to run the nfs command on the compute node.  If it still fails, making sure the nfs server is running would be the next step, then tcpdump on the master and compute nodes to make sure the packets are being sent and received.

**Comment by badaldavda** [comment]
Sure will do it. Thanks.
