### ISSUE TITLE
Ubuntu 17.10 cfncluster AMI

### ISSUE THREAD

**Issue by adavanisanti** [awslabs/cfncluster#314]
Hi - Is there an Ubuntu 17.10 cfncluster AMI? I could not find one here: https://github.com/awslabs/cfncluster/blob/master/amis.txt

Thanks
Santi

**Comment by mohanasudhan** [comment]
No, we haven't got to support ubuntu 17.10 yet.

**Comment by bwbarrett** [comment]
And likely won't ever support 17.10.  We traditionally have only supported current LTS releases (currently, that's 14.04 and 16.04).  So the next Ubuntu release we would add to CfnCluster would be 18.04 when it comes out this year.

**Comment by adavanisanti** [comment]
Thanks!
