### ISSUE TITLE
problems mounting shared volume with c5.9xlarge

### ISSUE THREAD

**Issue by gtrotter** [awslabs/cfncluster#315]
We are experimenting with going from c4.8xl to c5.9xl for master and compute nodes. In the cloudformation I added the c5.9xl as an allowed type, and then launch with that type. The launch fails.

I'll include the stacktrace below, but the problem seems to be mounting the shared volume. The recipe seems to be trying to mount it from /dev/disk/by-ebs-volumeid -- but that doesn't exist on the c5s. Perhaps because of the NVMe block storage?

On the c4, the storage appears as /dev/xvdb, and the recipe can find it:

```
[ec2-user@ip-10-100-113-7 ~]$ ll /dev/disk/by-ebs-volumeid/
total 0
lrwxrwxrwx 1 root root 10 Feb  8 18:01 vol-07ceefef96783d079 -> ../../xvdb

```

On the c5, it presents as  /dev/nvme1n1 and there is no by-ebs-volumeid directory:

```
[ec2-user@ip-10-100-115-252 log]$ ls /dev/disk
by-id  by-label  by-partlabel  by-partuuid  by-path  by-uuid

```

So, am I doing something wrong here? Is there some configuration option that will allow the recipe to use these mounts? Or is this code incompatible with the block volumes on c5s?

Here's the stacktrace:

`Generated at 2018-02-08 21:03:49 +0000
Timeout::Error: execution expired
/etc/chef/local-mode-cache/cache/cookbooks/cfncluster/libraries/helpers.rb:10:in `sleep'
/etc/chef/local-mode-cache/cache/cookbooks/cfncluster/libraries/helpers.rb:10:in `block in wait_for_block_dev'
/opt/chef/embedded/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/etc/chef/local-mode-cache/cache/cookbooks/cfncluster/libraries/helpers.rb:9:in `wait_for_block_dev'
/etc/chef/local-mode-cache/cache/cookbooks/cfncluster/recipes/_master_base_config.rb:39:in `block (2 levels) in from_file'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/provider/ruby_block.rb:35:in `block in action_run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/provider.rb:176:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/provider/ruby_block.rb:34:in `action_run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource.rb:622:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:77:in `block in run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:75:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:75:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:670:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:665:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:665:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:704:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:284:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:295:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:283:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:283:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:248:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:236:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:57:in `load'`

**Comment by mohanasudhan** [comment]
Can you paste your cfncluster config ( don't forgot to mask credential information ) ? Plus it would be useful to have cfn-init.log

**Comment by gtrotter** [comment]
The config is inline below, and the cfn-init.log is attached.

[ec2-user@ip-10-100-112-220 cfncluster]$ cat cfnconfig 
stack_name=cfncluster-nwp-c5
cfn_preinstall=NONE
cfn_preinstall_args=NONE
cfn_postinstall=s3://cfncluster-nwp-prod/nwp/cfncluster_postinstall_prod.sh
cfn_postinstall_args="NONE"
cfn_region=us-east-1
cfn_scheduler=slurm
cfn_scheduler_slots=cores
cfn_instance_slots=18
cfn_encrypted_ephemeral=false
cfn_ephemeral_dir=/scratch
cfn_shared_dir=/shared
cfn_proxy=NONE
cfn_node_type=MasterServer
cfn_cluster_user=ec2-user
cfn_volume=vol-050803ed2a377bf6c
[ec2-user@ip-10-100-112-220 cfncluster]$ cd
[ec2-user@ip-10-100-112-220 ~]$ cat /etc/cfncluster/cfnconfig 
stack_name=cfncluster-nwp-c5
cfn_preinstall=NONE
cfn_preinstall_args=NONE
cfn_postinstall=s3://cfncluster-nwp-prod/nwp/cfncluster_postinstall_prod.sh
cfn_postinstall_args="NONE"
cfn_region=us-east-1
cfn_scheduler=slurm
cfn_scheduler_slots=cores
cfn_instance_slots=18
cfn_encrypted_ephemeral=false
cfn_ephemeral_dir=/scratch
cfn_shared_dir=/shared
cfn_proxy=NONE
cfn_node_type=MasterServer
cfn_cluster_user=ec2-user
cfn_volume=vol-050803ed2a377bf6c


[cfn-init.log](https://github.com/awslabs/cfncluster/files/1709675/cfn-init.log)

**Comment by jocherry** [comment]
Which version of cfncluster are you using?
We introduced a solution to this problem in 1.4.0, so if you are using an older version you will need to upgrade.
If you're using > 1.4.0 there may be a bug to explore.

Please let us know which version you are using.

**Comment by gtrotter** [comment]
Ah. Yes, we were running 1.3.2. Upgrading fixed the problem. Thanks!
