### ISSUE TITLE
More than one job per node on a slurm cluster.

### ISSUE THREAD

**Issue by asalomatov** [awslabs/cfncluster#317]
I cannot get slum ro run more than one job per node. For example,

for i in {1..10}; do sbatch -N1 --ntasks-per-node=3 --wrap="sleep 10; echo $(date) $(hostname)"; done

I should see 3 jobs per node, but it only runs one.

I'm running cfncluster 1.4.2
I have this line in my config

extra_json = {"cfncluster" : { "cfn_scheduler_slots" : "10" }}

Thanks.

**Comment by asalomatov** [comment]
I tried modifying slurm.conf ...
slurm daemon would not start after the modification
#SelectType=select/linear 
SelectType=select/cons_res

**Comment by jocherry** [comment]
A few quick questions for you:
1. Did you try removing you extra_json line? Based on the documentation (https://slurm.schedmd.com/srun.html#OPT_ntasks-per-node) it looks like this could be taken as an upper bound if it senses another slot has been set.
2. Do you see it running the amount of times you expect?  It running 10 times? Or is it all running on one cluster? Or are you saying it runs one job per node?

**Comment by asalomatov** [comment]
I tried without extra_json in the config file, that does not seen to have any effect.
It always runs one job per node regardless of what is given in --ntasks-per-node

I was able to get the desired behavior from SGE so I’ve moved on to using that as a scheduler.

**Comment by jocherry** [comment]
I believe the issue is with -N1.
Based on the documentation that will be both the min and max number of nodes (when you only use one number) for allocation:
https://slurm.schedmd.com/srun.html#OPT_nodes
You will have to allocate your nodes differently to achieve this, but if you're now using SGE this may not be useful.

**Comment by lukeseawalker** [comment]
Slurm is now able to submit more than one job per node https://github.com/awslabs/cfncluster-node/commit/9ba545c371a56c1c1372c26132b328b9ccad2e39
