### ISSUE TITLE
can not launch c5.2xlarge through cfncluster

### ISSUE THREAD

**Issue by miker2746** [awslabs/cfncluster#322]

**Comment by miker2746** [comment]
hi,
I recently updated cfncluster to the newest version, but it can not launch two c5.2xlarge in placement group. And it always create ROLLBACK_IN_PROGRESS

`totoro@TOTORO:~$ cfncluster create -t mt-cluster1 mt-test7
Beginning cluster creation for cluster: mt-test7
Creating stack named: cfncluster-mt-test7
Status: cfncluster-mt-test7 - ROLLBACK_IN_PROGRESS                              
Cluster creation failed.  Failed events:
  - AWS::EC2::Instance MasterServer Received FAILURE signal with UniqueId i-06478198535713875
totoro@TOTORO:~$ 
`

and my config file is:

`## cfncluster templates
[cluster mt-cluster1]
# Name of an existing EC2 KeyPair to enable SSH access to the instances.
key_name = mt-test1
# Override path to cloudformation in S3
# (defaults to https://s3.amazonaws.com/cfncluster-<aws_region_name>/templates/cfncluster-<version>.cfn.json)
#template_url = https://s3.amazonaws.com/cfncluster-us-east-1/templates/cfncluster.cfn.json
# Cluster Server EC2 instance type
# (defaults to t2.micro for default template)
compute_instance_type = c5.2xlarge
# Master Server EC2 instance type
# (defaults to t2.micro for default template
master_instance_type = c5.2xlarge
# Inital number of EC2 instances to launch as compute nodes in the cluster.
# (defaults to 2 for default template)
initial_queue_size =1
# Maximum number of EC2 instances that can be launched in the cluster.
# (defaults to 10 for the default template)
max_queue_size =1
# Boolean flag to set autoscaling group to maintain initial size and scale back
# (defaults to false for the default template)
#maintain_initial_size = false
# Cluster scheduler
# (defaults to sge for the default template)
#scheduler = sge
# Type of cluster to launch i.e. ondemand or spot
# (defaults to ondemand for the default template)
#cluster_type = ondemand
# Spot price for the ComputeFleet
#spot_price = 0.00
# ID of a Custom AMI, to use instead of published AMI's
#custom_ami = ami-9802b1e1
#custom_ami = ami-ff8d1886
#custom_ami = ami-62fa6e1b
#custom_ami = ami-898b1ff0

# cfncluster default ubuntu1604 image in eu-west-1
#custom_ami = ami-9802b1e1

#cfncluster-ubuntu1604-fds-image-test1
#custom_ami =ami-5694072f

#cfncluster-nfs-test1-modified-according-aws-document
#custom_ami =ami-a51f8cdc


#cfncluster-image: full FDS, no NFS
#custom_ami = ami-2b910c52

# cfncluster default ubuntu1404 image in eu-west-1
custom_ami = ami-a5e578dc




# Specify S3 resource which cfncluster nodes will be granted read-only access
# (defaults to NONE for the default template)
#s3_read_resource = NONE
# Specify S3 resource which cfncluster nodes will be granted read-write access
# (defaults to NONE for the default template)
#s3_read_write_resource = NONE
# URL to a preinstall script. This is executed before any of the boot_as_* scripts are run
# (defaults to NONE for the default template)
#pre_install = NONE
# Arguments to be passed to preinstall script
# (defaults to NONE for the default template)
#pre_install_args = NONE
# URL to a postinstall script. This is executed after any of the boot_as_* scripts are run
# (defaults to NONE for the default template)
#post_install = NONE
# Arguments to be passed to postinstall script
# (defaults to NONE for the default template)
#post_install_args = NONE
# HTTP(S) proxy server, typically http://x.x.x.x:8080
# (defaults to NONE for the default template)
#proxy_server = NONE
# Cluster placement group. This placement group must already exist.
# (defaults to NONE for the default template)

#placement_group = cfncluster-pg-1
# Cluster placment logic. This enables the whole cluster or only compute to use the placement group
# (defaults to cluster in the default template)
#placement = cluster
# Path/mountpoint for ephemeral drives
# (defaults to /scratch in the default template)
#ephemeral_dir = /scratch
# Path/mountpoint for shared EBS volume
# (defaults to /shared in the default template)
#shared_dir = /shared
shared_dir = /home



# Encrypted ephemeral drives. In-memory keys, non-recoverable.
# (defaults to false in default template)
#encrypted_ephemeral = false
# MasterServer root volume size in GB. (AMI must support growroot)
# (defaults to 10 in default template)
#master_root_volume_size = 10
# ComputeFleet root volume size in GB. (AMI must support growroot)
# (defaults to 10 in default template)
#compute_root_volume_size = 10
# OS type used in the cluster
# (defaults to alinux in the default template)
#base_os = Ubuntu
# CloudWatch Logs region
# (defaults to NONE in the default template)
#cwl_region = NONE
# CloudWatch Logs Log Group name
# (defaults to NONE in the default template)
#cwl_log_group = NONE
# Existing EC2 IAM role to be assosiated with the EC2 instances
# (defaults to NONE in the default template)
#ec2_iam_role = NONE
# Extra Json to be merged with the dna.json used by Chef
# (defaults to {} in the default template)
#extra_json = {}
# Additional CloudFormation template to launch with the cluster
#additional_cfn_template = NONE
# Settings section relating to VPC to be used
vpc_settings = mycluster3-vpc
# Settings section relating to EBS volume
#ebs_settings = fds-test-volume-2
# Settings section relation to scaling
#scaling_settings = custom`

I can launch the default t2.micro, but I have no idea why cfncluster can't launch c5.2xlarge instance, while I can launch them from the console. Hope someone could help me, thanks in advance.

best regards,

shao

**Comment by bwbarrett** [comment]
The error message indicates that `i-06478198535713875` started, but that the startup scripts either called back with a failure or never called back.  Since you are using a custom AMI, you are not necessarily using the standard start-up recipes we provide with our AMIs, so you'll have to dig a bit to figure out why. The next steps would be to create a new cluster with the `--norollback` option so that CloudFormation doesn't rollback and destroy the instance on failure, and then look at the initialization logs in `/var/log/', in particular `cfn-init-cmd.log`, `cfn-init.log`, `cfn-wire.log`, and `cloud-init.log`.  One of those is likely to have the error message that resulted in the master node calling back to CloudFormation with a failure signal.

**Comment by miker2746** [comment]
Hi,
thank you for replying me. 
I am checking these files in /var/log right now. But I was using the AMI provided by "https://github.com/awslabs/cfncluster/blob/master/amis.txt" line 57. And all other settings are defaults, the region I am using is: eu-west-1, and I have successfully used CfnCluster to launch a cluster with instance type t2.micro and the same AMI I mentioned earlier. To launch c5 instance I chose c5.2xlarge and applied placement-group, but it keeps failing. So I want to ask you a few questions, is c5 instance supported by cfncluster, and have you launched c5 instances using cfncluster successfully? I attached these files here, could you please take a look.


best regards,

shao


[cfn-init.log](https://github.com/awslabs/cfncluster/files/1748650/cfn-init.log)
[cfn-init-cmd.log](https://github.com/awslabs/cfncluster/files/1748652/cfn-init-cmd.log)
[cfn-wire.log](https://github.com/awslabs/cfncluster/files/1748653/cfn-wire.log)
[cloud-init.log](https://github.com/awslabs/cfncluster/files/1748654/cloud-init.log)

**Comment by rajachan** [comment]
> So I want to ask you a few questions, is c5 instance supported by cfncluster, and have you launched c5 instances using cfncluster successfully? 

Yes, the latest version of CfnCluster does support C5 instances. From your logs, I see you are hitting a known issue with the cookbook that has since been fixed. What version of CfnCluster are you using? I suggest you upgrade to the latest version and retry, given that we have made several changes pertaining to C5 support.

**Comment by miker2746** [comment]
Hi,


I used the CfnCluster version 1.4.2, I thought this is the latest version of CfnCluster.



________________________________
发件人: Raghu Raja <notifications@github.com>
发送时间: 2018年2月27日 2:52:42
收件人: awslabs/cfncluster
抄送: miker2746; Author
主题: Re: [awslabs/cfncluster] can not launch c5.2xlarge through cfncluster (#322)


So I want to ask you a few questions, is c5 instance supported by cfncluster, and have you launched c5 instances using cfncluster successfully?

Yes, the latest version of CfnCluster does support C5 instances. From your logs, I see you are hitting a known issue with the cookbook that has since been fixed. What version of CfnCluster are you using? I suggest you upgrade to the latest version and retry, given that we have made several changes pertaining to C5 support.

―

**Comment by rajachan** [comment]
That's right, 1.4.2 is the latest version. On closer inspection of your config file, I see that you are trying to mount the shared directory at `/home`. Note that `/home/` is already an NFS export from the Master Server that is mounted on all the nodes (see https://github.com/awslabs/cfncluster-cookbook/blob/d1ff211e422ea29a8c42ae2fb32bcc97c169dc5e/recipes/_master_base_config.rb#L88).  You do not have to do any additional setup to get that mounted. The `shared_dir` parameter is for an _additional_ NFS export that will be backed by a separate EBS volume, which you could potentially use as scratch space.  Try setting `shared_dir` to some other mountpoint (say, /scratch), or leave it at the default (/shared).
