### ISSUE TITLE
Adding post-install script to existing cfncluster stack

### ISSUE THREAD

**Issue by awacs** [awslabs/cfncluster#323]
Is it possible?

**Comment by bwbarrett** [comment]
It's definitely not supported :).  I don't think that the change will propagate through a `cfncluster update`, but have to admit that I have not tried it myself.  You'd have to modify the CloudFormation stack directly (either through the console or AWS API), and modify the `post_install` template argument.  This will *only* apply to new instances.

To be clear; as I said, we don't support changing parameters on the fly and it might delete your entire cluster, but that's the way I can think of making your change.  Our design was really assuming cluster configurations that didn't change, and making it easy to spin up/down new clusters.
