### ISSUE TITLE
Alternative configuration file

### ISSUE THREAD

**Issue by awacs** [awslabs/cfncluster#324]
Is it possible to have cfncluster create cluster stacks with alternative config files, e.g. different config files other than ~/.cfncluster/config? Somehow pass that whole file as an argument?

**Comment by rajachan** [comment]
Yes, you can provide an alternate config file using the `--config` flag and giving it a path to your custom config file.

You could also create multiple configurations with unique names within the default `~/.cfncluster/config` file and pick one to use when creating a cluster using the `--cluster-template` flag.

Feel free to reopen this ticket if neither of these options work for you.
