### ISSUE TITLE
How to add custom TCP rule on master node?

### ISSUE THREAD

**Issue by adavanisanti** [awslabs/cfncluster#327]
Hi, I would like to add a custom TCP rule on the master node that looks as below:

```
Protocol: TCP
Port Range: xxxx-yyyy
Source: Custom 0.0.0.0/0
```

Could you point me to steps or parameters to add this rule?

Thanks
Santi

**Comment by rajachan** [comment]
One option is to create a security group with the rules you want, and pass it along to CfnCluster using the [`additional_sg`](http://cfncluster.readthedocs.io/en/latest/configuration.html#additional-sg) config parameter. However, this would apply the rule to all instances, not just the master node. You could also just manually add the security group to the master instance via the console or the CLI. See [this document](https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_SecurityGroups.html#SG_Changing_Group_Membership) for additional instructions to do that.
