### ISSUE TITLE
What goes inside AMI?

### ISSUE THREAD

**Issue by mukulagrawal78** [awslabs/cfncluster#328]
Where can I find/read details about what goes inside the AMI?
By any chance of luck, is there a dockerfile that I could take a look at?
Or any other sort of step-by-step build process for any of the linux distributions for latest cfncluster release?

**Comment by rajachan** [comment]
@mukulagrawal78, are you asking so you can build a custom AMI, or just to better understand what goes inside the default CfnCluster AMIs? If it is the former, you can find instructions to build a custom AMI [here](http://cfncluster.readthedocs.io/en/latest/ami_customization.html). If it is the latter, we use a collection of Chef recipies to install HPC batch schedulers, some utilities to monitor the scheduler queue for autoscaling, NFS configuration for shared filesystem across the cluster, Ganglia for cluster monitoring, and a couple other components necessary for CfnCluster operation. If you'd like to take a closer look, the CfnCluster cookbook is available [here](http://github.com/awslabs/cfncluster-cookbook/).

If this does not answer your question, feel free to reopen this ticket.

**Comment by mukulagrawal78** [comment]
@rajachan thank you. The cfncluster cookbook repository does not have any documentation. Can you point me to where to start looking for understanding how AMI is being built? I would be most interested in Linux/Ubuntu versions. If you could just help me orient with the basic structure of the repository that might already be helpful. Thanks.

**Comment by rajachan** [comment]
Mukul, [this document](http://cfncluster.readthedocs.io/en/latest/ami_development.html) might be useful in understanding how to work with the cookbook in a development environment. [This file](https://github.com/awslabs/cfncluster-cookbook/blob/develop/attributes/default.rb) has information on the packages we pull in.

As for the directory structure, 

```
├── attributes : The default attributes that will be used by various recipies
├── files      : A collection of generic and OS-specific config files or scripts we use to configure the AMIs
├── libraries  : Some custom helper functions used by recipes
├── recipes    : The actual recipes themselves, used to configure the scheduler, ganglia, shared FS, etc
├── spec       : Specs for unit testing
├── templates  : OS-specific templates for config files
└── test       : More specs for Rubocop correctness testing
```

The shell scripts and packer files in the top-level directory are used to automate the AMI building processes.
