### ISSUE TITLE
Rate exceeded

### ISSUE THREAD

**Issue by awacs** [awslabs/cfncluster#329]
This happens during cfncluster 
Beginning cluster creation for cluster: 14554
Creating stack named: cfncluster-14554

Status: cfncluster-14554 - CREATE_IN_PROGRESS                                   
Status: cfncluster-14554 - CREATE_IN_PROGRESS                                   
Status: MasterEIP - CREATE_IN_PROGRESS                                          
Status: RootRole - CREATE_COMPLETE                                              
Status: RootInstanceProfile - CREATE_IN_PROGRESS                                
Status: MasterEIP - CREATE_COMPLETE                                             
Status: SQSPolicy - CREATE_COMPLETE                                             
Status: SQSPolicy - CREATE_COMPLETE                                             
Status: DynamoDBTable - CREATE_COMPLETE                                         
Status: AssociateEIP - CREATE_COMPLETE                                          
Status: CfnClusterPolicies - CREATE_COMPLETE                                    
Status: CfnClusterPolicies - CREATE_COMPLETE                                    
Status: CfnClusterPolicies - CREATE_COMPLETE                                    
Status: CfnClusterPolicies - CREATE_COMPLETE                                    
Status: CfnClusterPolicies - CREATE_COMPLETE                                    
Status: CfnClusterPolicies - CREATE_COMPLETE                                    
Status: CfnClusterPolicies - CREATE_COMPLETE                                    
Status: CfnClusterPolicies - CREATE_COMPLETE                                    
Status: CfnClusterPolicies - CREATE_COMPLETE                                    
Status: CfnClusterPolicies - CREATE_COMPLETE                                    
Status: CfnClusterPolicies - CREATE_COMPLETE                                    Rate exceeded

And the cfncluster create command exits out. The cluster still creates successfully, but is there a way to suppress this?

**Comment by mohanasudhan** [comment]
This looks like API throttling limit from AWS cloudformation service for your account. How often do you see this issue? 

Suggestion: Please file Cloudformation Describe* API limit increase via Support service.

**Comment by mohanasudhan** [comment]
One more improvement that I can think off is to have backoff retries in our clients when there is throttling exception.

**Comment by awacs** [comment]
Do you know which limit this is hitting?

**Comment by awacs** [comment]
This is the response from aws I got
`"We can increase your limit to a degree, but note that above 10, you might not always be able to achieve the full number of concurrent control plane operations, depending on which combination of operations you are doing at once. CreateTable requests with several Secondary Indexes, especially when each index has a "Projection" with many "NonKeyAttributes". If your systems are going to need to rely on a certain number of concurrent control plane operations (for example, if you are creating time series tables on a schedule), then be sure to test to ensure that your particular combination of table creates and deletes for your particular table configurations work as you expect.`
