### ISSUE TITLE
CloudFormation Template File

### ISSUE THREAD

**Issue by mukulagrawal78** [awslabs/cfncluster#331]
I would like to use AWS Java SDK for CloudFormation service to fire a cfnCluster.

If I use an example given here:
https://github.com/aws/aws-sdk-java/blob/master/src/samples/AwsCloudFormation/CloudFormationSample.java

and replace the template file provided in that example by the default JSON template file for a cfnCluster, such as this one:
https://s3-us-west-2.amazonaws.com/cfncluster-public-scripts/cfncluster-simple-cfd.cfn.json

would that work out of the box? 

Pardon me, I just started exploring cfnCluster. Seems powerful. Just trying to confirm that I am on the right path before going to far down the road.

**Comment by mohanasudhan** [comment]
Thanks for look at cfncluster. 

If I understand correctly, you want to use only the cloudformation template of cfncluster. In short We don't expect it to work out of the box. 

In detail:
There are couple of features in cfncluster like create, start, stop, update etc. I can see ```create``` command would work if you pass in argument correctly to template. But other features like start, stop, or update of cfncluster won't work.

**Comment by mukulagrawal78** [comment]
Thanks.
Does that mean that if I launch cfncluster using AWS console following this example:
https://aws.amazon.com/hpc/sc15/getting-started/
that wont provide me all functionality? Do I really have to use the cfncluster's CLI? Is there Java SDK or any other SDK?

Can't I use AWS Java SDK for force killing cluster? If job ends by its own, I am guessing cluster wil go away on its own after 1 hour, is that right? 
Can I read somewhere what does start, stop and update do? Alternatively, what can AWS Java SDK allows me do and what it does not?
I would also like to understand the differences between config options that are documented on cfncluster website, and the configurations in the cloudformation template of cfncluster that is used in the AWS link I posted above.

**Comment by mohanasudhan** [comment]
https://aws.amazon.com/hpc/sc15/getting-started/ demonstrate ```creating HPC cluster``` using cloudformation template of cfncluster directly using console. I would highly recommend looking at http://cfncluster.readthedocs.io/en/latest/ which explain features of cfncluster and how its built. In short, ```Cfncluster is a tool which is build around AWS services like Cloudformation, SQS, Cloudwatch etc```, Hence above console way of creating cluster would work out of the box. But to get all the features I would ask you to use cfncluster cli. May I understand your reason for using only AWS SDK?

**Comment by mukulagrawal78** [comment]
Thanks @mohanasudhan .
Currently, I use Java SDK to launch AWS instances, track them and kill them. I have configured Slurm in the AMI's that I launch and I can track utilization and other things. I now want to start firing tightly coupled and loosely coupled clusters. If I can use Java SDK then it makes my life significantly simpler to extend functionality. 
One question: if I launch the cfncluster using AWS console method, would this cluster scale up and scale down automatically? I thought I saw CloudWatch being configured in the CloudFormation cfnCluster template file. Please correct me if this is not correct.
My perception was that the master node is the main command-center of the cluster and it is receiving messages for job status and cluster status. If CLI is used then does the computer that launches cluster play any significant role in controlling the state of the cluster? Or would it still be managed by the master node? (e.g. if this computer shuts down, would cluster go down as well?)

**Comment by bwbarrett** [comment]
The interface for creating a cluster is the `cfncluster` command line.  There are no plans to change that and no plans to support other use cases.  There are a number of template parameters that must be configured just so for CnfCluster to successfully build out a cluster, which we do not intend to make part of the public API.

That being said, once the cluster creation is started, the `cfncluster` application is not really involved, other than reporting status.  Certain operations (like `stop`, `start`, and `update`) are only supported through the `cfncluster` application, but checking status of the cluster and deleting the cluster through the CloudFormation stack API will work and we'll always use the existing stack naming scheme.  So if you can shell out to `cfncluster --nowait` and then use the Java SDK for status checks and termination, that should work.  Make sense?

**Comment by mukulagrawal78** [comment]
Thank you @bwbarrett and @mohanasudhan . This makes lot more sense now.

Just a last question: Would you know which group in AWS maintains, updates and supports CloudFormation template files for cfnCluster such as this one:
https://s3-us-west-2.amazonaws.com/cfncluster-public-scripts/cfncluster-simple-cfd.cfn.json

I am not sure how old it is and if it works with latest cfnCluster AMI's etc.

Thank you.

**Comment by bwbarrett** [comment]
We do not and we (the team that works on CfnCluster) doesn't own that S3 bucket or support anything in that S3 bucket.  I would assume scripts in that Bucket don't work and looking at that template in general, I can tell you it won't work with any modern CfnCluster AMIs.

That's also not the best practice for extending the resources built by CfnCluster.  There are both pre/post-install hooks that can be configured from the CfnCluster input config (http://cfncluster.readthedocs.io/en/latest/configuration.html#post-install) and add external resources to extend the CloudFormation stack built (http://cfncluster.readthedocs.io/en/latest/configuration.html#additional-cfn-template).  Those are much more portable ways of adding features to CfnCluster.
