### ISSUE TITLE
cfncluster autoscaling with memory usage

### ISSUE THREAD

**Issue by cgibioinformatics** [awslabs/cfncluster#335]
Hi,

I'm trying to configure my autoscaling configuration. My understanding is the autoscaling use cloudwatch metrics to scale up/down. It seems like the default it's monitoring the CPU usage, is there anyway I could make it "watch" my RAM usage and scale up? Thank you!

**Comment by mohanasudhan** [comment]
autoscaling uses pending job cloudwatch metrics - point an example of slurm pending jobs https://github.com/awslabs/cfncluster-cookbook/blob/develop/templates/default/publish_pending.slurm.erb#L31

**Comment by cgibioinformatics** [comment]
Hi, would you give me more detail how to use this? will it work with SGE? thanks so much

**Comment by mohanasudhan** [comment]
Please refer information in here http://cfncluster.readthedocs.io/en/latest/autoscaling.html ; this link will explain the details of autoscaling information.
