### ISSUE TITLE
mounting preexisting EBS volume part II

### ISSUE THREAD

**Issue by austintoma** [awslabs/cfncluster#34]
I realize that you've recommended making a snapshot of the volume to mount (which works fine), but can you implement a way to mount directly from a saved volume? 

The advantage for me at least is that any data generated and output to the persistent volume during program execution is saved without losing it when the cluster is terminated. I can then remount as needed to another instance of cfncluster after going through the generated dataset without the need to find a way to save it elsewhere.

Thoughts?

**Comment by dougalb** [comment]
Added to our backlog

**Comment by szs8** [comment]
+1

**Comment by dougalb** [comment]
This has been added and can be tested as part of the cfncluster 1.0 beta. More details on the beta can be found here - https://forums.aws.amazon.com/ann.jspa?annID=3471. The specific configuration item is - http://cfncluster.readthedocs.org/en/develop/configuration.html#ebs-volume-id.

**Comment by dougalb** [comment]
Released in d14a9fcaec241fd3d87a0ca00e34c22eea0f4187
