### ISSUE TITLE
spot instance for compute fleet

### ISSUE THREAD

**Issue by karlvirgil** [awslabs/cfncluster#340]
I decided to try out using spot for the compute node instances with cfncluster.  I created a new cluster, and submitted a job to the scheduler.

In the aws console, under the Auto Scaling group -> Activity History, I see this message:

Description:DescriptionPlacing Spot instance request. Status Reason: Max spot instance count exceeded. Placing Spot instance request failed.

Not sure what this means, or why it is failing.

**Comment by bwbarrett** [comment]
It means what it says: `Max spot instance count exceeded`.  In addition to limits on the number of instances of a given type that you can launch at a time in a given region, there is a limit to the total number of spot instances that you can run.  See [the Spot Docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-spot-limits.html?icmpid=docs_ec2_console) for more details and how to increase your account's limit.
