### ISSUE TITLE
s3fs mount to cfncluster via post_install script

### ISSUE THREAD

**Issue by jackyenbioinfo** [awslabs/cfncluster#342]
Hi, 
I am trying to mount s3 bucket using s3fs via post install step. I follow this thread here https://github.com/awslabs/cfncluster/issues/98
with the following steps:

1. create iam-role for cfncluster, attached s3 bucket full access, attached cfnclusterinstancepolicy and cfnclusteruserpolicy from the template here http://cfncluster.readthedocs.io/en/latest/iam.html
2. specify "ec2_iam_role" in the cfncluster config file
3. create cluster

[global]
cluster_template = mycluster
update_check = true
#sanity_check = true
vpc_settings = public

[aws]
aws_region_name = us-east-1
aws_access_key_id = ***
aws_secret_access_key = ****

[cluster default]
key_name = mykey
vpc_settings = public

[vpc public]
vpc_id = vpc-08*****
master_subnet_id = subnet-28***
use_public_ips = true

[cluster mycluster]
vpc_settings = public
key_name = RTP key pair
master_instance_type = t2.micro
compute_instance_type = r4.2xlarge
initial_queue_size = 1
max_queue_size = 10
scheduler = sge
#placement_group = mycluster

#custom_ami = ami-125bad6f
#ephemeral_dir = /scratch
shared_dir = /shared
encrypted_ephemeral = false
master_root_volume_size = 15
compute_root_volume_size = 15

ebs_settings = custom
scaling_settings = custom

base_os = ubuntu1404
#s3_read_write_resource = arn:aws:s3:::my-s3-bucket
post_install = https://my-s3-bucket.s3.amazonaws.com/cfncluster_install_script.sh
ec2_iam_role = cfncluster-iam-role

[ebs custom]
ebs_snapshot_id = snap-0******

volume_size = 100
volume_iops = 200
volume_type = io1

but I couldn't get the post_install script to work. I keep getting 
"CREATE_FAILED | AWS::EC2::Instance | MasterServer | Received FAILURE signal with UniqueId i-0eded072de61f8124"

would someone help me or direct me to the right path? thanks

**Comment by rajachan** [comment]
@jackyenbioinfo, to debug issues like this, you can create your cluster with the [`--norollback`](http://cfncluster.readthedocs.io/en/latest/commands.html#create) flag that would disable a full rollback on any CloudFormation failure event. In your case, you would then see a stack with just a MasterServer running. You can SSH into that instance and look at the initialization logs in `/var/log/`, in particular `cfn-init-cmd.log`, `cfn-init.log`, `cfn-wire.log`, and `cloud-init.log`. One of those is likely to have the error message that resulted in the master node calling back to CloudFormation with a failure signal.
