### ISSUE TITLE
cloudwatch metrics

### ISSUE THREAD

**Issue by jackyenbioinfo** [awslabs/cfncluster#343]
Hi,

I'm wondering how to make cfncluster monitor RAM usage using cloudwatch metrics? I couldn't find too many document or example on how to do this. Thanks!

**Comment by rajachan** [comment]
@jackyenbioinfo, [this guide](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/mon-scripts.html2) would help you setup CloudWatch metrics for your EC2 instances. If you are just interested in monitoring your cluster, CfnCluster already sets up Ganglia for cluster monitoring. Ganglia does provide memory usage metrics among other things. You can find the Ganglia endpoint in the CfnCluster stack outputs, or when you run `$cfncluster status <cluster-name>`. For instance:

```
Status: cfncluster-hello-world - CREATE_COMPLETE
Output:"MasterPrivateIP"="192.168.x.x"
Output:"MasterPublicIP"="54.148.x.x"
Output:"GangliaPrivateURL"="http://192.168.x.x/ganglia/"
Output:"GangliaPublicURL"="http://54.148.x.x/ganglia/"
```

**Comment by jackyenbioinfo** [comment]
thanks @rajachan the link is not available anymore. Would you explain a little bit more how it could be done?

**Comment by rajachan** [comment]
My bad, I had a copy-paste typo in that link. Try these:

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/mon-scripts.html
https://aws.amazon.com/code/amazon-cloudwatch-monitoring-scripts-for-linux/

**Comment by jackyenbioinfo** [comment]
Thanks @rajachan ! would you confirm my understanding? So here's what I think what I should do : 1. download/install the cloudwatch monitor script to my master node 2. do this one " To collect aggregated metrics for an Auto Scaling group and send them to Amazon CloudWatch without reporting individual instance metrics

./mon-put-instance-data.pl --mem-util --mem-used --mem-avail --auto-scaling=only" 

3. make this script a cron job? so it's continuing monitoring. "./mon-put-instance-data.pl --mem-util --mem-used --mem-avail --auto-scaling=only"  " 
4. save this as my custom AMI 

thanks!

**Comment by mohanasudhan** [comment]
I recommend using post-install script, instead of creating custom AMI. It's lot easier to move to new version of cfncluster with post-install script than custom AMI

**Comment by krogebry** [comment]
The "new hotness" here is to use collectd to publish metrics to CW.  It's super handy, ping me if you want more info.  I don't have the links handy right now, but it's pretty easy to find.
