### ISSUE TITLE
Setting Slots per Host

### ISSUE THREAD

**Issue by cancan101** [awslabs/cfncluster#36]
There does not appear to be any setting for controlling the number of slots available on a host (aka computer node).

**Comment by dougalb** [comment]
What is the reason for wanting to change the # of slots per instance versus the default which is the number of vCPUs?

**Comment by cancan101** [comment]
If I am running a GPU-requiring process that saturates the GPU, I would like to set the number of slots=number of GPUs on the instance. This is by far the most effective / simplest way of enforcing this resource limitation.

**Comment by johnbot1** [comment]
It would be nice to have as I have users that can't or won't modify their DRMAA code to use all available slots per compute instance but I also see reasoning for not adding additional variables that can already be handled on the SGE/postconfig level. I did this by setting my scaling to add a single host per single job then running then setting the following. 

```
qconf -arqs host-slots

{
Name         host-slots
description  restrict slots
enabled      TRUE
limit        hosts {@allhosts} to slots=1
}
```

It appears to be working for me so far.

**Comment by dougalb** [comment]
Experimental support for this on SGE, Openlava and Torque has been added to cfncluster-1.2.1. You can pass an additional setting using the extra_json parameter, which will enable you to set the number of slots per instances to `vpcus`, `cores`, or a number. For example, if you want to set the number of slots per instance to be only the number of cores, you could set the following in your config:

```
[cluster default]
...
extra_json = { "cfncluster" : { "cfn_scheduler_slots" : "cores" } }
...
```

If you wanted to see the number of slots per instance to only one, you could set the following in your config:

```
[cluster default]
...
extra_json = { "cfncluster" : { "cfn_scheduler_slots" : "1" } }
...
```
