### ISSUE TITLE
Attache an Elastic IP to Master

### ISSUE THREAD

**Issue by mukulagrawal78** [awslabs/cfncluster#368]
Folks: A quick question. Is there any parameter in configuration file or in the template file that allows me to specify an existing elastic IP for the master node?

**Comment by lukeseawalker** [comment]
This is not currently possible through cfncluster. The elastic IP is set into the cloudformation template [here](https://github.com/awslabs/cfncluster/blob/13c44e7df42c6b452375f3e09072402c8f518f20/cloudformation/cfncluster.cfn.json#L3938). Changing it requires changing the template. You can have a look at the cloudformation doc [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-eip-association.html)

**Comment by mukulagrawal78** [comment]
Thanks. I am doing all this through automated scripts. Is there a way to override values set in template without uploading new template to S3 every time I want to launch a cluster with new EIP for master?

**Comment by lukeseawalker** [comment]
Hi,
the list you can override is [here](https://github.com/awslabs/cfncluster/blob/13c44e7df42c6b452375f3e09072402c8f518f20/cloudformation/cfncluster.cfn.json#L703-L1071)

You can do for example
`create mycluster -p '{ "ScalingAdjustment" : "4" }'`

L
