### ISSUE TITLE
Cluster creating hosts file problem

### ISSUE THREAD

**Issue by etiennebourgeois** [awslabs/cfncluster#369]
Here are the symptoms I am getting:
•	When I ssh to the master node and run qhost, I see the hosts name, but all other columns are “-“
•	When I do qstat -f the jobs I submit are all in the Pending state (qw)

I found a workaround, but it is not elegant, and it seems like it might be a bug, but I'm not sure.

In the Compute node's hosts file, there is an entry for itself.
 
If I remove the hosts file entry, and add an entry for the master node,  then the install_execd process succeeds and the compute node can talk to the master node and run jobs.
 
To work around it, I created a post_install script that seems to work most of the time, but is not really elegant.

Is there a better way to address this issue, am I missing anything?

Here is my post_install script in case you are interested.
[post_install.txt](https://github.com/awslabs/cfncluster/files/2009672/post_install.txt)

**Comment by lukeseawalker** [comment]
Hi,
from what you are describing, it sounds like a network problem: your compute nodes are not able to resolve the master unless you add it into the hosts file.
Can you please do the following:
- verify you are using the latest cfncluster version, `cfncluster version`
- send the cfncluster config, please remove sensible info like AWS keys, if any
- send the output of `aws ec2 describe-vpc-attribute --vpc-id <your-vpc-id> --attribute enableDnsSupport --region=<your-region>`
- send the output of `aws ec2 describe-vpc-attribute --vpc-id <your-vpc-id> --attribute enableDnsHostnames --region=<your-region>`
- send the content of `/etc/resolv.conf` for the compute node

**Comment by etiennebourgeois** [comment]
Hi, Thanks for you help!!

Here are the details you asked for:

- cfncluster version 1.4.2

- [cfncluster.config.txt](https://github.com/awslabs/cfncluster/files/2013542/cfncluster.config.txt)

- EnableDnsSupport attribute:

`{
    "VpcId": "vpc-f1340c98",
    "EnableDnsSupport": {
        "Value": true
    }
}`

- EnableDnsHostnames attribute:

`{
    "VpcId": "vpc-f1340c98",
    "EnableDnsHostnames": {
        "Value": true
    }
}`

- [resolv.conf.txt](https://github.com/awslabs/cfncluster/files/2013543/resolv.conf.txt)

If you need further details, please let me know!

**Comment by lukeseawalker** [comment]
yes, can you provide the output of 
`aws ec2 describe-vpcs --vpc-ids vpc-f1340c98 --region=us-east-1`

thanks

**Comment by etiennebourgeois** [comment]
Here you go:
`{
    "Vpcs": [
        {
            "VpcId": "vpc-f1340c98",
            "InstanceTenancy": "default",
            "Tags": [
                {
                    "Value": "default-vpc",
                    "Key": "Name"
                }
            ],
            "CidrBlockAssociationSet": [
                {
                    "AssociationId": "vpc-cidr-assoc-cf7bbea6",
                    "CidrBlock": "192.168.0.0/21",
                    "CidrBlockState": {
                        "State": "associated"
                    }
                }
            ],
            "State": "available",
            "DhcpOptionsId": "dopt-01def845f833d564c",
            "CidrBlock": "192.168.0.0/21",
            "IsDefault": false
        }
    ]
}
`

**Comment by etiennebourgeois** [comment]
No I am not making changes to the resolve.conf file. We are however running
our own DNS servers, so maybe that is why.

**Comment by sean-smith** [comment]
@etiennebourgeois your DNS server needs to resolve the first part of the internal hostname i.e. `ip-172-31-56-87` if it doesn't do this, the scheduler can't communicate with the compute nodes.

See https://github.com/awslabs/cfncluster-node/blob/develop/sqswatcher/sqswatcher.py#L146 for where it's getting the hostname.

Can you run `dig ip-172-31-19-212` where the hostname is the master and you're running this command on one of the compute nodes.

**Comment by etiennebourgeois** [comment]
Here is the dig output:

; <<>> DiG 9.9.5-3ubuntu0.16-Ubuntu <<>> ip-192-168-1-39
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 8040
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;ip-192-168-1-39.               IN      A

;; Query time: 0 msec
;; SERVER: 192.168.7.5#53(192.168.7.5)
;; WHEN: Wed May 23 19:17:49 UTC 2018
;; MSG SIZE  rcvd: 44

**Comment by lukeseawalker** [comment]
@etiennebourgeois you should have a look at this thread https://forums.aws.amazon.com/thread.jspa?threadID=258743&tstart=0

**Comment by etiennebourgeois** [comment]
Thank @lukeseawalker and @sean-smith for the help. It is our DNS setup that is the issue.
