### ISSUE TITLE
Upgrade SGE to 8.1.1

### ISSUE THREAD

**Issue by cancan101** [awslabs/cfncluster#37]
http://arc.liv.ac.uk/repos/darcs/sge/NEWS

**Comment by dougalb** [comment]
CfnCluster uses SGE 8.1.8, which is the latest.

**Comment by cancan101** [comment]
Shoot. That should have said 8.1.8. 
Etiher way looks like that upgrade did not make the notes: https://github.com/awslabs/cfncluster/blob/master/CHANGELOG.rst#0017

**Comment by dougalb** [comment]
Sorry, not sure why that got missed. As we move to Chef for AMI creation and provisioning, you can easily check the versions here https://github.com/awslabs/cfncluster-cookbook/blob/develop/attributes/default.rb
