### ISSUE TITLE
question on post install args order, Is $1 name of the script?

### ISSUE THREAD

**Issue by adavanisanti** [awslabs/cfncluster#370]
I have the following post install script with args as follows:

```
post_install = <script_name>
post_install_args = "hello" "world" "cfncluster"
```

```
#!/bin/bash

. /etc/cfncluster/cfnconfig

case ${cfn_node_type} in
MasterServer)
    echo "I am the master" >> /home/ubuntu/master.txt
    echo $1 >> /home/ubuntu/master.txt
    echo $2 >> /home/ubuntu/master.txt
    ;;
ComputeFleet)
    echo "I am a compute node" >> /tmp/compute.txt
    ;;
esac

exit 0
```

My `master.txt` file on the master node is as follows:

```
I am the master
s3://rocketml-dev/scripts/post_install_script.sh
hello
```

Looks like `$1` is the script name followed by other args. Is this expected? Shouldn't `$0` be the script name?

Thanks
Santi

**Comment by sean-smith** [comment]
`$0` is a bash variable that refers to the filename which is different than the s3 uri provided in the config. The script that fetches the s3 file sets`$1` to be the s3 uri or url. The remaining parameters are set to the args that you pass. 

```bash
function download_run (){
    url=$1
    scheme=$(echo "${url}"| cut -d: -f1)
    tmpfile=$(mktemp)
    trap "/bin/rm $tmpfile" RETURN
    if [ "${scheme}" == "s3" ]; then
      aws --region ${cfn_region} s3 cp ${url} - > $tmpfile || return 1
    else
      wget -qO- ${url} > $tmpfile || return 1
    fi
    chmod +x $tmpfile || return 1
    $tmpfile $@ || return 1
}
```
See the file https://github.com/awslabs/cfncluster-cookbook/blob/9f53f9f1e1eebf55dfa95f0cdeb6ee4651fc56eb/files/default/fetch_and_run for more context.

Perhaps adding some documentation explaining this behavior would help?

**Comment by adavanisanti** [comment]
Yes, some documentation would definitely help. Thanks for the clarification.
