### ISSUE TITLE
Any Example Job?

### ISSUE THREAD

**Issue by mukulagrawal78** [awslabs/cfncluster#373]
Is there any scientific software and example scripts pre-installed on AMI that can be used to run and test some example cluster jobs?

**Comment by sean-smith** [comment]
No, unfortunately there's no scientific apps pre-installed.

I highly recommend you look at https://spack.io/ (hpc package manager) and for a general getting started guide there's https://cfncluster.readthedocs.io/en/latest/hello_world.html

Here's an example with Lammps (http://lammps.sandia.gov/):

```
# install lammps
module load mpi/openmpi-x86_64
cd /shared
git clone https://github.com/lammps/lammps
cd lammps/src
make mpi

# run it
mpirun -np 8 ./lmp_mpi -in ../bench/in.lj
```
(See https://github.com/lammps/lammps/blob/master/bench/README for info on lammps benchmarks)

Now create a file `~/lammps.sh` with the following:

```
#!/bin/bash
#$ -pe mpi 8
#$ -cwd

module load module load mpi/openmpi-x86_64
mpirun -np 8 /shared/lammps/src/lmp_mpi -in /shared/lammps/bench/in.lj
```

And run it:
```
qsub lammps.sh
sleep 2
qstat 
```

That example builds lammps with mpi support, runs it across 8 cores and finally shows you how to schedule it with sge. The output is contained in `lammps.sh.o*`.

**Comment by sean-smith** [comment]
Wanted to clarify, I'm installing from source in this example, however I recommend you install spack as it makes it really easy to install and manage applications.

**Comment by mukulagrawal78** [comment]
Thanks @sean-smith !
