### ISSUE TITLE
Cannot SSH into Compute Node

### ISSUE THREAD

**Issue by mukulagrawal78** [awslabs/cfncluster#378]
I can launch cluster fine. 
I can ssh into master node and submit job in queue. They are executing fine.
Everything seems to work good but I cannot ssh into compute nodes.
On AWS console, it shows that security group has all protocols open on all ports for incoming traffic.
It also shows the correct key that I am using.
I cant under why it is not letting me in then?
Any guidance?

**Comment by mukulagrawal78** [comment]
No worries I figured this out. Didn't realize that there are security groups attached.

**Comment by sean-smith** [comment]
Can you elaborate on what you did for the benefit of others? 

Generally you need to ssh into the master node then from there ssh into the compute nodes. See https://cfncluster.readthedocs.io/en/latest/networking.html for info on the networking setup.

**Comment by mukulagrawal78** [comment]
Traffic is open for all protocols and all ports but the compute nodes security group allows incoming traffic only from within the security group only. I had ignored/missed  the restriction on incoming source at first. I attached another security group that allowed incoming traffic from my host.
