### ISSUE TITLE
ssh config and master node script

### ISSUE THREAD

**Issue by mukulagrawal78** [awslabs/cfncluster#379]
I have two questions:

1/ I am building my custom AMI and I need to add more stuff to ssh config files. Seems like this breaks cfncluster. Is there a solution to this? Can I alter chef scripts to concatenate to what I have in ssh config files?

2/ Is there a way to run some post install script only on Master?

**Comment by sean-smith** [comment]
There's a file `/etc/cfncluster/cfnconfig` that contains the node type. Use that info to run the script just on Master:

	#!/bin/bash

	. /etc/cfncluster/cfnconfig

	case ${cfn_node_type} in
	MasterServer)
	    echo "I am the master"
	    ;;
	ComputeFleet)
	    echo "I am a compute node"
	    ;;
	esac

	exit 0

Can you elaborate on what in the ssh config is breaking cfncluster?

**Comment by mukulagrawal78** [comment]
Thanks @sean-smith 
Just to clarify, can I use PostInstallScript and in that script pickup the variable ${cfn_node_type} and then doa ctions accordingly?

In the AMI, in the ssh config file, I have added several HOST and associate keys to be able to automatically ssh into various machines through scripts. Once I do this in AMI and then launch cfncluster, master node comes up but it never finishes full setup and then ROLLBACK gets kicked in.

**Comment by sean-smith** [comment]
What's probably going on is you've created the `~/.ssh/known_hosts` with the ami. Then when [cfncluster-cookbook #L150](https://github.com/awslabs/cfncluster-cookbook/blob/b033083ffc088a4921c6a2ccd94a5c93fdd86694/recipes/_master_base_config.rb#L150) runs it won't do a `ssh-keyscan` which then doesn't add the other nodes in the cluster to the `known_hosts` file. Then when the nodes try to mount the file system (or something else), they're unable to do so.

I suggest you use a post_install script or pre_install script if all you're doing is modifying ssh config. See https://cfncluster.readthedocs.io/en/latest/pre_post_install.html

**Comment by mukulagrawal78** [comment]
@sean-smith: Looking for some guidance on following. Do you foresee any issues with cfn if I concatenate my own User data to cfn's User data in the CloudFormation template? My userdata will do 3 main things on MastetNode only: (1) I want to use slurm for managing some administrative workloads and use sge for regular job queue management. So I will do my own configuration of slurm and run some batch scripts through it. (2) I will add some host definitions and pem keys to ssh config file. (3) change user to a non priviledged user. And change the working folder.
