### ISSUE TITLE
Document why enableDnsHostnames is required

### ISSUE THREAD

**Issue by cancan101** [awslabs/cfncluster#38]
StarCluster does not require this settings.

What are the issue with turning this on?

**Comment by dougalb** [comment]
CfnCluster by default uses VPC DNS for host resolution. This is required for SGE and other services to operate correctly. They are enabled by default in a Default VPC or when creating a new VPC using the wizard. Details of the expected settings are highlighted here: http://cfncluster.readthedocs.org/en/latest/getting_started.html#configuring-cfncluster
