### ISSUE TITLE
Simultaneous Clusters

### ISSUE THREAD

**Issue by mukulagrawal78** [awslabs/cfncluster#385]
Can I have two simultaneously running clusters started from same AMI?
If not, then what would I need to do to get this possibility?

**Comment by bwbarrett** [comment]
I see you closed the ticket, but just to close the loop, yes, you can start as many clusters as you want from the same AMI.  Each must have a unique cluster name (that's the key CfnCluster uses to keep resources independent).  And, of course, as your resource utilization grows, you may have to request increases in various limits (usually EC2 instance limits is the first you'll need to increase).
