### ISSUE TITLE
Determining if I'm on the Master or Compute nodes in scripts

### ISSUE THREAD

**Issue by hellmersjl3ds** [awslabs/cfncluster#386]
Is there a way to determine in a script that I want to run for pre or post install if it's running on the master or compute node?

If not a couple of options
1) Create an environment variable on the nodes that indicates which one it is.
2) Add seperate parameters in the CfnCluster config file to indicate different scripts to use

**Comment by mauri-melato** [comment]
In the execution context of the pre/post install scripts you should have the `cfn_node_type` environment variable whose possible values are `MasterServer` and `ComputeFleet` for the master and compute node respectively.

A usage example
```
case "${cfn_node_type}" in
  MasterServer)
    # code to run on the master node
  ;;
  ComputeFleet)
    # code to run on the compute node
  ;;
esac
```

**Comment by hellmersjl3ds** [comment]
Well when I use this type of thing manually (by setting the environment variables and executing) on an already created master and compute node it works, but it doesn't work in my post install script.  in the cfn-init-cmd.log I see messages.  

    2018-05-25 20:21:27,696 P2217 [INFO]    Configuring Users...
    2018-05-25 20:21:27,696 P2217 [INFO]    No valid Node Type.
    2018-05-25 20:21:27,696 P2217 [INFO]    ...User Configuration complete

These are coming from the following statements in my post install script

	echo "Configuring Users..."

	case "${cfn_node_type}" in
	  MasterServer)
			echo "On Master Node"
			groupadd --force --gid 1983 Scitegic-Users
			useradd --base-dir /home --gid 1983 --create-home --uid 1983 scitegicuser
	  ;;
	  ComputeFleet)
		echo "On Compute Node"
		useradd --no-create-home --uid 1983 scitegicuser
	  ;;
	  *)
		echo "No valid Node Type"
	esac

	echo "...User Configuration complete."

**Comment by dougalb** [comment]
You must source the config into your script. For example see
https://github.com/awslabs/cfncluster-cookbook/blob/develop/files/default/compute_ready

**Comment by hellmersjl3ds** [comment]
Thanks that did the trick.  BTW, is the /etc/cfncluster/cfnconfig available when the pre-install script is running?

**Comment by enricou** [comment]
@hellmersjl3ds: yes it is available because the file is created in the prep env recipe https://github.com/awslabs/cfncluster-cookbook/blob/develop/recipes/_prep_env.rb#L29 that is executed before the pre/post install steps: https://github.com/awslabs/cfncluster/blob/develop/cloudformation/cfncluster.cfn.json#L2768 .
