### ISSUE TITLE
ami id support and cfn setup

### ISSUE THREAD

**Issue by mkaja** [awslabs/cfncluster#388]
1 . I had created a cfncluster on may 15 and it has ami-id ami-a192c8b7 in us-east-1 region - is this still supported or do i need to change ? 

2. a)we create cfncluster with one master/one compute nodes in config file and once its up we will ssh to master-node (we use SLURM) to modify the parameters in /opt/slurm/etc/slurm.conf like 
SelectType=select/cons_res
SelectTypeParameters=CR_CPU_Memory
FastSchedule=1
TaskPlugin=task/cgroup
add at last : CPUs=40 SocketsPerBoard=2 CoresPerSocket=10 ThreadsPerCore=2 RealMemory=161187 TmpDisk=20016 CoreSpecCount=2 State=UNKNOWN

b) add cgroup.conf to /opt/slurm/etc/ location 

c) restart slurm

following above steps was fine before 6 months but this time we had lot of issues -is there anything we need to change in setup- Please advise

**Comment by sean-smith** [comment]
Hi,

1. We haven't done a release since May 15th, 2018 so as long as your version of cfncluster is up to date, that's the latest AMI. Run `cfncluster version` to confirm you're running the latest version, `1.4.2`.

2. I don't know what your issues are? Can you explain the behavior difference between now and then? Also are you doing this manually or in a post install script?

**Comment by mkaja** [comment]
1. cfncluster version
1.3.2
2. a.Jobs are getting hung in CG mode ( snifo) 
b.and  error: Nodes not responding I see in /var/log/slurm*.log
c. [2018-05-18T] error: Node ip-appears to have a different slurm.conf than the slurmctld.  This could cause issues with communication and functionality.  Please review both files and make sure they are the same.  If this is expected ignore, and set DebugFlags=NO_CONF_HASH in your slurm.conf.

3. the  steps which i mentioned slurm.conf , cgroup.conf and restart slurm - I am doing manually

**Comment by Jspujol** [comment]
Hi,

I am having troubles understanding what kind of AMI are being launched by default using cfncluster. I would like to launch amis with preinstalled software like Deep Learning AMI (Ubuntu) Version 9.0, is that feasible?

Thanks!

**Comment by mkaja** [comment]
@Jspujol  Pls refer https://github.com/awslabs/cfncluster/blob/master/amis.txt fir the ami details launched using default cfncluster.... if you want to install deep learning refer http://cfncluster.readthedocs.io/en/latest/ami_customization.html
