### ISSUE TITLE
Option to Auto-Create the Placement Group

### ISSUE THREAD

**Issue by cancan101** [awslabs/cfncluster#39]
Right now that does not seem to be the case: http://cfncluster.readthedocs.org/en/latest/configuration.html#placement-group where as for StarCluster, the placement group is created automatically for the cluster.

**Comment by dougalb** [comment]
CfnCluster leverages CloudFormation for resource creation and currently it does not support creating a Placement Group resource. As soon as that is supported, it will be added.

**Comment by cancan101** [comment]
I figured as much: https://forums.aws.amazon.com/thread.jspa?threadID=195355&tstart=0

**Comment by cancan101** [comment]
Any updates on this?

**Comment by dougalb** [comment]
Hi,

The code is written and we'll be pushing shortly.

Kind regards,

Dougal

**Comment by dougalb** [comment]
Released in 1.1
