### ISSUE TITLE
Update configuration.html to include mention of supported ubuntu1604 for base_os

### ISSUE THREAD

**Issue by chrisdag** [awslabs/cfncluster#393]
The live version of documentation does not mention that 'ubuntu1604' is a valid option for parameter base_os = 

Source: https://cfncluster.readthedocs.io/en/latest/configuration.html#base-os

This doc issue is fixed in the developer branch but since I think the released version of cfncluster supports 16.04 LTS then the published/live documentation should mention that as well.

**Comment by enricou** [comment]
@chrisdag yes, the _develop_ branch will be merged in the *master* one as soon as the new version of CfnCluster will be released.

**Comment by enricou** [comment]
Doc updated: https://cfncluster.readthedocs.io/en/latest/configuration.html#base-os

**Comment by kevinayres** [comment]
I am experiencing the same issue trying to add SLES 12 sp3. I leveraged the develop branch and modified every reference I could find for base_os. See Fork kevinayres/aws-parallelcluster
Can you tell me what I'm missing please? I'm also referencing it via local ~/.parallelcluster/config

[aws]
aws_region_name = us-west-2
aws_access_key_id = AKIAIxxxXHDQ
aws_secret_access_key = hacBUjwxZNxxxxtM/Utjprm

[cluster default]
vpc_settings = public
key_name = pup
base_os = sles1203
#custom_ami = ami-00c75ff88724f9e77

[vpc public]
master_subnet_id = subnet-5a2a2800
vpc_id = vpc-97d87eef

[global]
update_check = true
sanity_check = true
cluster_template = default

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}
