### ISSUE TITLE
Communications between nodes really slow

### ISSUE THREAD

**Issue by etiennebourgeois** [awslabs/cfncluster#405]
Hi,

We are running a cluster and the performance is not what we need. We are finding that the bottleneck appears to be communication between nodes. Does anyone have any suggestion on how we could improve this?

Thanks,
Etienne

**Comment by lukeseawalker** [comment]
Hi Etienne,
placement group could help. You can find more information on what is a placement group [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/placement-groups.html). 

You can configure the cluster to use your own placement group with
`placement_group = <your_placement_group_name>`
or let CfnCluster create a placement group with the "cluster" strategy with
`placement_group = DYNAMIC`

More configuration info [here](https://cfncluster.readthedocs.io/en/latest/configuration.html#placement-group).

Regards,
L

**Comment by lukeseawalker** [comment]
Please also consider to choose an instance type that supports enhanced networking. For more information, see [Enhanced Networking](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html).

L

**Comment by enricou** [comment]
Hi @etiennebourgeois , just to complete @lukeseawalker 's suggestions I add that bandwidth scales with instance size: https://aws.amazon.com/it/blogs/aws/now-available-compute-intensive-c5-instances-for-amazon-ec2/

These three hints should cover the whole range of possibilities to improve network communication.

**Comment by etiennebourgeois** [comment]
Thanks for the advice @lukeseawalker and @enricou. I'm going to implement those this week.
