### ISSUE TITLE
Upgrade Python to 2.7

### ISSUE THREAD

**Issue by cancan101** [awslabs/cfncluster#41]
Currently default AMI has 2.6.6

**Comment by kdaily** [comment]
I think this ancient version is required by yum; it cannot be removed from the system. I was able to install 2.7 and 3.3, which can be switched using modules or virtualenv.

**Comment by cancan101** [comment]
Thanks for the pointer. I am trying out https://github.com/yyuu/pyenv.

**Comment by dougalb** [comment]
The current version of CfnCluster use CentOS6 as the base OS. Python 2.6.6 is the OS default and cannot be changed without significant impact to the OS. You can easily add other versions and leverage virtaulenv to switch between them.
