### ISSUE TITLE
Question: Scaling settings and maintain_initial_size

### ISSUE THREAD

**Issue by adavanisanti** [awslabs/cfncluster#438]
Quick clarification: All the scaling configurations are relevant when I set `maintain_initial_size = true` and when `max_queue_size > initial_queue_size`.  http://cfncluster.readthedocs.io/en/latest/configuration.html#scaling

Is that correct?

If not, if I set `maintain_initial_size = true`, when would "auto Scaling group to scale down to 0 members, so resources will not sit idle when they aren’t needed." happen?

Thanks
Santi

**Comment by hellmersjl3ds** [comment]
I'm pretty sure that if maintaining initial size is set to true, and our initial size is 0 then it would scale down to zero.  In fact I've seen that happen.

Keep in mind that if you have zero compute nodes, it will take awhile for one compute node to come online, which may cause the Queuing system or your application to throw an error.

**Comment by sean-smith** [comment]
1. The scaling settings are always observed when scaling
2. Depends on `initial_queue_size`, it will scale down to the initial queue size when `maintain_initial_size = true`. Note `initial_queue_size` defaults to 2.

**Comment by adavanisanti** [comment]
@hellmersjl3ds That is correct. I have noticed my application throwing an error when the total number of compute nodes went to zero. Trying to figure out how to handle this case without keeping too many compute nodes up and running the entire time.

**Comment by sean-smith** [comment]
yes

**Comment by adavanisanti** [comment]
I saw an error in my application when I set `maintain_initial_size = false` and `initial_queue_size = 2`. Total compute nodes available went to zero.

**Comment by sean-smith** [comment]
That's by design https://cfncluster.readthedocs.io/en/latest/autoscaling.html

What I'm more interested in is why this causes an error in your application?
