### ISSUE TITLE
cfncluster can't attach an EBS volume formatted with ext3

### ISSUE THREAD

**Issue by mark-cresset** [awslabs/cfncluster#440]
If I try to start a cluster, and attach a specified volume, then the cluster fails to start if the EBS volume is formatted as ext3.

Looking at the log on the failed master, it looks like the chef recipe ends up with something along the lines of 

fstype="ex2\" TYPE=\"ext3"

so presumably the failure is in whichever piece of code tries to work out the fs type - I'm not familiar enough with chef to easily debug this further.

 If the EBS volume is formatted as ext4 it works.

**Comment by sean-smith** [comment]
The relevant bit of code is here: https://github.com/awslabs/cfncluster-cookbook/blob/537041b3e51a77d4e9690b4b5989e744aa62a6c3/libraries/helpers.rb#L30

Looks like it's not picking up your file system type. Can you post the ebs section of your config file and the result of running `blkid -c /dev/null /dev/sdb`? Note `/dev/sdb` is the full path to the ebs volume that gets mounted
