### ISSUE TITLE
more nodes are launched than the requested ones

### ISSUE THREAD

**Issue by jindongw** [awslabs/cfncluster#446]
I submitted a job requesting 3 nodes on EC2/c5.18xlarge. It ended up with 10 nodes launched. 7 nodes were idling. I am wondering how to avoid this over-launch issue.

**Comment by sean-smith** [comment]
There's two scaling thresholds, first threshold is at 1 and it'll launch 1 new node every 2 minutes. Second threshold is at 200 (vcpu's requested), this causes 10 new nodes to launch.

You're hitting the second scaling threshold. The requested number of vcpu's (3 * 72 = 216) is greater than the default threshold of 200 so it launches 10 nodes.

You can change these thresholds in your config file under the scaling settings: https://cfncluster.readthedocs.io/en/latest/configuration.html#scaling-threshold2

You probably want something similar to this:

```
[scaling custom]
scaling_threshold = 1
scaling_adjustment = 1
scaling_threshold2 = 216
scaling_adjustment2 = 3
```
This launches 1 node when you request more than 1 vcpu and 3 nodes when you request >= 216 vcpu's.

**Comment by jindongw** [comment]
Thanks for your pin-to-point comment, Sean.
