### ISSUE TITLE
Cloud Watch Metrics not Cleaned up When Stack Deleted

### ISSUE THREAD

**Issue by cancan101** [awslabs/cfncluster#45]
![image](https://cloud.githubusercontent.com/assets/51059/8736169/3a3ed060-2be4-11e5-9d30-fca1acf5322e.png)

**Comment by dougalb** [comment]
Amazon CloudWatch Metrics are automatically deleted after 14 days. There is no delete API call and customers have up to 10 free custom metrics.

http://aws.amazon.com/cloudwatch/faqs/
http://aws.amazon.com/cloudwatch/pricing/
