### ISSUE TITLE
postinstallscript cannot open DISPLAY

### ISSUE THREAD

**Issue by mukulagrawal78** [awslabs/cfncluster#452]
I am not entirely sure how postinstalscript is executed by cfncluster. For me postinstall script is complaining that it cannot open DISPLAY.

So I have a VNC server running on master node on :50. This is done through userData.
I can manually log into the master node and do
DISPLAY=:50 xterm
and it works just fine.

But if I use following post install script then I get an error saying cannot open display %s.
Error is not fatal. cfncluster goes to completion and I have proper cluster working.
Any pointers/help is highly appreciated!

```
#!/bin/bash

. /etc/cfncluster/cfnconfig

case ${cfn_node_type} in
MasterServer)
    echo "I am the master" >> /tmp/master.txt

DISPLAY=:50 xlogo
	
    ;;
ComputeFleet)
    echo "I am a compute node" >> /tmp/compute.txt	
    ;;
*)
    ;;
esac

```

**Comment by mukulagrawal78** [comment]
I made some changes and now I am starting vnc server in post install script itself.
Something very strange is happening. If I look at the cfn-init.log then the logs are stuck at following lines:

2018-07-16 10:26:04,125 [DEBUG] Running command runpostinstall
2018-07-16 10:26:04,125 [DEBUG] No test for command runpostinstall

Master comes up but compute nodes never come up.
Then I log into master node and I manually execute fetch_and_run. No errors are reported . 
Then I see cfn-init.log start to show more logs and all compute nodes also comeup. I get DISPLAY working and everything else is working as expected.

Any idea what is happening here?

**Comment by mukulagrawal78** [comment]
Can you please tell me how is the successful completion of fetch_and_run reported back so that rest of rest of cfnclsuter can proceed? 

Where should I start looking? This is very puzzling. I am doing lots of echo's inside post install script ... all of them are showing up properly including the one in last line. Still cfncluster creation does not proceed further and is stuck. If I run the fetch_and_run manually then it starts to move forward successfully.
Seems to me issues related to whether fetch_and_run is being run from a log-in shell versus run by cfnclsuter (possible in dettached shell ??).

**Comment by lukeseawalker** [comment]
Hi,
the fetch_and_run execute the post-install script which should terminate with an exit code of 0 in order to signal a success back to the fetch_and_run.
Are you sure that your post-install script is terminating?

**Comment by mukulagrawal78** [comment]
@lukeseawalker, 

Yes, at least I can confirm that by running it manually. There is an explicit exit 0 at the end as well. 
Few strange things,

1/ if I execute fetch and run manually then cluster formation proceeds. Fetch and run is pulling exact same script from s3. Nt sure why it gets stuck when started automatically by cfncluster.

2/ If I comment out the vnc server command then also things work fine.

3/ vnc server does get started properly even in usual process when cfn is stuck at postinstall step. All commands after that are also executed. 

Does putting a daemon process is background in the script can cause issues?

**Comment by lukeseawalker** [comment]
Hi,
I'd compare the environment between the case "started by cfncluster" vs "started manually".
Is the X server running before starting the vnc server?
I'd try to execute the vnc server command in a subshell ( vncserver [...] ) or even with sh -c "vncserver [...]" to see if there are any difference.
I'd try to start the vnc server as a service (e.g. init.d script) instead using directly the command.

**Comment by mukulagrawal78** [comment]
@lukeseawalker , can you tell me parent of the fetch_and_run ... which program calls that script?

**Comment by sean-smith** [comment]
It's run from the UserData in the cloudformation init: https://github.com/awslabs/cfncluster/blob/develop/cloudformation/cfncluster.cfn.json#L2798

It's run as root and needs to terminate before the instance is added to the scheduler (and the cloudformation stack goes to `CREATE_COMPLETE`).
