### ISSUE TITLE
Compute node notification

### ISSUE THREAD

**Issue by mukulagrawal78** [awslabs/cfncluster#463]
Is there a notification generated that I can capture though API or CLI when a new compute node is added to the cluster or when an existing compute node is terminated? Or is there a list of all nodes somewhere that I can probe?

**Comment by dougalb** [comment]
It is also stored in DynamoDB

**Comment by mukulagrawal78** [comment]
Thanks @sean-smith and @dougalb .
Can I look at DB schema/tables somewhere?

**Comment by sean-smith** [comment]
in the dynamo console: https://console.aws.amazon.com/dynamodb/home
