### ISSUE TITLE
submitted job not running

### ISSUE THREAD

**Issue by jindongw** [awslabs/cfncluster#470]
I submitted a job requesting 1 node of c5.x18large. When I use "aws autoscaling describe-auto-scaling-instances", it shows that one instance is "HEALTHY" and "InService". When I use "qhost", it shows none computing node is activated. "qstat" always shows "qw". After a few minutes I use "aws autoscaling describe-auto-scaling-instances" to check again, it shows that two instances are "HEALTHY" and "InService". The job is still in queue.

**Comment by fnubalaj** [comment]
Could you please see the sqswatcher log to check if there are any errors logged. Could you please post the contents of /var/log/sqswatcher

**Comment by jindongw** [comment]
I didn't see anything for this issue in /var/log/sqswatcher. There are only some old error messages.

**Comment by fnubalaj** [comment]
Could you please post the contents of that file? 

In addition, to make sure that the ec2 instances are being added to the scheduler, could you please post the output of qhost?

What is the desired and max capacity in the cfncluster config set to?

Thanks
Balaji

**Comment by jindongw** [comment]
The desired capacity is 0.
The max size is 50.

**Comment by fnubalaj** [comment]
So, it seems evident that the instances are not being added to the queue either due to permission issues or because the queue does not exist

Could you please post the entire contents of cfn-init.log, cloud-init.log, cfn-init-cmd.log and sqswatcher?

Also, please post the output of

aws sqs list-queues

Thanks
Balaji

**Comment by jindongw** [comment]
We updated cfncluster from v1.4 to v1.5 and created a new cluster. The new cluster works now.
