### ISSUE TITLE
why did cfncluster drop "--config" support and is sanity_check broken in 1.5.2? 

### ISSUE THREAD

**Issue by chrisdag** [awslabs/cfncluster#472]
Seeing some issues with 1.5.2

The "--config" and "-C" arguments are gone! Is this by intent? There is no way now to specify a unique config file when launching a cluster? This seems odd :) I'd prefer not to maintain a massive .cfncluster/config file that lists many clusters run by many organizations. Would really like the ability to pass in a unique config file if possible

And sanity checking seems off in 1.5.2 as well; I keep getting:

> Beginning cluster creation for cluster: alk-use1-spot-gpu-hpc
IAM role error on user provided role cfnclusterRole: action sqs:DeleteMessage is implicitDeny
See https://cfncluster.readthedocs.io/en/latest/iam.html

Despite the fact that the IAM policy looks like:

>         {
            "Resource": [
                "arn:aws:sqs::ACCOUNTID:cfncluster-*"
            ],
            "Action": [
                "sqs:SendMessage",
                "sqs:ReceiveMessage",
                "sqs:ChangeMessageVisibility",
                "sqs:DeleteMessage",
                "sqs:GetQueueUrl"
            ],
            "Sid": "SQSQueue",
            "Effect": "Allow"
        }

The sanity check only seems to pass if those permissions are listed for the global "\*" resource rather than constrained by the ARN pattern containing "cfncluster-*.

**Comment by lukeseawalker** [comment]
Hi,
the flags are now specific for every subcommands, for example
```
cfncluster create -h
[...]
optional arguments:
  -h, --help            show this help message and exit
  --config CONFIG_FILE, -c CONFIG_FILE
                        specify a alternative config file
[...]
```

In your case I suppose you have just to move the "--config" after the subcommand, e.g. "create"

About the policy, the doc says

```
        {
            "Resource": [
                "arn:aws:sqs:<REGION>:<AWS ACCOUNT ID>:cfncluster-*"
            ],
[...]
```
Your custom policy doesn't have the <REGION> specified. Could you please add it and retry?

L
