### ISSUE TITLE
Config sanity error: AWS was not able to validate the provided access credentials

### ISSUE THREAD

**Issue by adavanisanti** [awslabs/cfncluster#476]
Hello All,

I am seeing this error `Config sanity error: AWS was not able to validate the provided access credentials` today morning. Everything was working until last night. Could you please help?

Thanks
Santi

**Comment by adavanisanti** [comment]
I have also tested with new access and secret keys. Running into the same error.

**Comment by sean-smith** [comment]
Did you upgrade the version of cfncluster recently?

**Comment by adavanisanti** [comment]
@sean-smith No, I have not upgraded the version. This problem resolved by itself without any changes on my end. I suspect that something happened on AWS for a few hours. I could not see any "T2" instances to start at the same time the above problem happened. I am not sure if they are related - just an observation.
