### ISSUE TITLE
A few additional IAM permissions needed for cfncluster deployer policy

### ISSUE THREAD

**Issue by chrisdag** [awslabs/cfncluster#478]
Suggested Fix for:

https://cfncluster.readthedocs.io/en/latest/iam.html

... this section in the policy for deploy user:

>       
            "Sid": "IAMModify",
            "Action": [
                "iam:PassRole",
                "iam:CreateRole",
                "iam:DeleteRole"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:iam::<AWS ACCOUNT ID>:role/<CFNCLUSTER EC2 ROLE NAME>"

Looks like the IAM set for the deployer user needs "iam:GetRole" in order to prevent this error on cluster creation:

> Beginning cluster creation for cluster: XXX-use1-prod-liggghts-hpc
Config sanity error: User: arn:aws:iam::XXX:user/svc_use1_rdapps_prod_cfncluster-deployer is not authorized to perform: iam:GetRole on resource: role cfnclusterRole

And it also looks like it's missing "iam:SimulatePrincipalPolicy" as well as I see this error:

> Config sanity error: User: arn:aws:iam::XXX:user/svc_use1_rdapps_prod_cfncluster-deployer is not authorized to perform: iam:SimulatePrincipalPolicy on resource: arn:aws:iam::XXX:role/cfnclusterRole

Suggested replacement text for IAMModify:

>         
            "Sid": "IAMModify",
            "Action": [
                "iam:PassRole",
                "iam:CreateRole",
                "iam:DeleteRole",
                "iam:GetRole",
                "iam:SimulatePrincipalPolicy"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:iam::<AWS ACCOUNT ID>:role/<CFNCLUSTER EC2 ROLE NAME>"

And finally I could not get past this sanity check error

> IAM role error on user provided role cfnclusterRole: action sqs:SendMessage is implicitDeny
See https://cfncluster.readthedocs.io/en/latest/iam.html

The IAM policy clearly allows sqs:SendMessage -- is there a chance that this particular sanity check test has a bug?  My policy looks like this now and there are no other SQS stanzas that should be inserting an implicit deny:

>        
            "Sid": "SQSAllow",
            "Action": [
                "sqs:CreateQueue",
                "sqs:SetQueueAttributes",
                "sqs:DeleteQueue",
                "sqs:SendMessage",
                "sqs:GetQueueAttributes"
            ],
            "Effect": "Allow",
            "Resource": "*"

**Comment by lukeseawalker** [comment]
Hi,
about the two missing policy, they are already included in the PR https://github.com/awslabs/cfncluster/pull/475, as a follow up of your ticket https://github.com/awslabs/cfncluster/issues/473.

About the "sqs:SendMessage" I think you are confusing the "CfnClusterInstancePolicy" with the "CfnClusterUserPolicy".

The "CfnClusterInstancePolicy is the policy associated to the EC2 instances through a custom role that could be configured via the config option "ec2_iam_role", see https://cfncluster.readthedocs.io/en/latest/configuration.html?highlight=ec2_iam_role. The sanity check will check if the custom configured policy is compliant to (only the relevant portion reported)
```
[...]
        {
            "Resource": [
                "arn:aws:sqs:<REGION>:<AWS ACCOUNT ID>:cfncluster-*"
            ],
            "Action": [
                "sqs:SendMessage",
                "sqs:ReceiveMessage",
                "sqs:ChangeMessageVisibility",
                "sqs:DeleteMessage",
                "sqs:GetQueueUrl"
            ],
            "Sid": "SQSQueue",
            "Effect": "Allow"
        },
[...]
```

Instead the "CfnClusterUserPolicy" is the policy associated to the user who want to create the cluster. There is no sanity check for this policy at the moment  (only the relevant portion reported)

```
[...]
        {
            "Sid": "SQSModify",
            "Action": [
                "sqs:CreateQueue",
                "sqs:SetQueueAttributes",
                "sqs:DeleteQueue"
            ],
            "Effect": "Allow",
            "Resource": "*"
        },
[...]
```

As you see the "sqs:SendMessage" should be present into the "CfnClusterInstancePolicy" and it is not necessary into the "CfnClusterUserPolicy", in which I suppose you are adding it.

L

**Comment by chrisdag** [comment]
Thanks Luca! 

I saw that error when deploying and thought it was IAM permission related on the deploy user but I just found the config_sanity.py script and it's pretty clear that sanity check is looking at the EC2 role:

>     if resource_type == 'EC2IAMRoleName':
        try:
            iam = boto3.client('iam', region_name=region,
                                aws_access_key_id=aws_access_key_id,
                                aws_secret_access_key=aws_secret_access_key)

            arn = iam.get_role(RoleName=resource_value).get('Role').get('Arn')
            accountid = boto3.client('sts').get_caller_identity().get('Account')

            iam_policy = [(['ec2:DescribeVolumes', 'ec2:AttachVolume', 'ec2:DescribeInstanceAttribute', 'ec2:DescribeInstanceStatus', 'ec2:DescribeInstances'], "*"),
                        (['dynamodb:ListTables'], "*"),
                        (['sqs:SendMessage', 'sqs:ReceiveMessage', 'sqs:ChangeMessageVisibility', 'sqs:DeleteMessage', 'sqs:GetQueueUrl'], "arn:aws:sqs:%s:%s:cfncluster-*" % (region, accountid)),
                        (['autoscaling:DescribeAutoScalingGroups', 'autoscaling:TerminateInstanceInAutoScalingGroup', 'autoscaling:SetDesiredCapacity'], "*"),
                        (['cloudwatch:PutMetricData'], "*"),
                        (['dynamodb:PutItem', 'dynamodb:Query', 'dynamodb:GetItem', 'dynamodb:DeleteItem', 'dynamodb:DescribeTable'], "arn:aws:dynamodb:%s:%s:table/cfncluster-*" % (region, accountid)),
                        (['sqs:ListQueues'], "*"),
                        (['logs:*'], "arn:aws:logs:*:*:*")]


Sorry for wasting your time :)

**Comment by lukeseawalker** [comment]
No prob at all,
glad that you solved.

L
