### ISSUE TITLE
cfncluster not worked in cn-north-1 but in Acceptable Values for AWS Region ID list

### ISSUE THREAD

**Issue by Allen2Git** [awslabs/cfncluster#479]
Hello all,

I've tested cfncluster in cn-north-1/cn-northwest-1 region but not worked. 
At beginning when using " cfncluster configure", cn-north-1 and cn-northwest-1 can be chose. But after I try to "cfncluster create" , it's shown 
```
Beginning cluster creation for cluster: cfntest
Creating stack named: cfncluster-cfntest
S3 error: The specified bucket does not exist
```
And I also find not cn-north-1 / cn-northwest-1 AMI in amis.txt.
Any updates I can do for solving this issues?

Thanks.

**Comment by sean-smith** [comment]
The chinese regions are not currently supported. I've marked this as a bug to remove the regions from being listed in `cfncluster configure` until they're supported. Thanks for pointing this out.
