### ISSUE TITLE
Support Adding more Values to /opt/cfncluster/cfnconfig

### ISSUE THREAD

**Issue by cancan101** [awslabs/cfncluster#48]
It appears the only way to pass in variables right now is `pre_install_args` and `post_install_args`. I suggest allowing the user to add more variables in `/opt/cfncluster/cfnconfig` which would be more akin 12 factor's use of environmental variables. 

In addition, consider sourcing  `/opt/cfncluster/cfnconfig` in either `/etc/bashrc`, or `/etc/profile`.

**Comment by dougalb** [comment]
In the upcoming chef changes, you will be able to pass custom JSON that will be exposed to Chef and in turn can be exposed in other places. 

CfnCluster is a framework, rather than an application. Pushing framework variables into the user environment may have adverse effects on user applications.

**Comment by dougalb** [comment]
You can know pass arbitrary JSON as part of the cfncluster configuration - http://cfncluster.readthedocs.org/en/develop/configuration.html#extra-json. This part of the CfnCluster 1.0 release and details of the beta are available here - https://forums.aws.amazon.com/ann.jspa?annID=3471.
