### ISSUE TITLE
Mount /opt/sge with sync flag

### ISSUE THREAD

**Issue by cancan101** [awslabs/cfncluster#49]
Consider [mounting the /opt/sge directory](https://github.com/awslabs/cfncluster/blob/4f634553e5054baf3e735b3ad907c9ac029ba5f7/bootstrap/src/scripts/sge/boot_as_compute#L46) with the `sync` flag so that output will stream back as it is created. For more discussion see: https://arc.liv.ac.uk/trac/SGE/ticket/1545 and the referenced SO tickets.

**Comment by dougalb** [comment]
It is typically not advised to mount NFS filesystem with sync as this can cause a significant amount of unneeded NFS traffic. CfnCluster simply uses the OS default for NFS, which is async. You can see this here https://github.com/awslabs/cfncluster/blob/master/bootstrap/src/scripts/sge/boot_as_compute#L46

**Comment by cancan101** [comment]
Ok. Is there any way to have the directory to which stdout is written on the compute nodes mounted using `sync` ?
