### ISSUE TITLE
Parameter ComputeInstanceType failed to satisfy constraint: Must be a valid EC2 instance type, with support for HVM.

### ISSUE THREAD

**Issue by karlvirgil** [awslabs/cfncluster#494]
I am trying to create a new cfncluster based on your tips, and am running into an weird error message
 
cfncluster create meredithk-efs2

Starting: meredithk-efs2
Parameter ComputeInstanceType failed to satisfy constraint: Must be a valid EC2 instance type, with support for HVM.
 
I’ve attached the config file.  
[config.txt](https://github.com/awslabs/cfncluster/files/2312694/config.txt)

The compute node instance types are the same ones I’ve used before (c5.18xlarge).  Why is it complaining that they are not supported?

**Comment by lukeseawalker** [comment]
Hi,
are you using the latest cfncluster version?
Please verify with
```
cfncluster version
```

L

**Comment by karlvirgil** [comment]
Seems the issue was my `awscli` was out of date. I assumed that when I upgraded `cfncluster` it would automatically upgrade `awscli`, but apparently not.  Running
`pip install awscli --upgrade --user`
seems to fix the problem.
