### ISSUE TITLE
Tracking compute VM nodes as they come and go away as part of autoscaling cfn stack

### ISSUE THREAD

**Issue by SunPj** [awslabs/cfncluster#503]
What's the preferable way of tracking compute VM nodes as they come and go away as part of autoscaling cfn stack? I would like to count number of compute nodes and their live time. Thanks

**Comment by lukeseawalker** [comment]
Hi,
the /var/log/sqswatcher log on the master instance keep track of the nodes being added and removed.
Also, the nodes are stored in the DynamoDB table so you can create triggers that automatically respond to events in DynamoDB Streams.
