### ISSUE TITLE
Ability to change the Scaling Settings once a Cluster is Running

### ISSUE THREAD

**Issue by cancan101** [awslabs/cfncluster#51]
Ability to change the scaling settings once a cluster is running or add instructions to the docs if this is already possible.

**Comment by dougalb** [comment]
Simply update the scaling config and run cfncluster update

http://cfncluster.readthedocs.org/en/latest/configuration.html#scaling

**Comment by cancan101** [comment]
Perhaps a silly question, but what does `update` do: https://github.com/awslabs/cfncluster/blob/4f634553e5054baf3e735b3ad907c9ac029ba5f7/cli/README#L12 ?

**Comment by dougalb** [comment]
The cfncluster update command applies updated configuration to a running
cluster. For example scaling or instance type.

**Comment by cancan101** [comment]
I think `InitialQueueSize` is being set to the size of the queue when I re-applied; I am seeing a value of 4 there even though I have 2 in my config (I have 4 nodes running right now).

**Comment by dougalb** [comment]
If you wish the `initial_queue_size` to be updated, you should pass the `--reset-desired` option when calling update.

```
$ cfncluster update --help
usage: cfncluster update [-h] [--norollback] [--template-url TEMPLATE_URL]
                         [--cluster-template CLUSTER_TEMPLATE]
                         [--extra-parameters EXTRA_PARAMETERS]
                         [--reset-desired]
                         cluster_name

positional arguments:
  cluster_name          update a cfncluster with the provided name.

optional arguments:
  -h, --help            show this help message and exit
  --norollback, -nr     disable stack rollback on error
  --template-url TEMPLATE_URL, -u TEMPLATE_URL
                        specify a URL for a custom cloudformation template
  --cluster-template CLUSTER_TEMPLATE, -t CLUSTER_TEMPLATE
                        specify a specific cluster template to use
  --extra-parameters EXTRA_PARAMETERS, -p EXTRA_PARAMETERS
                        add extra parameters to stack update
  --reset-desired, -rd  reset the current ASG desired capacity to initial
                        config values
```

**Comment by adavanisanti** [comment]
Hi @dougalb,  
Option --reset-desired works well and adds/removes instances. 
I am using slurm for scheduling. However, I don't see the new instances in sinfo. Is the slurm.conf updated once the queue size is updated or should I update it manually?

Thanks
Santi

**Comment by bwbarrett** [comment]
@adavanisanti, once the new compute nodes are running, they should be added to the slurm.conf.  If they're not, please open a new ticket with information such as cfncluster version, the state of the SQS queue for that cluster, and such.  If you're not using CfnCluster 1.3.2, it will be easier for us to help if you upgrade (so we can eliminate old bugs from the possibilities).

**Comment by adavanisanti** [comment]
@bwbarrett I am using 1.3.2. New compute nodes are getting added to slurm.conf. However, I think there is a significant delay between nodes running (from ec2 dashboard) to be available for cluster compute (in slurm.conf and sinfo). Is there a way to estimate this delay?
