### ISSUE TITLE
Scaling Seems to Double Apply

### ISSUE THREAD

**Issue by cancan101** [awslabs/cfncluster#52]
I think there is an issue where the nodes take longer to start up than the threshold time leading to the start trigger firing twice.

Right now I have:
```
Execute policy when:
cfncluster-mycluster7-AddCapacityAlarm-XXXXX	
breaches the alarm threshold: pending >= 4 for 2 consecutive periods of 60 seconds
for the metric dimensions
Stack = cfncluster-mycluster7
Take the action:
Add	2 instances	
And then wait: 120 seconds before allowing another scaling activity
```
but I am seeing 4 nodes started.

**Comment by dougalb** [comment]
All scaling settings are configurable. Depending on the instance sizes and any customization, the time to add new instances may be longer than the default cooldown values. You should update the settings to match your needs.

**Comment by cancan101** [comment]
Might be worth adding a note to the docs around this but the scaling does not wait for the previous instances to come up before adding more (this assume the time to start exceeds the timeout period).

**Comment by jbyars** [comment]
Please add a note to the docs on this. I had the same problem. When the scaling_cooldown countdown starts is not inherently obvious.
