### ISSUE TITLE
Export DRMAA_LIBRARY_PATH

### ISSUE THREAD

**Issue by cancan101** [awslabs/cfncluster#53]
When using SGE, export `DRMAA_LIBRARY_PATH=/opt/sge/lib/lx-amd64/libdrmaa.so` in one of the profile files.

**Comment by dougalb** [comment]
The current version of CfnCluster uses a default SGE install from https://arc.liv.ac.uk/trac/SGE. Customization of the environment can be easily carried out using pre/post install actions -http://cfncluster.readthedocs.org/en/latest/pre_post_install.html or by configuring an application enviornment that is attached to the cluster via the EBS snapshot setting - http://cfncluster.readthedocs.org/en/latest/configuration.html#ebs-snapshot-id
