### ISSUE TITLE
CfnClusterUserPolicy S3GetObject  iam policy issue 

### ISSUE THREAD

**Issue by extremoburo** [awslabs/cfncluster#554]
Hi all, 

I think there's something wrong in  the documentation so the policy added for version >= 1.5.3 named "Sid": "S3GetObj" is rejected by the IAM policy reviewer , it says there's something wrong within the resource creation using Fn:Join :

`            "Resource": [
              {
                "Fn::Join": [
                  "",
                  [
                    "arn:",
                    {
                      "Fn::FindInMap": [
                        "AWSRegion2Capabilites",
                        {
                          "Ref": "AWS::Region"
                        },
                        "arn"
                      ]
                    },
                    ":s3:::",
                    {
                      "Ref": "AWS::Region"
                    },
                    "-cfncluster/*"
                  ]
                ]
              }
            ]`          

To reproduce it just go to the AWS console -> IAM -> create a new policy and paste the User Policy provided in https://cfncluster.readthedocs.io/en/latest/iam.html . 

Any tip ? thks

**Comment by lukeseawalker** [comment]
Thank you for pointing out, it's actually in the wrong section of the doc, should be into the CfnClusterInstancePolicy to be like

          {
              "Resource": [
                  "arn:aws:s3:::<REGION>-cfncluster/*"
              ],
              "Action": [
                  "s3:GetObject"
              ],
              "Sid": "S3GetObj",
              "Effect": "Allow"
          }

L

**Comment by extremoburo** [comment]
Hi Luca, I can confirm with this fix it's working perfectly. thks
