### ISSUE TITLE
can i allow 2 different SSH keys to access the cluster?

### ISSUE THREAD

**Issue by floswald** [awslabs/cfncluster#564]
* suppose i set up the cluster with SSH keypair number 1
* I have a colleague who wants to use the cluster as well. can I add his SSH key number 2 somehow to the config so that they could log on to the master as well?

**Comment by enrico-usai** [comment]
Hi @floswald , currently there are no configuration parameters to enable multiple ssh-keys.
You could think to use a [custom bootstrap action](https://cfncluster.readthedocs.io/en/latest/pre_post_install.html).

**Comment by sean-smith** [comment]
To add to @enrico-usai's answer, you just need to append their public key to the autorized_keys file in your post install script. This is as simple as:

```bash
echo "ssh-rsa AAAA...11bh" >> ~/.ssh/authorized_keys
```

**Comment by sean-smith** [comment]
Stopping the cluster only stops the compute nodes. If you'd like to stop the master as well, first stop the cluster:

```bash
cfncluster stop HelloCluster
```
 
Wait until the compute instances are stopped. You can see the compute instances that are running with:

```bash
cfncluster instances HelloCluster
```

Go to the EC2 Console and find the master instance. You can use the instance id from the previous command. Stop that instance.

To restart the cluster, first start the master instance, wait for the master instance to become available, then run:

```bash
cfncluster start HelloCluster
```

**Comment by floswald** [comment]
awesome. you made my day sir. that's *exactly* how I wanted to use this.
