### ISSUE TITLE
post_install error

### ISSUE THREAD

**Issue by karlvirgil** [awslabs/cfncluster#565]
I am unable to get an efs volume to mount automatically using a post_install script.

Here's my config file:
[config.txt](https://github.com/awslabs/cfncluster/files/2420584/config.txt)

This is the post_install script:
[mount_efs_alinux.sh](https://github.com/awslabs/cfncluster/files/2420615/mount_efs_alinux.sh.txt)

The cluster gets created fine, but when I log in I find that the /efs has not been mounted.
The log file indicates an error:
[cfn-init.log](https://github.com/awslabs/cfncluster/files/2420628/cfn-init.log)

These are the relevant lines:
1484 2018-09-26 15:54:26,662 [INFO] Command runpostinstall succeeded
1485 2018-09-26 15:54:26,662 [DEBUG] Command runpostinstall output: mount.nfs4: Failed to resolve
     server s3: Name or service not known

I'm not sure how to debug this further.

**Comment by karlvirgil** [comment]
I realized that I had my arguments off by one.  Should have been
```
fsid=$2
mnt=$3
```
Everything works fine now.

**Comment by sean-smith** [comment]
For future reference, I've updated the docs to explain this: https://cfncluster.readthedocs.io/en/latest/pre_post_install.html#arguments
