### ISSUE TITLE
master_subnet_id shows up twice in the docs

### ISSUE THREAD

**Issue by cancan101** [awslabs/cfncluster#57]
* https://github.com/awslabs/cfncluster/blob/da3aa2e2e3840f8bd69971168ebd17a10db15f66/docs/source/configuration.rst#master_subnet_id
* https://github.com/awslabs/cfncluster/blob/da3aa2e2e3840f8bd69971168ebd17a10db15f66/docs/source/configuration.rst#master_subnet_id-1

**Comment by dougalb** [comment]
A pull request with a fix is typically the quickest and community approach for fixing doc errors.
