### ISSUE TITLE
Allow additional_sg to be a list rather than just one item

### ISSUE THREAD

**Issue by cancan101** [awslabs/cfncluster#58]
It looks like `additional_sg` only allows one additional sg. I suggest allowing this to be a comma separated list.

**Comment by dougalb** [comment]
Due to the Fn:Equals on the AddAdditionalSG condition, it is not possible to use a CommaDelimitedList parameter type for the AdditionalSG parameter. Additionally the condition is required to enable the dynamic addition and removal of the security group to the MasterENI.

**Comment by cancan101** [comment]
What do you mean by:
>Additionally the condition is required to enable the dynamic addition and removal of the security group to the MasterENI.
