### ISSUE TITLE
Creating cluster that doesn't grant SSH to internet

### ISSUE THREAD

**Issue by hellmersjl3ds** [awslabs/cfncluster#580]
When I create a cluster of CfnCluster a default security group is added which has SSH open to 0.0.0.0/0.

This is considered a security violation to my corporate AWS admins, and I always have to get ride of it automatically.

Is there a way to NOT have SSH open to 0.0.0.0/0 by default?

**Comment by sean-smith** [comment]
https://cfncluster.readthedocs.io/en/latest/configuration.html#ssh-from

**Comment by hellmersjl3ds** [comment]
Thanks Sean.

The problem was I was putting the vpc_security_group_id with the cluster section not with the VPC section.
