### ISSUE TITLE
Source / Destination IP Checks Disabled

### ISSUE THREAD

**Issue by cancan101** [awslabs/cfncluster#59]
Why is the ["Source / Destination IP Checks" disabled](https://github.com/awslabs/cfncluster/blob/8ef1993582b845e546c01a9e92f77c5f06871f16/cloudformation/cfncluster.cfn.json#L2512) on the master node?

**Comment by dougalb** [comment]
When the MasterServer operates as NAT for the compute subnet, this is a requirement.

**Comment by cancan101** [comment]
Under what conditions does the:
>MasterServer operates as NAT for the compute subnet, this is a requirement.

? I don't think I have seen any docs around this feature.

**Comment by dougalb** [comment]
It is the 2nd example in the docs - http://cfncluster.readthedocs.org/en/latest/networking.html

**Comment by cancan101** [comment]
Is there any way to disable the source /destination IP only when in that configuration?
