### ISSUE TITLE
cfncluster ignores my custom ami

### ISSUE THREAD

**Issue by andyjones1982** [awslabs/cfncluster#591]
When I run cfncluster, it ignores my custom_ami entry, and just uses the default instead. 

I needed to build a custom AMI with g++ 7.3.0 on it. I did that using the instructions here
https://cfncluster.readthedocs.io/en/latest/ami_customization.html
and here
https://stackoverflow.com/a/48796814
I now have an ami from which I can reliably start new instances having g++7.3.0, but when I put it in the custom_ami field, cfncluster ignores it.

**Comment by lukeseawalker** [comment]
Hi @andyjones1982,
can you please post your configuration file? What OS this AMI is based on?
What version of cfncluster are you using?

Thanks,
L

**Comment by andyjones1982** [comment]
The OS is alinux. The base AMI is 
us-east-1: ami-07f61c3e18538c70c
cfncluster version 1.5.4

The config file is below (the problem is under [cluster bigdrive]
```
[global]
update_check = true
sanity_check = true
cluster_template = default

[aws]
aws_region_name = us-east-1

[vpc public]
master_subnet_id = subnet-3b07b334
vpc_id = vpc-63a8c518

[aliases]
ssh = ssh -i ~/.ssh/aws.pem {CFN_USER}@{MASTER_IP} {ARGS}

[cluster default]
vpc_settings = public
key_name = AWSprivatekeypair
key_location = /home/ajones/.ssh/aws.pem

master_instance_type = t2.micro
compute_instance_type = c5.large

initial_queue_size = 0
max_queue_size = 100
maintain_initial_size = true

scheduler = sge

scaling_settings = custom

cluster_type = spot
spot_price = 0.05


[cluster bigdrive]
vpc_settings = public
key_name = AWSprivatekeypair
key_location = /home/ajones/.ssh/aws.pem

custom_ami = ami-0d45ebe85db13dd27

master_instance_type = t2.micro
compute_instance_type = h1.2xlarge
extra_json = { "cfncluster" : { "cfn_scheduler_slots" : "4" } }

initial_queue_size = 0
max_queue_size = 40
maintain_initial_size = true

scheduler = sge

scaling_settings = custom

cluster_type = spot
spot_price = 0.5

[scaling custom]
scaling_threshold2 = 10
scaling_adjustment = 5
```

**Comment by lukeseawalker** [comment]
You should then use
```
cluster_template = bigdrive
```

L

**Comment by andyjones1982** [comment]
Thank you! 
I realise my problem now. I thought that
`cfncluster create bigdrive`
I thought this would select bigdrive cluster template but now I see it is just a name. It does not use the template. What I need is 
`cfncluster create -t bigdrive bigdrive`
