### ISSUE TITLE
Upgrade AMI to Centos 6.7

### ISSUE THREAD

**Issue by cancan101** [awslabs/cfncluster#60]
http://wiki.centos.org/Manuals/ReleaseNotes/CentOS6.7

**Comment by dougalb** [comment]
CentOS 6.7 is not officially released, see release notes and
http://wiki.centos.org/AdditionalResources/Repositories/CR.

**Comment by dougalb** [comment]
Closing this, as 6.7 will be supported when released as part of regular CfnCluster updates.
