### ISSUE TITLE
Add Docs about what IAM Permissions are Needed

### ISSUE THREAD

**Issue by cancan101** [awslabs/cfncluster#62]
Add Docs about what IAM Permissions are Needed in order to start the cluster. For example when permissions should I grant the [user that I specify in the config](http://cfncluster.readthedocs.org/en/latest/configuration.html#aws)?

**Comment by dougalb** [comment]
As the CloudFormation stack creates an EC2 IAM Role for the cluster, you typically need a user with the Power User policy. 

Also I suggest that these questions might be best directed to the AWS HPC forum, as they are not actual software issues in the CfnCluster code. 

https://forums.aws.amazon.com/forum.jspa?forumID=192
