### ISSUE TITLE
Changing the size of the predefined AMI's EBS volume

### ISSUE THREAD

**Issue by btatsis** [awslabs/cfncluster#63]
Dear All,

I am trying to modify the size of the EBS volume of the prebuilt AMI (ami-f1dd7e9a).
By changing its size from 10GB to 30GB,  cfncluster cannot create the master node and it's rolling back.
My aim is to set-up an AMI with all the source code and the necessary input files, based on the prebuild AMI (ami-f1dd7e9a).
Is there any other possible solution or workaround?

Thanks in advance,
Bill

**Comment by dougalb** [comment]
Are you using the http://cfncluster.readthedocs.org/en/latest/configuration.html#master-root-volume-size option in the config? What specific version of CfnCluster are you using?

When testing a new configuration, using the --norollback option, which disables rollback and then you can usually access the instance for troubleshooting.

**Comment by btatsis** [comment]
Hi Dougal,

Thank you for your swift response. 
I am currently using the latest version [0.0.22] of cfncluster. 
Indeed, by adding the options master_root_volume_size and compute_root_volume_size in my cfncluster config file solved the issue with the root volume size. 

Best, 
Bill

**Comment by dougalb** [comment]
Okay, as an FYI, the typical approach I would take for your situation is setting up all the source code and input files in the /shared directory and then making an EBS snapshot from this volume. You can then easily attach this snapshot for future clusters - http://cfncluster.readthedocs.org/en/latest/configuration.html#ebs-snapshot-id.

This has the advantage that you don't need to build a custom AMI, which typically means you need to rebuild everything for newer versions of CfnCluster.

**Comment by btatsis** [comment]
Hi Dougal, thank you very much for your advice.
It works perfectly fine!
