### ISSUE TITLE
TemplateURL must reference a valid S3 object to which you have access

### ISSUE THREAD

**Issue by jpiper** [awslabs/cfncluster#64]
Hello,

I seem to be getting the same error as #33  with version 0.0.22
```
(cfncluster)HLI-MACPRO48:envs jpiper$ cfncluster create mycluster
Starting: mycluster
TemplateURL must reference a valid S3 object to which you have access.
```
```
(cfncluster)HLI-MACPRO48:envs jpiper$ cfncluster version
0.0.22
```
```
(cfncluster)HLI-MACPRO48:envs jpiper$ pip freeze
boto==2.38.0
cfncluster==0.0.22
wheel==0.24.0
```

**Comment by jpiper** [comment]
It appears that the code here

https://github.com/awslabs/cfncluster/blob/master/cli/cfncluster/cfnconfig.py#L156-L165

needs to be updated due a permanent redirect on those s3 paths.

However, if I change the code to the new endpoint:

    self.template_url = ('https://cfncluster-%s.s3.amazonaws.com/templates/cfncluster-%s.cfn.json'
                                         % (self.region, self.version))

I still get

    "TemplateURL must reference a valid S3 object to which you have access."

**Comment by dougalb** [comment]
Hi, what EC2 region are you using? I'll try and recreate the issue.

**Comment by jpiper** [comment]
us-west-2

**Comment by dougalb** [comment]
I am trying to recreate and not getting the error message.

$ module load ec2-us-west-2
dougalb at a8206614f0f3 in ~
$ workon cfncluster
(cfncluster)dougalb at a8206614f0f3 in ~
$ cfncluster create mycluster
Starting: mycluster
Stack [cfncluster-mycluster] already exists
(cfncluster)dougalb at a8206614f0f3 in ~
$ cfncluster create mycluster2
Starting: mycluster2
Status: cfncluster-mycluster2 - CREATE_IN_PROGRESS                              ^C
Exiting...
(cfncluster)dougalb at a8206614f0f3 in ~
$ pip freeze
boto==2.38.0
cfncluster==0.0.22
wsgiref==0.1.2
(cfncluster)dougalb at a8206614f0f3 in ~
$

Can you email me a copy of ~/.cfncluster/cfncluster-cli.log to dougalb at amazon dot com

**Comment by andrey-epam** [comment]
Hi - any update there ? I have the same error in us-west-2 zone. 
ubuntu@ip-249:~$ cfncluster create test-one
Starting: test-one
TemplateURL must reference a valid S3 object to which you have access.

**Comment by dougalb** [comment]
Do you have region= in your config file or AWS_DEFAULT_REGION set in your environment?

**Comment by andrey-epam** [comment]
I guess :
[aws]
aws_region_name = us-west-2
aws_access_key_id = XXX
aws_secret_access_key =XXX

**Comment by dougalb** [comment]
Can you send me the config, minus any keys and also the ~/.cfncluster/cfncluster-cli.log. I am unable to reproduce the error and it seems to be rare for others.

**Comment by dougalb** [comment]
You are welcome to email to dougalb at amazon dot com, if you prefer not to post them.

**Comment by andrey-epam** [comment]
Thank you - just sent at amazon.com

**Comment by ScottZimmerman** [comment]
I'm also having the same issue, also us-west-2. Could you post the solution if you've found it?

**Comment by andrey-epam** [comment]
Try to put in config:

    template_url = https://cfncluster-us-west-2.s3.amazonaws.com/templates/cfncluster-0.0.22.cfn.json

If it does not help you need full IAM user full permissions.

IAM service account I  use has a read/write access in our S3 bucket . I put cfncluster-0.0.22.cfn.json file there – does not help.

**Comment by dougalb** [comment]
This is an issue with the IAM user launching the cluster. The upcoming release of CfnCluster 1.0 supports using an existing EC2 IAM role when launching a cluster, this reduces the capabilities needed to launch a cluster. More details on the beta release can be found here - https://forums.aws.amazon.com/ann.jspa?annID=3471

**Comment by dougalb** [comment]
Using existing IAM roles is now part of CfnCluster and so this should be a non-issue now.
