### ISSUE TITLE
post_install using non-public-read script

### ISSUE THREAD

**Issue by jonr667** [awslabs/cfncluster#65]
Hello,

I'm trying to create a post_install script to handle all the fun environmental customizations.  When I go by the docs and set the file to be 'public-read' everything works fine.  However if I attempt use a script set to be accessible only by the IAM user creating the account and a config line such as 

post_install = s3://mybucket/testme.sh

the cnfcluster script fails to create the cluster.  I guess I had assumed that the post_install would have access to the aws_access_key_id and aws_secret_access_key environment variables.  Is there any reasonable way to not have the install script world readable?

Thanks!

**Comment by dougalb** [comment]
Please try adding access to S3 via the config - http://cfncluster.readthedocs.org/en/latest/s3_resources.html. You can typically just add * access to a s3_read_resource. This should enabled the EC2 IAM role to have S3 access.

**Comment by jonr667** [comment]
Sorry I missed that line, it worked perfectly when added! Thank you!
