### ISSUE TITLE
Provide IP output for failed cluster creation with --norollback specified

### ISSUE THREAD

**Issue by johnbot1** [awslabs/cfncluster#69]
When building new clusters I often find it necessary to use the --norollback option so I can get into the Master instance and check logs. However, running cfncluster status <cluster-name> on a failed cluster with running Master does not produce the instances public or private IP address as it does with a successful cluster launch. 

Is there a design reason why the status command does not provide IP information on a failed cluster launch that has a master running (--norollback)? Running something like aws(cli) ec2 describe-instances --instance-ids i-a440567f | grep PublicIpAddress works but it's not as convenient. 

John

**Comment by sean-smith** [comment]
With CfnCluster 1.5.2 you can do `cfncluster ssh your_cluster` which will work as long as the master is running. To get the ip address just add the dryrun flag `cfncluster ssh your_cluster --dryrun`
