### ISSUE TITLE
Indefinite Hang on MasterServer - CREATE_IN_PROGRESS

### ISSUE THREAD

**Issue by xanderdunn** [awslabs/cfncluster#76]
I installed cfncluster on Ubuntu 14.04 with `sudo pip install cfncluster`.  My config: 

```
[cluster default]
vpc_settings = test
key_name = mykey
cluster_type = spot
spot_price = 0.030
use_public_ips = false
custom_ami = ami-######
compute_instance_type = c4.large
master_root_volume_size = 50

[vpc test]
master_subnet_id = subnet-######
vpc_id = vpc-######

[global]
update_check = true
sanity_check = true
cluster_template = default
```

When I `cfncluster create default`, I see it present the status of a few things being created, and then it hangs indefinitely on: 
```
$ cfncluster create default
Starting: default
Status: MasterServer - CREATE_IN_PROGRESS
```

In the AWS online console I can see the node named "Master" has successfully started and status checks have passed.  It has an elastic IP and I can SSH into it.

**Comment by dougalb** [comment]
The issue may be that the requested compute instances are not launching for the price you are requesting. Check the EC2 console for the spot requests created for the compute instances and make sure your bid is accepted.

**Comment by xanderdunn** [comment]
Thanks for your help.  

I just tried again.  Master is up, status checks passed.  I waited for several minutes and never saw any spot requests created.  It looks like by default the initial queue size is 2, but I'm not seeing any spot requests.  I'm using the same AMI user and password that I've successfully been using with StarCluster and boto3 to request spot instances.  The price of 0.030 is nearly always sufficient for c4.large, which are typically at 0.020.

**Comment by dougalb** [comment]
Have you tested without the custom_ami? Does a basic cluster launch?

Can you email me your account number to dougalb at amazon dot com.

**Comment by dougalb** [comment]
Are you still having issues?

**Comment by xanderdunn** [comment]
@dougalb Thanks for your help.  Yes, I am still facing the same issue.  I'm looking for the time to try your suggestions.

**Comment by xanderdunn** [comment]
@dougalb helped me figure out this is because I hadn't set up my images to be compatible with cfncluster.  I completely missed the fact that installing the cfn tools on the image is necessary.
