### ISSUE TITLE
Configure failing in python 3.5.1

### ISSUE THREAD

**Issue by msto** [awslabs/cfncluster#78]
Hi,

Are there plans to make cfncluster python 3 compatible? I'm receiving the following error when I try to run `cfncluster configure` under 3.5.1.

    AttributeError: module 'easyconfig' has no attribute 'configure'

Thanks!

**Comment by msto** [comment]
Perplexingly, easyconfig throws this error in both Python 2.7.10 and 3.5.1, but cfncluster only throws the error in Python 2.7.10. 

#### easyconfig from REPL

Python 2.7.10

    In [9]: sys.version
    Out[9]: '2.7.10 |Anaconda 2.1.0 (64-bit)| (default, Oct 19 2015, 18:04:42) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'
    In [10]: easyconfig.__version__
    Out[10]: '0.1.2'
    In [11]: easyconfig.configure
    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-11-3dd152134a23> in <module>()
    ----> 1 easyconfig.configure
    
    AttributeError: 'module' object has no attribute 'configure'

Python 3.5.1 

    In [6]: sys.version
    Out[6]: '3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'
    In [7]: easyconfig.__version__
    Out[7]: '0.1.2'
    In [8]: easyconfig.configure
    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-8-3dd152134a23> in <module>()
    ----> 1 easyconfig.configure
    
    AttributeError: module 'easyconfig' has no attribute 'configure'
    In [9]:

#### easyconfig from cfncluster

Python 2.7.10

    $ python2 $(which cfncluster) configure
    Cluster Template [default]:

Python 3.5.1

    $ python3 $(which cfncluster) configure
    Traceback (most recent call last):
      File "/apps/lab/miket/anaconda/2.0.1/envs/py35/bin/cfncluster", line 11, in <module>
        sys.exit(main())
      File "/apps/lab/miket/anaconda/2.0.1/envs/py35/lib/python3.5/site-packages/cfncluster/cli.py", line 136, in main
        args.func(args)
      File "/apps/lab/miket/anaconda/2.0.1/envs/py35/lib/python3.5/site-packages/cfncluster/cli.py", line 25, in configure
        easyconfig.configure(args)
    AttributeError: module 'easyconfig' has no attribute 'configure'

**Comment by dougalb** [comment]
Does cfncluster version fail as well?

**Comment by msto** [comment]
Thanks for the quick response.

Yes, `version` fails similarly under Python 3.

    AttributeError: module 'cfncluster' has no attribute 'version'

However, it also fails under Python 2 with the following error. 

    $ python2 /apps/lab/miket/anaconda/2.0.1/envs/py35/bin/cfncluster version
    Traceback (most recent call last):
      File "/apps/lab/miket/anaconda/2.0.1/envs/py35/bin/cfncluster", line 11, in <module>
        sys.exit(main())
      File "/apps/lab/miket/anaconda/2.0.1/lib/python2.7/site-packages/cfncluster/cli.py", line 136, in main
        args.func(args)
      File "/apps/lab/miket/anaconda/2.0.1/lib/python2.7/site-packages/cfncluster/cli.py", line 43, in version
        cfncluster.version(args)
      File "/apps/lab/miket/anaconda/2.0.1/lib/python2.7/site-packages/cfncluster/cfncluster.py", line 27, in version
        config = cfnconfig.CfnClusterConfig(args)
      File "/apps/lab/miket/anaconda/2.0.1/lib/python2.7/site-packages/cfncluster/cfnconfig.py", line 37, in __init__
        self.version = pkg_resources.get_distribution("cfncluster").version
      File "/apps/lab/miket/anaconda/2.0.1/lib/python2.7/site-packages/distribute-0.6.15-py2.7.egg/pkg_resources.py", line 298, in get_distribution
        if isinstance(dist,Requirement): dist = get_provider(dist)
      File "/apps/lab/miket/anaconda/2.0.1/lib/python2.7/site-packages/distribute-0.6.15-py2.7.egg/pkg_resources.py", line 177, in get_provider
        return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
      File "/apps/lab/miket/anaconda/2.0.1/lib/python2.7/site-packages/distribute-0.6.15-py2.7.egg/pkg_resources.py", line 654, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/apps/lab/miket/anaconda/2.0.1/lib/python2.7/site-packages/distribute-0.6.15-py2.7.egg/pkg_resources.py", line 552, in resolve
        raise DistributionNotFound(req)
    pkg_resources.DistributionNotFound: cfncluster

**Comment by dougalb** [comment]
That's very strange, all initial testing is done on python 2.7.

**Comment by dougalb** [comment]
What OS are you testing on? How did you install CfnCluster?

**Comment by msto** [comment]
Sorry, it looks like there was an issue with the pip install in that conda environment. I created a fresh environment and `version` looks like it's working appropriately.

    $ python --version
    Python 2.7.11 :: Continuum Analytics, Inc.
    $ cfncluster version
    Default config /PHShome/my520/.cfncluster/config not found
    You can copy a template from here: /apps/lab/miket/anaconda/2.0.1/envs/py27/lib/python2.7/site-packages/cfncluster/examples/config

I'm on RHEL 6.5 and installed with pip 7.1.2.

**Comment by dougalb** [comment]
No problem. Are you installing 0.0.22 from PyPi or the latest 1.0 beta? For more information on the beta, check here - https://forums.aws.amazon.com/ann.jspa?annID=3471. If you are just getting started with CfnCluster, I would highly recommend starting with the latest release.

**Comment by bcthomas** [comment]
Sorry to be commenting on a year old issue, but I cannot get cfncluster to work with 3.5.2 (works fine with 2.7).  Is this a known issue?  The only requirements I see in the docs where it specifically says 2.7 is for the windows section (I'm using both os x and a modern linux).  If 3.5.2 is not supported, are there plans to?

Just for reference, here is the situation (for os x)...
```
# pyenv version
3.5.2 (set by /Users/bct/.pyenv/version)
# pip install cfncluster --upgrade
Requirement already up-to-date: cfncluster in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages
Requirement already up-to-date: boto>=2.42.0 in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from cfncluster)
Requirement already up-to-date: awscli>=1.10.56 in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from cfncluster)
Requirement already up-to-date: botocore==1.4.92 in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from awscli>=1.10.56->cfncluster)
Requirement already up-to-date: PyYAML<=3.12,>=3.10 in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from awscli>=1.10.56->cfncluster)
Requirement already up-to-date: colorama<=0.3.7,>=0.2.5 in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from awscli>=1.10.56->cfncluster)
Requirement already up-to-date: docutils>=0.10 in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from awscli>=1.10.56->cfncluster)
Requirement already up-to-date: s3transfer<0.2.0,>=0.1.9 in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from awscli>=1.10.56->cfncluster)
Requirement already up-to-date: rsa<=3.5.0,>=3.1.2 in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from awscli>=1.10.56->cfncluster)
Requirement already up-to-date: python-dateutil<3.0.0,>=2.1 in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from botocore==1.4.92->awscli>=1.10.56->cfncluster)
Requirement already up-to-date: jmespath<1.0.0,>=0.7.1 in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from botocore==1.4.92->awscli>=1.10.56->cfncluster)
Requirement already up-to-date: pyasn1>=0.1.3 in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from rsa<=3.5.0,>=3.1.2->awscli>=1.10.56->cfncluster)
Requirement already up-to-date: six>=1.5 in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from python-dateutil<3.0.0,>=2.1->botocore==1.4.92->awscli>=1.10.56->cfncluster)
# cfncluster configure
Traceback (most recent call last):
  File "~/.pyenv/versions/3.5.2/bin/cfncluster", line 11, in <module>
    load_entry_point('cfncluster==1.3.1', 'console_scripts', 'cfncluster')()
  File "~/.pyenv/versions/3.5.2/lib/python3.5/site-packages/cfncluster/cli.py", line 154, in main
    args.func(args)
  File "~/.pyenv/versions/3.5.2/lib/python3.5/site-packages/cfncluster/cli.py", line 25, in configure
    easyconfig.configure(args)
AttributeError: module 'easyconfig' has no attribute 'configure'
```
