### ISSUE TITLE
Add tags to EC2 and EBS resources for billing

### ISSUE THREAD

**Issue by digout** [awslabs/cfncluster#79]
Is there any way to add custom tags to EC2 and EBS instances?
It would enable costs split per Project, for example.

**Comment by dougalb** [comment]
Yes, you can pass tags using the following option to the create command:

    $ cfncluster create --tags '{ "CostCenter" : "A12345", "Project" : "NewProject" }' mycluster

That will pass the tags to the CloudFormation CreateStack call http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html#Tags and then through to EC2 resources such as EC2, EBS and VPC.

**Comment by digout** [comment]
Excellent!
