### ISSUE TITLE
Broken YouTube link in docs

### ISSUE THREAD

**Issue by kgutwin** [awslabs/cfncluster#85]
See https://github.com/awslabs/cfncluster/blob/master/docs/source/index.rst#additional-resources. The video https://www.youtube.com/watch?v=iHtzy6_WytE is not accessible (YouTube gives the message "this video is unavailable").

**Comment by dougalb** [comment]
Looks like the video has been removed. Thanks for noticing. I think we'll link to https://www.youtube.com/watch?v=2WJcKwAChHE now.

**Comment by kgutwin** [comment]
At the risk of avoiding my own self-promotion, might I also recommend this https://www.youtube.com/watch?v=jp3wfBJgS-A which seems to be a walkthrough/screencap style video.

**Comment by dougalb** [comment]
Doc updates done in fab3f3d, many thanks to @jamiekin for that.
