### ISSUE TITLE
CfnCluster 1.1.1 - Ubuntu 14.04 & SGE

### ISSUE THREAD

**Issue by btatsis** [awslabs/cfncluster#86]
Dear All, 
I tried to use an ubuntu 14.04 AMI (us-west-2: ami-534ba833) with the sge scheduler and I am getting the following message: 
"**ubuntu's job is not allowed to run in any queue**"
Unfortunately, I set-up a snaphshot for using ubuntu and I would to keep using this OS.
Thanks for your help,
Bill

**Comment by dougalb** [comment]
This is an expected message and it is fact just a warning from SGE. Under normal behaviour, all of the instances in the ComputeFleet will terminate if they are idle and reach almost an hour of uptime. You can still submit jobs to the queue and SGE prints the warning message as there are no instances to run your job, however the cluster should then scale up because of the pending jobs. 

Do you see your jobs pending in the qstat output?

**Comment by btatsis** [comment]
Hi, 
thank you for your swift response.
Indeed, I can see the pending jobs, but their status is not changing. All jobs are waiting on queue.
I have to note that I am only using (just for testing) a master node and a spot instance (c3.8xlarge).

This is the submission script I am using:
`#!/bin/bash
#
#$ -cwd
#$ -S /bin/bash
#$ -pe mpi 8
#$ -o job.out
#$ -e job.err

run sth. in parallel`

Output from **qhost**:
HOSTNAME                ARCH         NCPU NSOC NCOR NTHR  LOAD  MEMTOT  MEMUSE  SWAPTO  SWAPUS
----------------------------------------------------------------------------------------------
global                             -               -    -    -    -     -       -       -       -       -
ip-xxx-yyy-zzz-ooo         -               -    -    -    -     -       -       -       -       -

Output from **qstat**:
==============================================================
job_number:                 7
exec_file:                  job_scripts/7
submission_time:            Mon Mar 14 13:29:48 2016
owner:                      ubuntu
uid:                        1000
group:                      ubuntu
gid:                        1000
sge_o_home:                 /home/ubuntu
sge_o_log_name:             ubuntu
sge_o_path:                 /opt/sge/bin:/opt/sge/bin/lx-amd64:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
sge_o_shell:                /bin/bash
sge_o_workdir:              /shared/test
sge_o_host:                 ip-172-31-1-197
account:                    sge
cwd:                        /shared/test
stderr_path_list:           NONE:NONE:job.err
mail_list:                  ubuntu@ip-172-31-1-197.us-west-2.compute.internal
notify:                     FALSE
job_name:                   submit.sh
stdout_path_list:           NONE:NONE:job.out
jobshare:                   0
shell_list:                 NONE:/bin/bash
env_list:                   TERM=NONE
script_file:                submit.sh
parallel environment:  mpi range: 8
binding:                    NONE
job_type:                   NONE
scheduling info:            (Collecting of scheduler job information is turned off)

Thanks for your help.
Bill

**Comment by dougalb** [comment]
What is the status of the spot request in the console? Is your bid price
high enough to launch an instance?

If you email your AWS account number to dougalb at amazon dot com, I can
take a deeper look.

**Comment by btatsis** [comment]
The status of the spot is running. 
The bid price was higher enough to keep alive the instance.

**Comment by btatsis** [comment]
The same issue appears also with this CentOS7 custom ami **us-west-2: ami-5447a434**

**Comment by dougalb** [comment]
I looked at the clusters you have launched and the issue is the following, you are changing the OS using the custom_ami parameter, which is not needed if you are only wanting a different OS. Please use the base_os parameter and do not set custom_ami if you are using the CfnCluster provided AMIs.

I have just pushed an update to the docs - http://cfncluster.readthedocs.org/en/develop/configuration.html#base-os

**Comment by dougalb** [comment]
Also a bit more detail, the output of qhost on a working cluster with your config, should look like this:

```
ubuntu@ip-192-168-1-129:~$ qhost
HOSTNAME                ARCH         NCPU NSOC NCOR NTHR  LOAD  MEMTOT  MEMUSE  SWAPTO  SWAPUS
----------------------------------------------------------------------------------------------
global                  -               -    -    -    -     -       -       -       -       -
ip-192-168-1-24         lx-amd64       32    2   16   32  0.82   59.0G  553.0M     0.0     0.0
ubuntu@ip-192-168-1-129:~$
```

Also you should see that host being added to /var/log/sqswatcher

```
ubuntu@ip-192-168-1-129:~$ sudo cat /var/log/sqswatcher
2016-03-15 18:32:32,196 INFO [sqswatcher:main] sqswatcher startup
2016-03-15 18:33:34,357 INFO [sqswatcher:pollQueue] eventType=autoscaling:TEST_NOTIFICATION
2016-03-15 18:39:35,250 INFO [sqswatcher:pollQueue] eventType=cfncluster:COMPUTE_READY
2016-03-15 18:39:35,250 INFO [sqswatcher:pollQueue] instanceId=i-bfdd9678
2016-03-15 18:39:35,389 INFO [sqswatcher:pollQueue] Adding Hostname: [Reservation:r-b5654770]
2016-03-15 18:39:35,390 INFO [sge:addHost] Adding ip-192-168-1-24
ip-192-168-1-24.us-west-2.compute.internal added to administrative host list
ip-192-168-1-24.us-west-2.compute.internal added to submit host list
root@ip-192-168-1-129.us-west-2.compute.internal added "ip-192-168-1-24.us-west-2.compute.internal" to exechost list
2016-03-15 18:39:35,416 INFO [sge:addHost] Connecting to host: ip-192-168-1-24 iter: 0
2016-03-15 18:39:35,431 INFO [transport:_log] Connected (version 2.0, client OpenSSH_6.6.1p1)
2016-03-15 18:39:35,595 INFO [transport:_log] Authentication (publickey) successful!
ubuntu@ip-192-168-1-129:~$
```

**Comment by btatsis** [comment]
Thanks for your help! 
Now, everything works fine.
