### ISSUE TITLE
Torque and Job Arrays - ScaleUp

### ISSUE THREAD

**Issue by mkosmo** [awslabs/cfncluster#87]
We use a fair number of job arrays with torque and noticed that cfnCluster wasn't scaling up (as expected, at least) with the defined thresholds.  Traced it down to publish_pending:

[centos@ip-10-0-0-30 ~]$ qstat -i | tail -n+6 | awk '{total = total+ $7}END{print total}'
26
[centos@ip-10-0-0-30 ~]$ qstat -it | tail -n+6 | awk '{total = total+ $7}END{print total}'
618

I'm not sure if this is intended behavior, but we locally patched publish_pending:20 with the addition of the -t flag for qstat.

**Comment by dougalb** [comment]
This is intended behaviour and we'll update or you can submit a pull request against the develop branch.

**Comment by mkosmo** [comment]
I'll put together a pull request tonight or tomorrow for you.  Thanks!

**Comment by dougalb** [comment]
All the PRs have been included in cfncluster-1.2.1
