### ISSUE TITLE
shared volume attachment bug

### ISSUE THREAD

**Issue by freecurve** [awslabs/cfncluster#89]
When the shared volume is attached more than one directory down, the compute nodes fail to initialize. Our DevOps person suspects the issue is this: 

In the _compute_base_config.rb recipe in the cfncluser cookbook, the 'directory' resource (the very first one), seems like it should have 'recursive true'. 
I think we are getting chef failures on the compute nodes because of this, and that is part of the problem we are having...

When volume name is attached directly to root : /ourvolume the nodes spin up properly and it all works. 

thanks!

**Comment by dougalb** [comment]
Hi, what version of CfnCluster are you using? Also what is the output of `cat /opt/cfncluster/.bootstrapped`?

**Comment by freecurve** [comment]
version 1.2.1 and I don't have a stack with that feature running at the moment Dougal.

**Comment by dougalb** [comment]
It was a bug in the cookbook, it is fixed now and didn't require a CLI or AMI update, so you should be able to just test with cfncluster-1.2.1.

https://github.com/awslabs/cfncluster-cookbook/commit/2c8efbba6cc32fcf13a91180ab2cba5f2290f50a

**Comment by freecurve** [comment]
Thank you guys! can close .
