### ISSUE TITLE
Rq not counted as pending

### ISSUE THREAD

**Issue by freecurve** [awslabs/cfncluster#90]
this came up before, Rq does not trigger the load alarm; the fix is

pending=$(qstat -g d -s p -u '*' | tail -n+3 | awk '$5 == "qw" || $5 == "Rq" {total = total+ $8} END {print total}')

in publish_pending_jobs (at least for SGE)

**Comment by dougalb** [comment]
Not 100% sure why this is regressed. The last change is here https://github.com/awslabs/cfncluster-cookbook/commit/fb85d0693f72ff131da7d68f5747dc8627055d88#diff-9190b8b61d683ec65a9631a74b8ace61. I'll combine them and update. Should be able to do this without an AMI update.

**Comment by freecurve** [comment]
Thank you. The edit in publish_pending_jobs.sh works.

**Comment by freecurve** [comment]
Hi guys - in /opt/cfncluster/scripts/publish_pending you should have the line: 

pending=$(qstat -g d -s p -u '*' | tail -n+3 | awk '$5 == "qw" || $5 == "Rq" {total = total+ $8} END {print total}')

instead of just "qw" and that way rescheduled jobs will also trigger the alarm. Tested and working. 

thanks!
