### ISSUE TITLE
Ubuntu 16.04 LTS cfncluster AMI release?

### ISSUE THREAD

**Issue by aculich** [awslabs/cfncluster#91]
We are readying an Ubuntu 16.04 LTS release of [our campus community-supported image](http://bce.berkeley.edu/) and would like to build on the cfncluster AWS AMI when it is available, so I wanted to make this feature request to let you know there is interest. If you have a timeline in mind for doing a release with this new version we'd appreciate knowing when so we can plan accordingly.

Thanks,
 Aaron

**Comment by dougalb** [comment]
We haven't looked at Ubuntu 16.04 LTS yet and you're the first to ask! I'll keep the issue here and open it as part of the [cfncluster-cookbook](https://github.com/awslabs/cfncluster-cookbook) project.

**Comment by fideloper** [comment]
Friendly nudge!

**Comment by dougalb** [comment]
Please see the issue in https://github.com/awslabs/cfncluster-cookbook/issues/9 for updates

**Comment by dougalb** [comment]
This has been released as part of cfncluster-1.3
