### ISSUE TITLE
Configed to use Slurm scheduler but didn't work

### ISSUE THREAD

**Issue by yuanzhou** [awslabs/cfncluster#94]
According to the documentation, I should be able to use Slurm as the scheduler. So I added that config 

````
[cluster test]
vpc_settings = cluster-test
key_name = aws-east
scheduler = slurm
````

But after logging into the Master node, and submitted several jobs, I didn't see any compute nodes created to run the jobs.

![capture](https://cloud.githubusercontent.com/assets/195873/14823955/3dce6472-0ba2-11e6-8f69-2581017cde9c.PNG)

Do I need to install slurm or is there anything I missed? I could submit and run all the jobs with SGE scheduler yesterday. FYI, I'm using the Amazon Linux as the OS.

**Comment by yuanzhou** [comment]
Just to update this issue, it took a while after I submitted the jobs to see new compute nodes being created via AWS web console. But I still don't see any output from running `qstat`. Does Slurm uses a different set of commands to see the status?

**Comment by dougalb** [comment]
Yes, SLURM is a different scheduler than SGE and uses different commands. You might want to review the SLURM documentation for how to use SLURM - http://slurm.schedmd.com/tutorials.html.

Also quickly looking at the cluster that you launched, did you create it as a SLURM cluster or did you update it to be a SLURM cluster? CfnCluster does not support modifying the scheduler after a cluster has been created.

**Comment by yuanzhou** [comment]
I was using the default SGE at first, then updated the config file to use Slurm. And I deleted that cluster and created it freshly using the config file that tells cfncluster to use Slurm. It worked after I tested with some slurm commands.

Slurm works very differently from SGE, when I was testing with SGE, new compute nodes got created upon the 3rd job being submitted. With Slurm, I submitted 20 jobs, the same `hellojob.sh`

````
#!/bin/bash
sleep 30
echo "Hello World from $(hostname)"
````

and no new compute nodes got created.

Thanks for replying to my issue. It will be very helpful to tell users this in the cfncluster documentation.

A side note: as several folks have discussed in this thread: https://forums.aws.amazon.com/thread.jspa?threadID=26111

I got the same issue and seeing all those terminated compute nodes still showing on the AWS web console. I know it's not your job to make the changes, hope you can mention this to the right person who designs the instances console page. Cfncluster users can also benefit from this fix.
