### ISSUE TITLE
user cannot qdel the job if spot compute instance drops

### ISSUE THREAD

**Issue by elipapa** [awslabs/cfncluster#95]
If a job is running on a spot compute instance and the instance gets interrupted, the job remains stuck in the `dr` state and deleting as root is necessary. 

The main SGE configuration should contain ENABLE_FORCED_QDEL in the qmaster_params, according to http://serverfault.com/questions/265726/kill-an-sge-job-already-in-deletion-as-user

**Comment by dougalb** [comment]
CfnCluster ships the schedulers using their default configuration. Making changes to the schedulers can be done using a [`post_install`](http://cfncluster.readthedocs.io/en/latest/configuration.html#post-install) script that updates the SGE configuration.
