### ISSUE TITLE
New compute instances created when master instance is stopped

### ISSUE THREAD

**Issue by yuanzhou** [awslabs/cfncluster#96]
I've been testing Cfncluster with Slurm. Today after I got all the jobs finished, I went to AWS web console and manually stopped all the compute node instances as well as the master instance in order to save money. 

Here is the corresponding section of my config file:
````
[cluster test]
vpc_settings = cluster-test
key_name = aws-east
scheduler = slurm
initial_queue_size = 2
max_queue_size = 4
````

After couple of hours, I noticed that 4 new compute nodes have been created while the master instance is still stopped. 

````
[ec2-user@ip-172-31-27-137 ~]$ cfncluster instances test
MasterServer         i-a8e2f133
ComputeFleet         i-1a425081
ComputeFleet         i-e041537b
ComputeFleet         i-434755d8
ComputeFleet         i-b3445628
````

And after I restarted the Master instance, I see this:

````
[ec2-user@ip-172-31-17-53 ~]$ sinfo
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
compute*     up   infinite      0    n/a
[ec2-user@ip-172-31-17-53 ~]$ squeue
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)

````

Is this the desired behavior? It seems the only way I can fully stop all the compute nodes is to run `cfncluster delete test`. Is this a bug or is there a way that we can temporarily stop the cluster and bring it back (at least the master instance) later on?

**Comment by yuanzhou** [comment]
Just to follow up with this issue. I tested again by stopping the master node after finishing running some jobs. This time it didn't create new compute notes. I'm guessing maybe it takes some time to cooldown the compute notes after the master being stopped.

**Comment by yuanzhou** [comment]
Encountered this issue again. Stopped the master after all compute nodes were terminated due to not being used. I waited overnight and came back saw there's a new compute node running while the master is still stopped.

**Comment by f403** [comment]
Do you have MaintainInitialSize == false || InitialQueueSize == 0 ?

**Comment by yuanzhou** [comment]
In my config, 
````
initial_queue_size = 2
````

I use the default `maintain_initial_size` which is `false`.

**Comment by f403** [comment]
One more thing i can guess is pending spot requests. They could be satisfied after you stopped all your instances. And then compute instances could not terminate after 57 minutes because they could not request running jobs from master node.

So, I think cfnCluster is not designed for manual stopping instances (especially master instance).
But you can do this, if you understand how it works (I don't:) ).

**Comment by yuanzhou** [comment]
I think you are right that cfncluster is not designed for manual stopping instances once the cluster is created. That will probably require a real-time check to see if the master node is still running in order for cfncluster to terminate the compute nodes.
