### ISSUE TITLE
Mount s3 bucket to cfncluster via IAM role

### ISSUE THREAD

**Issue by yuanzhou** [awslabs/cfncluster#98]
This issue is more like a question about shared data storage in cfncluster. Is there a way that I can use s3 bucket as a mountpoint in the cluster that all nodes can share?

The reason I'm asking this is because we are planning to use cfncluster to run some algorithms to analyze some large data files. Slurm is used as the job scheduler,  and we wanted to see if it's possible to use s3 to store all the data results as a stable data store. I could mount s3 bucket to master using s3fs, but it seems slurm can't tell all the nodes to store their results back to the mountpoint on master.

**Comment by delocalizer** [comment]
[s3fs-fuse](https://github.com/s3fs-fuse/s3fs-fuse)

**Comment by delocalizer** [comment]
That's not a limitation of slurm, it's the nature of an object store (which is not a filesystem). Anyhow if you're using s3fs already you don't have to have just one mountpoint on the Master, you can mount the bucket on all the compute nodes... there's only "eventual consistency" guarantee if you're accessing the bucket from multiple nodes, but that as good as you can get with this type of storage.

**Comment by yuanzhou** [comment]
Thanks for the reply. I tried s3fs several times and couldn't find a way to mount s3 bucket to all nodes. I could only mount it to the master node. I read through this thread https://github.com/s3fs-fuse/s3fs-fuse/issues/30 but it was not very clear about all things need to be done. Even after I tried to add the mount point in the "/etc/fstab" file.

As you said it's not a Slurm issue and I found this out too. Because when I tried to submit a batch job script that is stored in the mounted s3, slurm said "No such file or directory", which I think is due to the s3 bucket is not mounted onto all compute nodes.

Can you please shed some light on how to mount s3 to all compute nodes and the master? Much appreciated!

**Comment by yuanzhou** [comment]
BTW, I tested with the `s3_read_write_resource` in configuration and it allowed me to read and write to the s3 bucket. According to the documentation http://cfncluster.readthedocs.io/en/latest/s3_resources.html it says that all nodes will have the read and write access. so I was wondering if this implies that I should try to call AWS S3 CLI to read and write instead of using s3fs.

**Comment by delocalizer** [comment]
If you have a workflow that can use s3 directly then aws cli is a great choice. I assumed you had some specific reason for wanting a _filesystem_, in which case you are stuck with something like s3fs. To mount it on all nodes I would create a post_install script containing the mount commands, which you upload to s3 and then reference in cfncluster configuration. This script gets run whenever a cluster node is built, be it Master or Compute, and is AWS recommended way of customizing node installation.

**Comment by yuanzhou** [comment]
Thanks for the suggestion. I've been trying to run the post install script yesterday. Debugging is not very easy. My post install script looks like this:

````
#!/bin/bash

cd /home/ec2-user/

mkdir s3mnt
````

For testing purpose, I wanted to see if the `s3mnt` dir can be created on the master (as well as on all compute nodes, but I can't login to the compute nodes to verify). But after the cluster was created, I didn't see that dir.

I also made the post install script on s3 public and enabled the read and write access in cfncluster config.

````

s3_read_write_resource = arn:aws:s3:::ccd-s3
post_install = https://s3.amazonaws.com/ccd-s3/cfncluster-post_install.sh
````

I'm also wondering is the post install script is being executed by the root instead of ec2-user.

**Comment by yuanzhou** [comment]
I finally got this working. This is what's in the post install script, which is stored in s3 and can be accessed publicly.

````
#!/bin/bash

cd /home/ec2-user/

mkdir s3mnt

chmod 777 s3mnt

yum -y install automake fuse fuse-devel gcc-c++ git libcurl-devel libxml2-devel make openssl-devel

git clone https://github.com/s3fs-fuse/s3fs-fuse.git

cd s3fs-fuse

./autogen.sh

./configure

make

make install

cd ..

echo MYIDENTITY:MYCREDENTIAL > .passwd-s3fs

chmod 600 .passwd-s3fs

s3fs my-s3 /home/ec2-user/s3mnt -o allow_other -o passwd_file=/home/ec2-user/.passwd-s3fs -o umask=0000
````

In my cfncluster config, I have these two lines:

````
s3_read_write_resource = arn:aws:s3:::my-s3
post_install = https://s3.amazonaws.com/my-s3/cfncluster-post_install.sh
````

Just wanted to share so others who have the same issue may get some details.

**Comment by delocalizer** [comment]
That's basically the right way to do it, but you shouldn't put your credentials on the node, and especially  not by echoing them there via hardcoded entry in a shell script - it's only one forgetful moment away from exposing them to everyone online. The right way to do it is to set up IAM role with S3 read/write permissions on the bucket, grant the role to the cfncluster instances, and specify the  "-o iam_role <my_s3_read_write_role>" argument to s3fs.

**Comment by yuanzhou** [comment]
Thanks for the suggestion. I'll do that. Since you mentioned using IAM role with s3fs, do you know can we also specify an IAM role in cfncluster configuration instead of have the AWS credentials in the config file?

![image](https://cloud.githubusercontent.com/assets/195873/15182507/e10a1b22-175a-11e6-9a39-cbc54a829698.png)

**Comment by yuanzhou** [comment]
When you mentioned "grant the role to the cfncluster instances", how do you do that? I created the IAM role (s3fs-iam-role) with s3 full access, and added the `iam_role="s3fs-iam-role"` when mounting the s3 bucket to the cluster instances via the post install script. I don't see the s3 bucket is mounted there. So I'm wondering maybe I didn't grant the IAM role to those cfncluster instances before creating them.

**Comment by yuanzhou** [comment]
Oops, just saw this `ec2_iam_role` in the configuration. I think this is the one I needed. Trying it now.

**Comment by delocalizer** [comment]
Yes you need to assign the IAM role before node creation, which is why it's specified in the config file. See http://cfncluster.readthedocs.io/en/latest/iam.html. You should use the CfnClusterInstancePolicy as a template and add a section with policy for read/write permissions for whatever s3 resources you will be mounting with s3fs.
Re. earlier comment, you don't need AWS credentials in the config file as long as you have previously executed `aws configure`

**Comment by yuanzhou** [comment]
@delocalizer thanks for the instructions. Here is what I did.

1. I added a new policy based on the `CfnClusterInstancePolicy` from http://cfncluster.readthedocs.io/en/latest/iam.html and added the S3 section as well.

2. Created a new role called "cfncluster-iam-role" and attached that `CfnClusterInstancePolicy` to this role.

3. Added `ec2_iam_role` in my `.cfncluster/config` file:

````
[global]
update_check = true
sanity_check = true
cluster_template = ccd

[aws]
aws_access_key_id = xxxxx
aws_secret_access_key = yyyyyyy
aws_region_name = us-east-1

[cluster ccd]
vpc_settings = ccd
key_name = dbmi-aws-east
scheduler = slurm
initial_queue_size = 2
max_queue_size = 4
s3_read_write_resource = arn:aws:s3:::ccd-s3
post_install = https://ccd-s3.s3.amazonaws.com/cfncluster-post_install.sh
ec2_iam_role = arn:aws:iam::495666495561:role/cfncluster-iam-role

[vpc ccd]
master_subnet_id = subnet-65aede3c
vpc_id = vpc-7f88871a
````

As you replied, I also tried to use `aws configure` to put the aws credentials there, it saved the config  to `~/.aws`, I thought it might be still easy to just have the `[aws]` section with credentials in cfncluster config.

But after running `cfncluster create ccd` I got this error:

````
[ec2-user@ip-172-31-27-137 .cfncluster]$ cfncluster create ccd
Starting: ccd
Template format error: Unresolved resource dependencies [RootRole] in the Resources block of the template
````

And when I removed the `ec2_iam_role` line from config, it was fine. I just couldn't figure this out. Hope you can shed some light on me.

**Comment by dougalb** [comment]
By default CfnCluster creates an EC2 IAM Role as part of the cluster stack. The [`ec2_iam_role`](http://cfncluster.readthedocs.io/en/latest/configuration.html#ec2-iam-role) setting causes CfnCluster to no longer create the role and use the provided role. The value should simply be the role name, in your example `cfncluster-iam-role`. 

The [`s3_read_resource`](http://cfncluster.readthedocs.io/en/latest/configuration.html#s3-read-resource) and [`s3_read_write_resource`](http://cfncluster.readthedocs.io/en/latest/configuration.html#s3-read-write-resource) settings are used to add basic S3 access to the stack role and should not be set, when using [`ec2_iam_role`](http://cfncluster.readthedocs.io/en/latest/configuration.html#ec2-iam-role).

In addition, it is best not to modify the [**CfnClusterInstancePolicy**](http://cfncluster.readthedocs.io/en/latest/iam.html#cfnclusterinstancepolicy) directly, rather you can attach up to 10 policies to the role you create for CfnCluster. It is generally better to use an S3 managed policy for S3 or built a specific one for your S3 access requirements.

With regards to credentials, the CfnCluster CLI is built using boto and uses the following precedence - http://boto.readthedocs.io/en/latest/boto_config_tut.html#precedence.

**Comment by yuanzhou** [comment]
@dougalb thanks for your help! I got it work by following your instructions. As you suggested, I created a new policy for s3 access only and attached it together with the `CfnClusterInstancePolicy` from the documentation. Also removed the `s3_read_write_resource ` line and changed the `ec2_iam_role` value to the iam role name.

My s3 bucket was mounted and I could submit batch jobs with slurm inside the mounted s3 directory. So I assume this s3 bucket was also mounted to all other compute nodes.

The only thing I couldn't get work is to have this s3 mounted upon master server reboot. Cron job works on other tasks, but couldn't re-mount this using 
````
@reboot s3fs ccd-s3 /home/ec2-user/s3mnt -o iam_role="cfncluster-iam-role" -o allow_other -o umask=0000
````

I'm guessing I'm not supposed to manually stop/start or reboot the master node since it's a cluster. Am I right about this?

**Comment by yuanzhou** [comment]
Just an update: due to performance issue, we no longer use S3 with CfnCluster, we mounted an EBS volume to the cluster and it worked very well.

**Comment by adavanisanti** [comment]
Hi @dougalb, I am trying to mount s3 on cfncluster instances using s3-fuse. I have s3-fuse installed on my custom ami. Could you please help me with the steps that use iam_role instead of AWS credentials?

**Comment by bwbarrett** [comment]
@adavanisanti: you need to create an IAM role before building the cluster (http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html).  That role should include the S3 permissions you need, as well as the list of permissions that CfnCluster requires (http://cfncluster.readthedocs.io/en/latest/iam.html).  From there, you should be able to specify your new role as the `ec2_iam_role` option in your CfnCluster configuration and be good to go.

**Comment by tylerwmarrs** [comment]
I am having similar issues with utilizing the ec2_iam_role. When I create the cluster based on my configuration it appears to keep creating a new role with the default policies in AWS.

Here is my role with the policies:
![image](https://user-images.githubusercontent.com/18449075/35753538-cdec542a-0825-11e8-8154-4b44a7ea5b9e.png)

Here is my configuration:
![image](https://user-images.githubusercontent.com/18449075/35753586-f54d0fa0-0825-11e8-9629-22d5f56622ec.png)

Here is a screenshot of the default behavior (creation of role):
![image](https://user-images.githubusercontent.com/18449075/35753643-24f31ede-0826-11e8-8302-74bc692b0677.png)

Does anyone have any insight on what is wrong here?

**Comment by tylerwmarrs** [comment]
It only seems to work when I have it defined in the "[cluster default]" section with "cluster default" being set as the template in the configuration.

Here is my full config:

![image](https://user-images.githubusercontent.com/18449075/35755183-dd2a7cfe-082b-11e8-86b8-4ce7e0709204.png)

**Comment by rajachan** [comment]
@tylerwmarrs, there is no relationship between the Cfncluster cluster name and your IAM role name. CfnCluster should not create a new role if a custom one is provided. If you still have your "tiny" cluster running, can you see which role was actually attached to the instances --- was it cfncluster-tiny-RootRole-.. or cfncluster-default?

**Comment by tylerwmarrs** [comment]
The root role was attached. I am aware that there is no relationship
between the names. I coincidentally named mine cfncluster-default. The only
way that I could get it to use my role was to have ec2_iam_role in my
default template and in the tiny cluster template. Having it only set in
the tiny cluster section caused the root role creation and association with
the cluster.
